### ISSUE TITLE
Find a way to add coverage on fork()'ed children ?

### ISSUE THREAD

**Issue by Snaipe** [Snaipe/Criterion#11]
It seems that gcov generates no coverage report for forked children. A bit of googling on the matter yielded no results -- maybe someone knows how to solve this ?

Relevant [stackoverflow question](http://stackoverflow.com/questions/28408811/how-do-i-generate-coverage-reports-for-forkd-children-using-gcov-lcov).

**Comment by Snaipe** [comment]
It was actually dumb; _exit() will of course not call __gcov_flush().

**Comment by haneiko** [comment]
how can i get gcov to work with criterion? any alternative?
