### ISSUE TITLE
Has Criterion mocking support?

### ISSUE THREAD

**Issue by jetm** [Snaipe/Criterion#112]
I found Criterion as a very complete C Unit Testing framework. Reading about Criterion, searching in the repo and between features list, I have not found how to do mocking. Has Criterion mocking support?

**Comment by pvsundarram** [comment]
May be try https://github.com/Snaipe/Mimick by the same author?

**Comment by Snaipe** [comment]
A word of warning -- Mimick isn't ready for use, the API ought to change.

Mocking will not be part of Criterion. I do plan on providing some convenience bridges for existing mocking libraries, though.

**Comment by jetm** [comment]
@pvsundarram :+1: Thanks

@Snaipe: What existing mocking libraries are in your mind?

**Comment by Snaipe** [comment]
For C, [CMock](https://github.com/ThrowTheSwitch/CMock) (and of course Mimick once it hits 1.0) comes to mind. Maybe [CMocka](https://cmocka.org/), if the mock objects can be used standalone.
For C++, [GMock](https://github.com/google/googletest/tree/master/googlemock) or [FakeIt](https://github.com/eranpeer/FakeIt).

**Comment by jetm** [comment]
@Snaipe: Good to know. Thanks!

**Comment by marco-m** [comment]
@Snaipe just discovered Criterion :-) What is the status of Mimick compared to your answer above of March 2016 ? In the meantime, would it make sense to write a small README with best practices to use Criterion and Mimick together (if at all possible with the current status)? Thanks!

**Comment by Snaipe** [comment]
I think Mimick is pretty solid right now, but it needs better testing, and on more platforms. I've been thinking of setting up a few virtualized test beds, but user testing is fine too.

I doubt the API is going to change massively, although we have some subtle things we need to support eventually. For instance, how to deal with functions with specific calling conventions, and foreign functions. I'll probably have to change mmk_mock to support that in the near future.

**Comment by Snaipe** [comment]
Also, w.r.t writing a README, I guess that would be cool to do, although a documentation page for mocking in general could make more sense. I don't think there's much to do anyway with mimick, and I don't think there are "best practices" either, apart from "don't mock criterion's functions when running inside a criterion test", but that's a given.

**Comment by marco-m** [comment]
thanks!

**Comment by dertarr** [comment]
Hi Snaipe,

Recently was looking for a UT framework for a new C/C++ project and found Criterion which seems to be a very interesting piece of work. However, what is the current status of mimick and gmock or fakeit support? There is no header file for fakeit with support for Criterion on their github repo.

**Comment by Snaipe** [comment]
Mimick can be used standalone whatever the testing framework you're using, so it should just work. I do not use gmock nor fakeit, so it would take someone to step up and actually write some glue to make it work.
