### ISSUE TITLE
binary Download Links broken

### ISSUE THREAD

**Issue by roesti77** [Snaipe/Criterion#115]
The Binary Download Links for 
Windows (MSVC - x86_64) and 
Windows (MinGW - x86_64) 
are broken.
Linux and OS X are still working

**Comment by Snaipe** [comment]
And here I was thinking it was fixed. Going to change this ASAP.

In the meantime, you can download the binary releases from the [release page](https://github.com/Snaipe/Criterion/releases/latest)

**Comment by Snaipe** [comment]
Fixed. I included a link to the release page instead of listing downloads.
