### ISSUE TITLE
kubuntu : Criterion build from sources exits with error

### ISSUE THREAD

**Issue by calvinundhobbestc** [Snaipe/Criterion#123]
kubuntu 14.04 32bit, cmake version 2.8.12.2
I am not familiar with cmake, may be I overlook something obvious ?

> $ cd build/
> tc@artcom5:/head/bits/std/base/libcriterion/Criterion-2.2.1/build$ /usr/bin/cmake ..
> -- Updating submodules to their latest/fixed versions
> -- (this can take a while, please be patient)
> -- no specific version given for submodule libcsptr, checking out master
> -- checking out libcsptr's commit/tag master
> -- no specific version given for submodule dyncall, checking out master
> -- checking out dyncall's commit/tag master
> CMake Error at CMakeLists.txt:23 (add_subdirectory):
>   The source directory
> 
>     /head/bits/std/base/libcriterion/Criterion-2.2.1/dependencies/libcsptr
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> CMake Error at CMakeLists.txt:26 (add_subdirectory):
>   The source directory
> 
>     /head/bits/std/base/libcriterion/Criterion-2.2.1/dependencies/dyncall
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/head/bits/std/base/libcriterion/Criterion-2.2.1/build/CMakeFiles/CMakeOutput.log".
> See also "/head/bits/std/base/libcriterion/Criterion-2.2.1/build/CMakeFiles/CMakeError.log".
> 

In CMakeError.log there is an error displayed that  ‘strtok_s’ is undeclared.
But if this leads to dyncall and libcsptr being empty I don't know.
However, here is the CMakeError.log.

> Determining if the prototype strtok_s exists for HAVE_STRTOK_S failed with the following output:
> Change Dir: /head/bits/std/base/libcriterion/Criterion-2.2.1/build/CMakeFiles/CMakeTmp
> 
> Run Build Command:/usr/bin/make "cmTryCompileExec1154642954/fast"
> /usr/bin/make -f CMakeFiles/cmTryCompileExec1154642954.dir/build.make CMakeFiles/cmTryCompileExec1154642954.dir/build
> make[1]: Entering directory `/data/head/bits/std/base/libcriterion/Criterion-2.2.1/build/CMakeFiles/CMakeTmp'
> /usr/bin/cmake -E cmake_progress_report /head/bits/std/base/libcriterion/Criterion-2.2.1/build/CMakeFiles/CMakeTmp/CMakeFiles 1
> Building C object CMakeFiles/cmTryCompileExec1154642954.dir/CheckPrototypeDefinition.c.o
> /usr/bin/cc    -o CMakeFiles/cmTryCompileExec1154642954.dir/CheckPrototypeDefinition.c.o   -c /head/bits/std/base/libcriterion/Criterion-2.2.1/build/CMakeFiles/CMakeTmp/CheckPrototypeDefinition.c
> /head/bits/std/base/libcriterion/Criterion-2.2.1/build/CMakeFiles/CMakeTmp/CheckPrototypeDefinition.c: In function ‘checkSymbol’:
> /head/bits/std/base/libcriterion/Criterion-2.2.1/build/CMakeFiles/CMakeTmp/CheckPrototypeDefinition.c:10:26: error: ‘strtok_s’ undeclared (first use in this function)
>    cmakeRequireSymbol(0, &strtok_s);
>                           ^
> /head/bits/std/base/libcriterion/Criterion-2.2.1/build/CMakeFiles/CMakeTmp/CheckPrototypeDefinition.c:10:26: note: each undeclared identifier is reported only once for each function it appears in
> make[1]: *** [CMakeFiles/cmTryCompileExec1154642954.dir/CheckPrototypeDefinition.c.o] Error 1
> make[1]: Leaving directory `/data/head/bits/std/base/libcriterion/Criterion-2.2.1/build/CMakeFiles/CMakeTmp'
> make: *** [cmTryCompileExec1154642954/fast] Error 2
> 
> 
> #include <string.h>
> 
> 
> static void cmakeRequireSymbol(int dummy, ...) {
>   (void) dummy;
> }
> 
> static void checkSymbol(void) {
> #ifndef strtok_s
>   cmakeRequireSymbol(0, &strtok_s);
> #endif
> }
> 
> char *strtok_s(char *strToken, const char *strDelimit, char **context) {
>   return NULL;
> }
> 
> #ifdef __CLASSIC_C__
> int main() {
>   int ac;
>   char*av[];
> #else
> int main(int ac, char *av[]) {
> #endif
>   checkSymbol();
>   if (ac > 1000) {
>     return *av[0];
>   }
>   return 0;
> }
> 
> 

I guess the problem with strtok_s lies within the file src/compat/strtak.h and its use under Linux ?
Or some other place where the assumption is made that strtok_s is defined ?

```
#ifndef COMPAT_STRTOK_H_
# define COMPAT_STRTOK_H_

# include "config.h"

# ifdef VANILLA_WIN32
#  if HAVE_STRTOK_S
#   define strtok_r strtok_s
#  else
static CR_INLINE char *strtok_r(char *str, const char *delim, CR_UNUSED char **saveptr) {
  return strtok(str, delim);
}
#  endif

#  ifdef _MSC_VER
#   define strdup _strdup
#  endif
# endif

#endif /* !COMPAT_STRTOK_H_ */
```

**Comment by Snaipe** [comment]
It seems that the subdirectories inside `dependencies` are empty, maybe the `git submodule update --init` failed. Do you have git installed? How did you get your sources? I don't think that the default tarballs provided by github on release would really work as they are missing vital dependencies.

The second cmake "error" you are seeing just means that `strtok_s` doesn't exist under kubuntu (which is normal), so CMake will use strtok as a fallback for `strtok_r`.

**Comment by Snaipe** [comment]
Incidentally, this also raises the issue that, indeed, a proper tarball containing all dependencies should be uploaded on release.

**Comment by calvinundhobbestc** [comment]
You are right. I downloaded the source tarball (v2.2.1..tar.gz) from https://github.com/Snaipe/Criterion/releases
And I looked it up on my local copy. Yep. dependecies only has empty dirs except valgrind, where
one valgrind.h is stored in.

I would prefer to not install git but to depend on the tarball. 
Would it be possible to update the tarball ? 
Thanx. :-)

**Comment by Snaipe** [comment]
Can't upload it right now, but I'll do so in a few hours. If you *really* want to build it in the meantime, you may [download the tarballs](https://github.com/Snaipe/Criterion/tree/v2.2.1/dependencies) of each dependency and extract them in their own directories. It's not ideal, but should work for the moment.

**Comment by calvinundhobbestc** [comment]
That worked. Many thanks to your fast replies.
Have a nice weekend.

**Comment by Snaipe** [comment]
A [proper archive](https://github.com/Snaipe/Criterion/releases/download/v2.2.1/criterion-v2.2.1.tar.bz2) has been uploaded for 2.2.1. Sources archives such as this will now be deployed automatically by travis on each release.
