### ISSUE TITLE
Debugging a criterion test with GDB

### ISSUE THREAD

**Issue by Wiler** [Snaipe/Criterion#127]
Hi,

I can not find any information about how to debug a criterion test using GDB. When I try to use gdb, it is not capable of show me where the error is produced inside my code. The backtrace only shows me the call path inside criterion. I suppose that GDB needs an special configuration. Could you give me any information related to this?

Thanks

**Comment by Snaipe** [comment]
There are two main ways:

### Single mode

The simplest one is, if you know which test fails, to run your test with the `--single suite::test` command line option. For instance, debugging the `misc::failing` test in the `simple.c` sample:

```gdb
$ gdb -q ./samples/simple.c.bin
Reading symbols from ./samples/simple.c.bin...done.
(gdb) b misc_failing_impl 
Breakpoint 1 at 0x400cc9: file /home/snaipe/workspace/c/criterion/samples/simple.c, line 4.
(gdb) r --single misc::failing
Starting program: /home/snaipe/workspace/c/criterion/build/samples/simple.c.bin --single misc::failing
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Breakpoint 1, misc_failing_impl () at /home/snaipe/workspace/c/criterion/samples/simple.c:4
4	    cr_assert(0);
(gdb) q
```

### GDB Inferiors

A more complete/extensive method is to make use of some gdb options to juggle between what gdb calls "inferiors":

```
$ gdb -q ./samples/simple.c.bin
Reading symbols from ./samples/simple.c.bin...done.
(gdb) set follow-fork-mode child
(gdb) set detach-on-fork off
(gdb) set non-stop on
(gdb) set target-async on
(gdb) set schedule-multiple on
```

These options will make sure that the tests are still tracked by gdb without suspending the parent runner. All it left is to place some breakpoints and run the tests:

```
(gdb) b misc_failing_impl 
Breakpoint 1 at 0x400cc9: file /home/snaipe/workspace/c/criterion/samples/simple.c, line 4.
(gdb) r
Starting program: /home/snaipe/workspace/c/criterion/build/samples/simple.c.bin 

<snip>

Thread 2.1 "simple.c.bin" hit Breakpoint 1, misc_failing_impl () at /home/snaipe/workspace/c/criterion/samples/simple.c:4
4	    cr_assert(0);
[Thread 0x7ffff6c0e700 (LWP 7239) exited]
[Inferior 3 (process 7236) exited normally]
```

We can see that Thread 2.1 (i.e. Inferior 2, Thread 1) has hit our breakpoint -- all that is left it to switch to the Inferior 2 and debug accordingly.

```
(gdb) inferior 2
[Switching to inferior 2 [process 7234] (/home/snaipe/workspace/c/criterion/build/samples/simple.c.bin)]
[Switching to thread 2.1 (Thread 0x7ffff7fb1700 (LWP 7234))] 
#0  misc_failing_impl () at /home/snaipe/workspace/c/criterion/samples/simple.c:4
4	    cr_assert(0);
(gdb) q
```

**Comment by Snaipe** [comment]
As a side note -- perhaps this ought to have its own page in the documentation. I'll keep this open as a reminder.

**Comment by Snaipe** [comment]
Documentation regarding this with the new `--debug` flag has been added by fbbfcb6.
