### ISSUE TITLE
skip tests

### ISSUE THREAD

**Issue by fserra** [Snaipe/Criterion#131]
Hi

Would it be possible to have something like python's pytest `pytest.skip()` to skip a test at run time?

I am trying to test a software which has different capabilities depending on how it was compiled. So there are functions like `isFunctionalityXAvailable` and would like to write on some tests
```C
if( !isFunctionalityXAvaiable() )
{
    criterion_skip();
}
```
Thanks!

**Comment by Snaipe** [comment]
You can (kind of) already do that by setting up a hook that disables the specific test, but it's too painful to my liking. I guess this will be a workaround for the time being if you *really* need to disable the test, until `criterion_skip` gets implemented.

Thanks for the feedback!
