### ISSUE TITLE
Problems Visual Studio 2015

### ISSUE THREAD

**Issue by dcbrav** [Snaipe/Criterion#134]
When I start to work with Criterion, I have the next errors (Visual Studio 2015):

Error	LNK2019	unresolved external symbol __imp_cr_malloc referenced in function "void __cdecl criterion::`dynamic initializer for 'malloc''(void)" (??__Emalloc@criterion@@YAXXZ)

Error	LNK2019	unresolved external symbol __imp_cr_calloc referenced in function "void __cdecl criterion::`dynamic initializer for 'calloc''(void)" (??__Ecalloc@criterion@@YAXXZ)

Error	LNK2019	unresolved external symbol __imp_cr_realloc referenced in function "void __cdecl criterion::`dynamic initializer for 'realloc''(void)" (??__Erealloc@criterion@@YAXXZ)	

Error	LNK2019	unresolved external symbol __imp_cr_free referenced in function "void __cdecl criterion::`dynamic initializer for 'free''(void)" (??__Efree@criterion@@YAXXZ)	

Any solution? Thanks!

**Comment by Snaipe** [comment]
Thanks for the report. What compiler are you using, VC or VC++? Could you post the command-line commands that Visual Studio uses to build your project?

Additionally, what version of criterion are you using?

**Comment by am11** [comment]
I just successfully built latest bleeding branch with VS 2015 Update 3 (Community Edition) with the set of commands given below:

```powershell
# PowerShell

git clone https://github.com/Snaipe/Criterion -b bleeding --single-branch --recursive
cd Criterion

mkdir build
cd build

cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build . --config Release
```

no errors, just 32 warnings :)

Then `(dir .\Release).Name` resulted in:

```powershell
criterion.dll
criterion.exp
criterion.lib
```

**Comment by Snaipe** [comment]
As this wasn't updated, I'm going to close this. If you need help, consider asking on the [mailing list](mailto:criterion@freelists.org) rather than opening a ticket.
