### ISSUE TITLE
Linking issues/namespace pollution in core

### ISSUE THREAD

**Issue by MrAnno** [Snaipe/Criterion#141]
Hello,

I'm trying to integrate Criterion with a "bigger project", but unfortunately I'm having linking issues because of some namespace pollution in the core of Criterion.

For example, in the `stats` module, there are non-static functions such as `stats_init` and `stat_push_event`.

Is it a bad idea to append a specific Criterion-related prefix to all public symbols?

**Comment by Snaipe** [comment]
Yes, these are functions that were part of the 1.0 release and that are bound to be gone with the current rewrite work.

Prefixing will happen eventually, but in effect this is mostly a visibility bug. All symbols that are part of the core should have their visibility set to "hidden".

**Comment by Snaipe** [comment]
Fixed. For previous releases, you can achieve the same results when configuring with `CFLAGS=-fvisibility=hidden cmake ..`.

**Comment by MrAnno** [comment]
Wow, it was really fast. Thank you. :+1: :smile:
