### ISSUE TITLE
Debian package issue on Ubuntu Precise

### ISSUE THREAD

**Issue by lbudai** [Snaipe/Criterion#142]
Hi,

I've build Criterion Debian packages in my [OBS](https://build.opensuse.org/package/show/home:laszlo_budai:syslog-ng/criterion) repository.

We need to install Criterion in Travis which uses Precise.
All of the unit tests are passed, even those that contained only a failing testcase.
The reason was that on Precise the linker uses the as-needed flag by default and because of this some crucial parts was not part of the library.

I've fixed it on my environment, maybe you can fix it in another way
(my fix is really simple: in debian/rules I run cmake with `-DCMAKE_SHARED_LINKER_FLAGS='-Wl,--no-as-needed'` in the build target).

**Comment by Snaipe** [comment]
Interesting. This might be related to #91. Were your tests registered but all marked as passed, or were there no tests running at all?

**Comment by lbudai** [comment]
No tests running.

**Comment by Snaipe** [comment]
Could you please check if there is a `__start_cr_tst` symbol in the resulting test executable? I'm expecting it not to be there, but I want to be sure.

**Comment by Snaipe** [comment]
@lbudai now that #91 is fixed, could you check if you're still having the issue on `bleeding`?

**Comment by lbudai** [comment]
@Snaipe : sorry for the late answer. yeah, it solved the issue, thanks.
(I've just build the 2.3.0-rc1 in my OBS repo. )
