### ISSUE TITLE
"Providing your own main" undefined reference

### ISSUE THREAD

**Issue by MrAnno** [Snaipe/Criterion#145]
After introducing the `-fvisibility=hidden` CFLAG in 15b221ac, `criterion_initialize`, `criterion_run_all_tests` and `criterion_finalize` have become hidden as well.

These functions are required to run tests with a [custom `main()`](http://criterion.readthedocs.io/en/master/internal.html#example-main).

**Comment by Snaipe** [comment]
I took the time to audit which APIs were exported, and which weren't. Turns out that there were quite a few missing. Thanks for the report!

**Comment by Snaipe** [comment]
R

**Comment by MrAnno** [comment]
Thanks for the fix! :)
