### ISSUE TITLE
Extglob misbehaves on windows builds

### ISSUE THREAD

**Issue by Snaipe** [Snaipe/Criterion#147]
This is visible on the appveyor builds: https://ci.appveyor.com/project/Snaipe/criterion/build/2.2.2_b1443-features/boxfort-sandboxing/job/vh0ixf1wngmgg4pi#L880

@a1lu any insights on what might cause this?

**Comment by a1lu** [comment]
That looks like a problem with pattern including `*/` .
Is this a escape sequence on windows or the appveyor shell?

**Comment by Snaipe** [comment]
The pattern tests are still done with cram 0.7, which on appveyor explicitely uses the msys2 shell as per the configuration.

If this is indeed a wrong substitution in the shell, it should be visible on the pattern fed to the extglob -- I'll try printing that on my windows box.

**Comment by am11** [comment]
Might be the PowerShell is the issue here: https://github.com/Snaipe/Criterion/blob/eb70ea8/appveyor.yml#L83-L87

We can try to replace this block with batch+bash instead of ps+bash:

```yml
- |
  sh -c "ctest --output-on-failure --timeout 10"
  if errorlevel 1 (
     echo Failed with code %errorlevel%
     exit /b %errorlevel%
  )
```

**Comment by a1lu** [comment]
There is an similar problem with xterm and bash/zsh on patterns like including `!`. I have to escape this to work properly.

**Comment by Snaipe** [comment]
Okay this is actually pretty stupid.

msys2 is replacing patterns such as '*/passing' to '*C:/msys64/passing'.

I'm a bit speechless. There isn't much we can really do here, but according to [this](https://sourceforge.net/p/msys2/wiki/Porting/) we might get away by telling our users to `export MSYS2_ARG_CONV_EXCL="$MSYS2_ARG_CONV_EXCL;--pattern="`.

In the meantime I'm going to do just this for our test suite.
