### ISSUE TITLE
Theories are broken on windows

### ISSUE THREAD

**Issue by Snaipe** [Snaipe/Criterion#150]
Relevant build: https://ci.appveyor.com/project/Snaipe/criterion/build/2.2.2_b1453-bleeding/job/hotyn0yjptfso7ts#L903

**Comment by Snaipe** [comment]
After investigating some more, it appears that theories aren't broken per-se, but longjmp()'ing when a `cr_assert()` fails inside a theory causes a crash. It does not seem that this is caused by a corruption of the jmp_buf either, and a stack corruption is a bit unlikely.

Maybe the windows setjmp/longjmp implementation is garbage? If so, libunwind might be a good choice for these operations in the future.

**Comment by am11** [comment]
Seems like in C++ context, the [set/long]jmp is surely not supported https://msdn.microsoft.com/en-us/library/xe7acxfb.aspx#Anchor_3.
Separately, according to [CoreCLR source](https://github.com/dotnet/CoreCLR), .NET runtime -- while relying on HP/nongnu libunwind for Unices (which fallbacks to llvm libunwind if nongnu variant is not ported to platform) -- their JIT has custom implementation of stack unwinding for Windows; which in my understanding is built on top of APIs like [`RtlVirtualUnwind`](https://msdn.microsoft.com/en-us/library/ms680617.aspx) et al.

**Comment by Snaipe** [comment]
I've been investigating the matter a bit more, and we're in a bit of a pickle anyway: since we're using setjmp/longjmp, we're not properly handling C++ unwinding anyway.

So, what should we be doing here anyway?

We could throw an exception on the C++ side when an assert is hit, but this makes it possible for a user to actually catch that exception (and the catchall `catch(...)` statement doesn't help). Plus, this doesn't work for the C side.

We could use the [Itanium C++ ABI Spec](http://mentorembedded.github.io/cxx-abi/abi-eh.html) functions to unwind the stack for us, but this requires a hard dependency on the C++ runtime. Not that good, but the spec specifies the behavior of a complying (but hypothetic) `longjmp_unwind` function.

We can't call exit either since `abort`, `exit`, and `terminate` does not unwind the stack.

We could unwind the stack ourselves (with the help of libunwind), but I dread the day I'll have to do this manually.

Perhaps we shouldn't care about unwinding at this point, since on a failed assert, we could argue that the process is going to die anyway. In which case, we could just setup an `atexit` handler and go on our merry way.

Exiting would mean that theories would be fried -- we would have to reimplement them as individual processes. Maybe this could be a good excuse to finally implement that nested test tree structure 3.0 promises?

**Comment by Snaipe** [comment]
I have started writing [some support code](https://github.com/Snaipe/Criterion/tree/features/unwind) for manually unwinding the stack with the IA64 ABI. So far it's working pretty well on linux, but I don't think it's going to be possible to avoid being handled by catch-all statements (which is probably why not rethrowing after a `catch(...)` is evil). Theories are also failing on linux with that change, so it might suggest that perhaps the way theories uses their jumps is wrong.

It is also not clear if this will improve anything on the windows side.

**Comment by Snaipe** [comment]
Confirmed that the setjmp/longjmp implementation from msvcrt.dll is utter garbage. Using __builtin_setjmp/longjmp works as expected on MinGW.

I think the best course of action at this point is to rewrite the function for x86/x86-64/arm targets.

I also don't think that unwinding the stack is a good idea for the moment. We'll leave that as a post 2.3.0 concern.

**Comment by am11** [comment]
> I think the best course of action at this point is to rewrite the function for msvc x86/x86-64/arm targets in BoxFort.

Great! I found a similar discussion about setjmp that why it works in MINGW and not on MSVC here http://stackoverflow.com/q/8628067/863980, but this is pre-C99-support post. Some are showing C99 std specs and some are encouraging `CreateFiber` stuff. Might be some information there is relevant to this scenario. :)

**Comment by Snaipe** [comment]
[That was it](https://ci.appveyor.com/project/Snaipe/criterion/build/2.3.0-rc2_b1589-fix/150).

It seems that setjmp/longjmp in the windows CRT actually unwinds. This is in our case horrible since this piece of code is trying to unwind past the BoxFort main, which cannot possibly handle this.

Sometimes dumb functions should be left alone.

In any case, the mitigation here is simple: use setjmp/longjmp for the rest of the world, and for windows either use __builtin_setjmp/longjmp if available, or implement it ourselves otherwise.
