### ISSUE TITLE
Build error on FreeBSD

### ISSUE THREAD

**Issue by a1lu** [Snaipe/Criterion#156]
On FreeBSD bleeding does'nt build.
in src/compat/section.h:35 :

```
type specifier missing, defaults to 'int'
const ELFW(Ehdr) * map;
~~~~

'const' type qualifier on return type has no effect
const ELFW(Ehdr) * map;
~~~~
error: a parameter list without types is only allowed in a function definition
const ELFW(Ehdr) * map;
            ^
error: expected ';' at end of declaration list
const ELFW(Ehdr) * map;
                ^

```

**Comment by Snaipe** [comment]
Not sure why ELFW was used here instead of ElfW. Will fix.

**Comment by Snaipe** [comment]
Actually, nevermind, where does the `ELFW` come from? The current source uses `ElfW`.918af49

**Comment by a1lu** [comment]
Yes ElfW is used. ELFW was a typo, sorry.

**Comment by Snaipe** [comment]
Okay, I remember now that FreeBSD does not define ElfW. I have a similar fix on [mimick](https://github.com/Snaipe/Mimick/blob/master/src/plt-elf.h#L29).

**Comment by a1lu** [comment]
This is also included in boxfort
