### ISSUE TITLE
[ERR] Corrupted event IO in the worker pipe

### ISSUE THREAD

**Issue by Wiler** [Snaipe/Criterion#162]
Hello

Could you provide me some information about this kind of error? How can it be produce or when?

Thanks,

**Comment by Snaipe** [comment]
What version of criterion is this happening, and on what platform?

Also, do you have a test case that triggers the condition?

**Comment by Snaipe** [comment]
I haven't encountered this issue since 2.3.0-rc1, so I'm going to assume that it got fixed.
