### ISSUE TITLE
problem with --crash

### ISSUE THREAD

**Issue by fserra** [Snaipe/Criterion#164]
Hi  
I am running the following example:
```C
  Test(simple, test_crash)
  {
     int a = 2;
     cr_assert(a == 1); 
  }
```
With the latest commit a9df791, running the test in gdb with `set follow-fork-mode child`, produces gdb to stop several times, with or without `--crash`:
```
Thread 2.1 "test" received signal SIGSTOP, Stopped (signal).
Thread 2.1 "test" received signal SIGSTOP, Stopped (signal).
Thread 2.1 "test" received signal SIGCONT, Continued.
Thread 2.1 "test" received signal SIGSTOP, Stopped (signal).
Thread 2.1 "test" received signal SIGSTOP, Stopped (signal).
Thread 2.1 "test" received signal SIGCONT, Continued.
```
None of these stops is the actual assert.  

In 5ff8ef9 and 25d444b it works fine: gdb stops a single time which corresponds to the failing assert (with `--crash`)  
Any ideas what is going on?  
Thanks!

**Comment by Snaipe** [comment]
Don't run gdb on the runner itself unless you're prepared to setup a lot of options to make multi-process debugging work. Instead, the new release candidate introduces `--debug` to spawn a gdbserver running your test.

More details can be found on the [bleeding docs](http://criterion.readthedocs.io/en/latest/debug.html)

**Comment by Snaipe** [comment]
(Also note that `--debug` implies `--crash -j1`, and is composable with `--filter` to run specific tests)

**Comment by fserra** [comment]
Sorry for the ignorance, but I can't seem to get it to work.  
So I followed the instructions, the test is run, but then I don't get control at the assert.
I did `./test --debug` and in another terminal 
```
gdb -q ./test
target remote localhost:1234
continue
```
and then its done..  
How do you get this working??  
Thanks!

**Comment by Snaipe** [comment]
It might be a bug then. Can you break into your function and debug properly otherwise?

**Comment by fserra** [comment]
yes, I can break

**Comment by Snaipe** [comment]
It's a bug! it seems that `--crash` is broken right now because `criterion_options` isn't inherited in the child process, so the trap always gets skipped.

**Comment by Snaipe** [comment]
This should now work properly.

**Comment by fserra** [comment]
it does. thanks a lot
