### ISSUE TITLE
Rewrite the assertion API

### ISSUE THREAD

**Issue by Snaipe** [Snaipe/Criterion#165]
The assertion API is a bit clunky as it is. I think that the design of that part of the API needs to change for the better for 3.0, as we've learned quite some things in the past two years.

My biggest gripe with the current design is that it's at the same time too inconsistent and too shallow to be useful for both the user and the runtime (it makes printing actual/expected diffs hard).

I have three proposals for a redesign in mind:
## Proposal 1: use long names and per-type functions:

``` c
Test(assert, full)
{
    /* cr_assert(Cond, [msg, ...]) */
    cr_assert(1);
    cr_assert(1, "Hello %s", "World!");

    /* cr_assert_<cmp>_<type>(A, B, [msg, ...])
     *
     * comparators: eq, ne, lt, le, gt, ge
     * types: i8, i16, i32, i64, u8, u16, u32, u64,
     *        str, wcs, tcs (windows-specific TCHAR)
     *        uchar, schar, uint, sint, ulong, slong,
     *        ullong, sllong, flt, dbl, ldbl, bool
     */
    cr_assert_eq_i8(1, 1);

    /* "cr_assert_<cmp>" will simply use the relevant operator and
     * an appropriate stringification for compilers supporting it. */
    cr_assert_eq(1, 1);

    /* the "mem" type requires an additional size parameter:
     * cr_assert_<cmp>_mem(A, B, Size, [msg, ...])
     */
    cr_assert_eq_mem(&(int){ 1 }, &(int){ 1 }, sizeof (int));

    /* cr_assert_<cmp>_cmp(&A, &B, Cmp, [msg, ...])
     * Must take pointers, and uses a user-provided comparator.
     *
     * Unnecessary on C++ compilers where operator== is used.
     */
    cr_assert_eq_cmp(&(int){ 1 }, &(int){ 1 }, int_cmp);

    /* pointer checks */
    cr_assert_null(NULL);
    cr_assert_notnull(0x1);

    /* C++ exceptions */
    cr_assert_throw({ throw std::exception("test") });
    cr_assert_nothrow({});
    cr_assert_anythrow({ throw std::exception("test") });
}
```

This one is the least risky: we basically take the current API, add some type-specific macros, and make the naming and usage conventions consistent. Nothing too far-fetched, and quite consistent with the C philosophy.
## Proposal 2: cleaner syntax w/ assertion sub-expressions:

``` c
Test(assert, nested)
{
    /* cr_assert(Cond, [msg, ...]) */
    cr_assert(1);
    cr_assert(1, "Hello %s", "World!");

    /* negation */
    cr_assert(not(0));

    /* comparison
     *
     * cr_assert(<cmp>(A, B, <type_tag>), [msg, ...]) 
     *
     * comparators: eq, ne, lt, le, gt, ge
     * types tags: i8, i16, i32, i64, u8, u16, u32, u64,
     *        str, wcs, tcs (windows-specific TCHAR), mem
     *        uchar, schar, uint, sint, ulong, slong,
     *        ullong, sllong, flt, dbl, ldbl, bool
     */
    cr_assert(eq(1, 1, i8));

    /* mem uses the struct cr_mem type */
    struct cr_mem a = { &(int){ 1 }, sizeof (int) };
    struct cr_mem b = { &(int){ 1 }, sizeof (int) };
    cr_assert(eq(a, b, mem));

    /* mem<cmp>(arr1, arr2, size) is a syntactic sugar for arrays
     * that have the same size */
    cr_assert(memeq(&(int){ 1 }, &(int){ 1 }, sizeof (int)));

    /* on supported compilers, the type tag can be dropped entirely */
    cr_assert(eq(1, 1));

    /* on C compilers, using a custom type tag allows the usage of
     * custom comparators and stringification functions.
     *
     * on C++ compilers, this is unnecessary as operator== and operator<<
     * are used.
     */
    cr_assert(eq(1, 1, my_type_id));

    /* composition */
    cr_assert(or(1, 0)) /* expr1 || expr2 */
    cr_assert(and(1, 1)) /* expr1 && expr2 */
    cr_assert(any(0, 0, 1, 0)); /* at least one expr must be true */
    cr_assert(none(0, 0, 0, 0)); /* all exprs must be false */
    cr_assert(all(1, 1, 1, 1)); /* all exprs must be true */

    cr_assert(or(and(eq(1, 1), eq(2, 2)), eq(1, 2)));

    /* pointer checks */
    cr_assert(null(NULL));

    /* C++ exceptions */
    cr_assert(throw({ throw std::exception("test"); }));
    cr_assert(nothrow({}));
    cr_assert(anythrow({ throw std::exception("test"); }));
}
```

I like this one quite a lot. Here, we only need to define two macros, cr_assert and cr_expect, fitted with some token recognition for eq, ne, ... and the rest.

The usage of type tags makes it possible for us to define easily comparision functions and stringification functions that would make possible generic value diffing as described in #105, and best of all would allow users to implement for instance `cr_user_<tag>_cmp` and `cr_user_<tag>_tostr` that would be then picked up as possible comparison and stringification functions for their cursom type tag.

It is, however, quite unclear if this design is at all possible and will require some experimentation, but my experience with mimick tells me that this should definitely be implementable.
## Proposal 3: object-oriented-like composition:

``` c
Test(assert, compound)
{
    cr_assert().istrue(1).done();
    cr_assert().istrue(1).msg("Hello %s", "World!").done();

    /* negation */
    cr_assert().not().istrue(1).done();
    cr_assert().isfalse(0).done(); /* equivalent */

    /* comparison (needs pointers & comparator + stringification functions) */
    cr_assert().eq(&(int){ 1 }, &(int){ 1 }, cr_sint).done();

    /* mem uses the struct cr_mem type */
    struct cr_mem a = { &(int){ 1 }, sizeof (int) };
    struct cr_mem b = { &(int){ 1 }, sizeof (int) };
    cr_assert().eq(a, b, cr_mem).done();

    /* user types needs comparator and stringification function */
    struct cr_user_type my_type = { .cmp = my_cmp, .str = my_str };
    cr_assert().eq(A, B, my_type).done();

    /* compound expressions */
    cr_assert()
        .eq(A, B, my_type).or()
        .lt(A, B, my_type).and()
        .gt(A, B, my_type)
        .done();

    /* pointer checks */
    cr_assert().null(NULL).done();

}
```

This one is more for posterity, as one of the "should be possible" designs, but while the compound expressions and chaining coupled with the external `.msg()` are nice, I have a few problems with the trailing `.done()` and the lack of automatic type handling (you always have to provide a comparator here).

The idea of chaining a `.msg` could still be interesting but would require deep changes in the protocol.

**Comment by am11** [comment]
+1 for proposal 3.

Would be nice if `.true` and `.false` are preferred over `.istrue` and `.isfalse` respectively.

Also, slightly better semantics and if possible, `done()` should have a once-per-test constraint ([source of inspiration](https://github.com/mochajs/mocha/blob/9e7f5f207a9905d3243d33a22c81d3b0c960ccda/test/browser/multiple-done.spec.js)).

**Comment by Snaipe** [comment]
The problem with true and false is that they are mandated by the standard to be macros that expand to 1 and 0 respectively, so we can't use them as tokens.

As for done(), the call is necessary to actually send the assert protocol message. I could make it so that the next call to cr_assert implicitely calls done() for the previous assert, but this causes issues for code in-between, and more so if it happens to crash.

All in all \#3 is nice but a real hassle to implement soundly, though it's still worth a shot.

**Comment by a1lu** [comment]
I like the second one. It has a clean syntax. The third looks a bit strange to me.

**Comment by am11** [comment]
Thanks for the explanation! :)

> I could make it so that the next call to cr_assert implicitely calls done() for the previous assert, but this causes issues for code in-between, and more so if it happens to crash.

Would it make sense to enqueue all the assert calls; and on `done()` dequeue, execute and dispatch the message?

> I like the second one. It has a clean syntax.

Reasonable. On this note, can we:

* support all three styles?
  * Proposal 1: elaborated
  * Proposal 2: nested
  * Proposal 3: chained
* separate out the assertion mechanics as external repo(s), in order to make criterion pluggable for these three and even future assertion lib choices?

**Comment by Snaipe** [comment]
> Would it make sense to enqueue all the assert calls; and on done() dequeue, execute and dispatch the message?

Perhaps. I'm not too keen on the style itself, but I could imagine it being done.

My main gripe with this is that embracing fully the third proposal would mean that either we make `done()` mandatory on each call, even the "non-chained" ones, which is horrible, *or* we make it optional and dequeue when we really want that, which moves the responsibility of carefully think about where and when you should call it to the user, which is admitedly also a horrible decision.

The syntax should be designed to allow the user to easily write tests while minimizing the number of questions they need to ask themselves while developing, and currently either decision doesn't fit the bill.

If I were to consider a assertion-chaining API, I would probably make it as a C++ extension to the main API, or a dedicated function, which brings me to the next point:

> Reasonable. On this note, can we:
>
> * support all three styles?
>   * Proposal 1: elaborated
>   * Proposal 2: nested
>   * Proposal 3: chained
> * separate out the assertion mechanics as external repo(s), in order to make criterion pluggable for these three and even future assertion lib choices?

Supporting all three styles is very unlikely, because of maintainance -- the assertion API (does and will) heavily make use of preprocessing tricks and is hard to maintain as it is. Doing so on three separate APIs would probably eat everyone's sanity, mine first.

What could be interesting would be to see if proposal 2 works as a main API, and consider integrating the chaining semantics of the 3rd proposal through a C++-only extension (which does not have the problem of done() since we can just do that in the destructor of the temporary assert objects, much like google test already does), or fully embrace calling `done()` every time as part of a new `cr_assert_that()` function:

```c
cr_assert(1, "whatever"); // normal assert

cr_assert_that()
    .eq(1, 1, i8).and()
    .ne(2ul, 2ul, ulong)
    .msg("some message")
    .check(); // 'check' seems more appropriate than 'done'
```

**Comment by kugel-** [comment]
I like #2 best because of possible composition.

Is it planned that the new API can output nicer messages (e.g. the actual values instead variable names) automatically?

**Comment by Snaipe** [comment]
Yes, this is planned and actually outputing the actual values of the relevant parameters ocer on #182.

Diffing the parameters on equality tests (e.g. for strings or byte arrays) is also planned.
