### ISSUE TITLE
Exit with nonzero status when encountering a warning or error

### ISSUE THREAD

**Issue by Snaipe** [Snaipe/Criterion#169]
As discussed on gitter, Criterion should exit with a nonzero status when a warning is raised (for instance when a test crashes in its teardown). Warnings should not mark a test as failed, but they shouldn't be ignored either, and exiting with 0 when something is probably wrong is bad behaviour.

In addition to that we would also include a `--ignore-warnings` to restore the original behaviour.

**Comment by kugel-** [comment]
In my jenkins (CI) workflow, it would mean that steps after the unit test wouldn't be executed. This is not always wanted, so yes, a flag to restore the current behavior is needed. If that's there I don't have a problem with the change.

**Comment by Snaipe** [comment]
Fixed by 99a2c7ec7261ea1c343f968dc9af657b48e90c2b.
