### ISSUE TITLE
cr_log: deadlock in multi-threaded tests

### ISSUE THREAD

**Issue by stv0g** [Snaipe/Criterion#170]
The nanomsg / protobuf-based logging code seems to be buggy.
I ran the following code in a Fedara 23 Docker container:

Error:
```
[ERR ] Could not read ack: Operation cannot be performed in this state.
[ERR ] Could not read ack: Operation cannot be performed in this state.
[----] tests/log.c:15: Unexpected signal caught below this line!
[FAIL] logging::simple: CRASH!
[====] Synthesis: Tested: 1 | Passing: 0 | Failing: 1 | Crashing: 1
```

Minimal example:
```
#include <criterion/criterion.h>
#include <criterion/logging.h>

#include <pthread.h>

void * thread(void *ctx)
{
	for (int i = 0; i < 1000; i++)
		cr_log_info("loop %u", i);
	
	return NULL;
}


Test(logging, simple) {
	pthread_t thrds[10];
	
	for (int i = 0; i < 10; i++)
		pthread_create(&thrds[i], NULL, thread, NULL);

	for (int i = 0; i < 10; i++)
		pthread_join(thrds[i], NULL);	
}
```

**Comment by Snaipe** [comment]
Criterion isn't changing any global state in these functions, so perhaps we're having something like a data race in nanopb/nanomsg?

The logs for this issue are very similar to the ones I got in #118. Now that I think about it, they might be related, as on windows child processes are collected in parallel threads calling `cr_send_to_runner`.

I recall the nanomsg maintainer saying that accesses to the internal REQ/REP hash table were not synchronized. I'll see if I can find where this is coming from on the nanomsg side.

In the meantime I'm just going to put a global mutex around my calls to `nn_send` as a workaround.

**Comment by Snaipe** [comment]
So it turns out that it was the exact same issue as #118. This kills two birds with once stone, and parallel jobs are back on windows!

Thank you for reporting this issue.
