### ISSUE TITLE
It doesn't tell me what line the crash happened on

### ISSUE THREAD

**Issue by dabowheel** [Snaipe/Criterion#173]
When I get a SIGSEGV crash I get a error message that only tells me what test the crash was in.

[----] main.c:158: Unexpected signal caught below this line!

When I do remote debugging the debugger doesn't stop where the crash happened.

How do I know which line/function caused the crash? Is there a way to turn off signal catching?

GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) target remote localhost:1234
Remote debugging using localhost:1234
Reading /home/miguel/workspace/aqua/test/main from remote target...
warning: File transfers from remote targets can be slow. Use "set sysroot" to access files locally instead.
Reading /home/miguel/workspace/aqua/test/main from remote target...
Reading symbols from target:/home/miguel/workspace/aqua/test/main...done.
Reading /lib64/ld-linux-x86-64.so.2 from remote target...
Reading /lib64/ld-linux-x86-64.so.2 from remote target...
Reading symbols from target:/lib64/ld-linux-x86-64.so.2...Reading /lib64/ld-2.23.so from remote target...
Reading /lib64/.debug/ld-2.23.so from remote target...
(no debugging symbols found)...done.
0x00007ffff7dd7cc0 in ?? () from target:/lib64/ld-linux-x86-64.so.2
(gdb) c
Continuing.
Reading /usr/local/lib/libcriterion.so.3 from remote target...
Reading /usr/local/lib/libaqua.so.0.1 from remote target...
Reading /lib/x86_64-linux-gnu/libc.so.6 from remote target...
Reading /lib/x86_64-linux-gnu/libpthread.so.0 from remote target...
Reading /lib/x86_64-linux-gnu/librt.so.1 from remote target...
Reading /lib/x86_64-linux-gnu/libanl.so.1 from remote target...
Reading /lib/x86_64-linux-gnu/libc-2.23.so from remote target...
Reading /lib/x86_64-linux-gnu/.debug/libc-2.23.so from remote target...
Reading /lib/x86_64-linux-gnu/librt-2.23.so from remote target...
Reading /lib/x86_64-linux-gnu/.debug/librt-2.23.so from remote target...
Reading /lib/x86_64-linux-gnu/libanl-2.23.so from remote target...
Reading /lib/x86_64-linux-gnu/.debug/libanl-2.23.so from remote target...
[New Thread 706.761]

Thread 1 "main" received signal SIGSEGV, Segmentation fault.
__strcmp_sse2_unaligned ()
    at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
31	../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S: No such file or directory.
(gdb) print name
$1 = '\000' <repeats 32 times>
(gdb) print place
No symbol "place" in current context.
(gdb) s

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
PC register is not available
(gdb) s
The program is not being run.
(gdb) q
PC register is not available

**Comment by Snaipe** [comment]
> [----] main.c:158: Unexpected signal caught below this line!

This message tells you that the crash happenned after line 158 -- for the moment criterion can't really produce a backtrace of where the segfault is happening (because that would require an analysis of the relevant core dump, which is horrid). With the new sandbox implementation, criterion could additionally print the function & line/address where the crash happenned, but it wouldn't really give any info on which line the crash happenned *in the test*.

> When I do remote debugging the debugger doesn't stop where the crash happened.
> ...
> Thread 1 "main" received signal SIGSEGV, Segmentation fault.
> __strcmp_sse2_unaligned ()
> at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
> 31 ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S: No such file or directory.

It seems that it stopped exactly where the crash happened? You has a segfault on a call to strcmp, just go back a few stack frames with the `up` gdb command.
