### ISSUE TITLE
Cannot build 2.3.0-rc1

### ISSUE THREAD

**Issue by davemaleni** [Snaipe/Criterion#175]
I downloaded 2.3.0-rc1 release from https://github.com/Snaipe/Criterion/releases
Unpacked, created build directory and from there typed "cmake .."

That gave errors like this:

-- Updating submodules to their latest/fixed versions
-- (this can take a while, please be patient)
fatal: Not a git repository (or any parent up to mount point /home/dave)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Error at /usr/share/cmake-3.5/Modules/ExternalProject.cmake:1915 (message):
  No download info given for 'csptr' and its source directory:

   /home/dave/work/Criterion-2.3.0-rc1/dependencies/libcsptr

  is not an existing non-empty directory.  Please specify one of:

   * SOURCE_DIR with an existing non-empty directory
   * URL
   * GIT_REPOSITORY
   * HG_REPOSITORY
   * CVS_REPOSITORY and CVS_MODULE
   * SVN_REVISION
   * DOWNLOAD_COMMAND
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/ExternalProject.cmake:2459 (_ep_add_download_command)
  .cmake/Modules/Subprojects.cmake:74 (externalproject_add)
  CMakeLists.txt:34 (cr_add_subproject)

I got the same kind of error for csptr, dyncall_s, nanomsg and boxfort.
Then I modified CMakeLists.txt to include git repositories, like this:

cr_add_subproject (csptr PATH dependencies/libcsptr
    GIT https://github.com/Snaipe/libcsptr.git
    OPTS
    ...

I'm not sure if that's the correct option nor which branch it would pull from git.

That got rid of the errors for the 4 subprojects, but the next "cmake .." run produces:

-- Updating submodules to their latest/fixed versions
-- (this can take a while, please be patient)
fatal: Not a git repository (or any parent up to mount point /home/dave)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- Configuring done
CMake Error at .cmake/Modules/PackageUtils.cmake:41 (add_library):
  Cannot find source file:

    dependencies/nanopb/pb_common.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  CMakeLists.txt:105 (cr_add_library)

CMake Error: CMake can not determine linker language for target: criterion
CMake Error: Cannot determine link language for target "criterion".

I don't know where nanopb can be found. Also not sure about the remaining subprojects in the
dependencies directory.

So how am I supposed to build the code?

I'm on Ubuntu 16.04.1, cmake version 3.5.1.

**Comment by Snaipe** [comment]
The release tarball automatically created by github are broken because they don't include submodules. You must clone the repository for it to work, although I understand that this might be impractical.

I'm going to include a source tarball in the release with all dependencies included.

**Comment by Snaipe** [comment]
It turns out that the deployment of releases was broken. The process is now fixed, and with the new 2.3.0-rc2 release, a [source archive](https://github.com/Snaipe/Criterion/releases/download/v2.3.0-rc2/criterion-v2.3.0-rc2.tar.bz2) is available.
