### ISSUE TITLE
Unable to start --debug

### ISSUE THREAD

**Issue by abc-mikey** [Snaipe/Criterion#179]
I may be missing something here but I get the following when trying to start a Criterion unit test in `--debug` to use with `gdb`.

```
$ ./unit_test --debug
[----] Criterion v2.3.0-rc2
[====] Running 2 tests from string_btree:
criterion: Could not spawn test instance: No such file or directory
Aborted (core dumped)
```

**Comment by Snaipe** [comment]
What did you compile your tests with? Currently compiling with `clang` assumes that `lldb-server` is present on your system (same thing with `gcc` and `gdbserver`).

If you did compile with clang and want to use `gdbserver`, use `--debug=gdb`.

**Comment by abc-mikey** [comment]
Ah. Compiling with `gcc` but it appears that I didn't have `gdbserver` installed. I now get:

```
$ ./unit_test --debug
[----] Criterion v2.3.0-rc2
[====] Running 2 tests from string_btree:
Process /home/michael/src/projects/MetaConfig/unit_test created; pid = 10688
Listening on port 1234
```

**Comment by abc-mikey** [comment]
Appears to work now as per [Debugging docs](../blob/bleeding/doc/debug.rst).
