### ISSUE TITLE
PPA can't be added via add-apt-repository

### ISSUE THREAD

**Issue by skytreader** [Snaipe/Criterion#189]
I hope this is the place to report issues like this.

```
$ sudo add-apt-repository ppa:snaipewastaken/ppa
Cannot add PPA: 'ppa:~snaipewastaken/ubuntu/ppa'.
ERROR: '~snaipewastaken' user or team does not exist.
```

However, I was eventually able to install criterion by manually adding the PPA to my `sources.list`. With one minor hiccup:

```
$ sudo apt-get install criterion-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  criterion
The following NEW packages will be installed:
  criterion criterion-dev
0 upgraded, 2 newly installed, 0 to remove and 252 not upgraded.
Need to get 193 kB of archives.
After this operation, 816 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
WARNING: The following packages cannot be authenticated!
  criterion criterion-dev
Install these packages without verification? [y/N] y
```

This is on Ubuntu 16.04.

**Comment by Snaipe** [comment]
Are you behind a proxy server? I cannot reproduce the error on my end, and this particular message seems to come up with problems related to proxy environment variables not being defined.

Are you able to add any other ppa from launchpad.com?

Manually adding the ppa to your sources.list works, but you'll probably want to add my [public key](http://keyserver.ubuntu.com:11371/pks/lookup?fingerprint=on&op=index&search=0x75B021D964AD869324CDB74DDDD7BCCD44BB9A9D) to your apt keychain with the `apt-key` command.

**Comment by skytreader** [comment]
I'm certain I'm not behind a proxy server. I've been able to add other PPAs from Launchpad on the same machine and on the same connection before but, just right now, I do not have any need to add a new one (so I can't test if this might be a local problem that cropped up recently).

I have another 16.04 machine I can try this on though. I'm also looking to use Criterion with Travis CI. Will give more details as I get to test them.

**Comment by skytreader** [comment]
Tried adding the PPA on one more physical 16.04 machine (succeeded) and a few 16.04 VMs (hit and miss) on a connection far more reliable than what I had when I created this issue (and guaranteed to be not behind a proxy too). Guess this issue is more about our local internet infrastructure and unlikely to be solved by any GitHub contributor. Closing.
