### ISSUE TITLE
Documentation refers to {assert, expect}_null, but it doesn't seem to be defined. 

### ISSUE THREAD

**Issue by bturrubiates** [Snaipe/Criterion#19]
Assertion macro in questions is referred to here: 
http://criterion.readthedocs.org/en/latest/starter.html#asserting-things

But upon building:
```
warning: implicit declaration of function ‘expect_null’
```

**Comment by Snaipe** [comment]
null assertions are available since 1.2.0, what version are you currently using ?

**Comment by bturrubiates** [comment]
Oh, that would be why. I'm on the 1.1.0 tag. Thanks.
