### ISSUE TITLE
Failure to build tests against debian package

### ISSUE THREAD

**Issue by kugel-** [Snaipe/Criterion#190]
I'm attempting to use criterion 2.3.1 through the provided debian packages, but things fail:

```
$ pkg-config --cflags criterion

$ pkg-config --libs criterion
-lcriterion 

$ gcc $(pkg-config --cflags criterion) simple.c $(pkg-config --libs criterion)
/tmp/ccuhiPDp.o: In function `misc_failing_impl':
simple.c:(.text+0x183): undefined reference to `criterion_send_event'
/tmp/ccuhiPDp.o: In function `misc_passing_impl':
simple.c:(.text+0x328): undefined reference to `criterion_send_event'
collect2: error: ld returned 1 exit status
```

Do you have an idea?

**Comment by kugel-** [comment]
When compiling 2.3.1 myself I don't experience this problem.

**Comment by Snaipe** [comment]
I can't seem to be able to reproduce this. What version/architecture of debian are you using?

**Comment by Snaipe** [comment]
It's a bit weird because `criterion_send_event` isn't used at all by the internals -- you might have somehow have header files outdated compared to libcriterion.so?

**Comment by kugel-** [comment]
I cannot reproduce it on a clean system. I think it was caused by a stale libcriterion.so /usr/local/lib
