### ISSUE TITLE
Support for callgrind (or clarification of it)

### ISSUE THREAD

**Issue by tsieprawski** [Snaipe/Criterion#192]
I write a C library and I'd like to profile its code. Normally to profile the code I'd run `valgrind --tool=callgrind` against the program. I have test suite that builds with criterion to a program, so it sounds reasonable and easy.

I've found out that right now criterion supports being run in valgrind's memcheck, as in you can see memory leaks and their traces. But valgrind's callgrind looks like not being supported, as in you see very different results for a code run with criterion (mostly actual call hits from criterion and dependencies, not the actual test code) and without.

See snippet repo in [1]. There is `lenghty.c` that is loaded both by `main.c` and `test.c` (which links to `criterion`). `build.sh` (or `build_docker.sh` if you want reliable results) will build them all, run in callgrind and `grep random` callgrind's output. For `main.c` there are ~3 method hits, for `test.c` there is only a `nn_random` and none of the relevant hits.

I suspect that because criterion runs everything in subprocesses/`forks()`/`toolong;didnotinvestigate`, then callgrind does not catch method hits because it does not look into them?

Example for `main.c`.
```
$ callgrind_annotate  main.out
--------------------------------------------------------------------------------
Profile data file 'main.out' (creator: callgrind-3.12.0)
--------------------------------------------------------------------------------

blah blah blah

--------------------------------------------------------------------------------
         Ir  file:function
--------------------------------------------------------------------------------
231,420,186  ???:lengthy [/home/tomasz/criterion-cannot-callgrind/main]
185,480,024  /build/glibc-bDJTDn/glibc-2.24/stdlib/random_r.c:random_r [/lib/x86_64-linux-gnu/libc-2.24.so]
121,420,783  /build/glibc-bDJTDn/glibc-2.24/stdlib/random.c:random [/lib/x86_64-linux-gnu/libc-2.24.so]
 28,569,596  /build/glibc-bDJTDn/glibc-2.24/stdlib/rand.c:rand [/lib/x86_64-linux-gnu/libc-2.24.so]
```

Example for `test.c`.

```
$ callgrind_annotate test.out                                             
--------------------------------------------------------------------------------                                                      
Profile data file 'test.out' (creator: callgrind-3.12.0)                                                                              
--------------------------------------------------------------------------------                                               

blah blah blah

------------------------------------
    Ir  file:function
--------------------------------------------------------------------------------
98,700  ???:get_section_data [/usr/lib/libcriterion.so.3.1.0]
86,670  /build/glibc-bDJTDn/glibc-2.24/elf/dl-lookup.c:do_lookup_x [/lib/x86_64-linux-gnu/ld-2.24.so]
79,142  /build/glibc-bDJTDn/glibc-2.24/string/../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:__strcmp_sse2_unaligned [/lib/x86_64
-linux-gnu/libc-2.24.so]
59,075  /build/glibc-bDJTDn/glibc-2.24/malloc/malloc.c:_int_malloc [/lib/x86_64-linux-gnu/libc-2.24.so]
56,813  /build/glibc-bDJTDn/glibc-2.24/string/../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:__memset_avx2_erms [/lib/x86_64-
linux-gnu/libc-2.24.so]
56,642  /build/glibc-bDJTDn/glibc-2.24/string/../sysdeps/x86_64/multiarch/../strcmp.S:strcmp [/lib/x86_64-linux-gnu/ld-2.24.so]
56,567  /build/glibc-bDJTDn/glibc-2.24/elf/dl-addr.c:_dl_addr [/lib/x86_64-linux-gnu/libc-2.24.so]
56,495  /build/glibc-bDJTDn/glibc-2.24/string/../sysdeps/x86_64/multiarch/../strcmp.S:__GI_strcmp [/lib/x86_64-linux-gnu/libc-2.24.so]
52,663  /build/glibc-bDJTDn/glibc-2.24/intl/../intl/l10nflist.c:_nl_make_l10nflist'2 [/lib/x86_64-linux-gnu/libc-2.24.so]
49,720  /build/glibc-bDJTDn/glibc-2.24/elf/dl-lookup.c:_dl_lookup_symbol_x [/lib/x86_64-linux-gnu/ld-2.24.so]
35,742  /build/glibc-bDJTDn/glibc-2.24/string/../sysdeps/x86_64/strlen.S:strlen [/lib/x86_64-linux-gnu/libc-2.24.so]
28,542  /build/glibc-bDJTDn/glibc-2.24/elf/../sysdeps/x86_64/dl-machine.h:_dl_relocate_object
24,168  /build/glibc-bDJTDn/glibc-2.24/malloc/malloc.c:malloc [/lib/x86_64-linux-gnu/libc-2.24.so]
23,888  ???:pb_field_iter_next [/usr/lib/libcriterion.so.3.1.0]
```

[1] https://bitbucket.org/snippets/tsieprawski/zex5G

**Comment by Snaipe** [comment]
Callgrind should be working out of the box, but you need to pass `--trace-children=yes` to valgrind. Callgrind will then generate a separate file per process/test.

If you're using `--callgrind-out-file` to change the name of the output file, be sure to include a `%p` (which will get substitued by the pid) so that the same file doesn't get overwritten over and over by the tests.

**Comment by tsieprawski** [comment]
Right, my `--callgrind-out-file` did not specify `%p` so I did not get the file from children. When I added it, the child-out file got the expected profile data.

Still IMO it would be worth noting in documentation - that when callgrinding criterion to expect >=1 out file per process (parent+children).

Besides that, this issue can be closed.

Thanks a lot!

**Comment by Snaipe** [comment]
Right, this is information that I could see go in a section of http://criterion.readthedocs.io/en/master/debug.html

Will keep this issue around to remind me to do that once I get a bit more time.
