### ISSUE TITLE
cr_assert memory usage

### ISSUE THREAD

**Issue by cybojanek** [Snaipe/Criterion#197]
Hi,

I use a lot of cr_assert statements in one of my tests (its a loop), and along with all my other tests in the suite, memory usage keeps increasing without bound, eventually leading to an OOM error. I think I narrowed down the issue with valgrind massif to push_assert in stats.c, and the strdup it does there. What is the expected behavior? Here's a simple test whose memory usage keeps growing.

Note: you won't catch it just with valgrind heap leak, because the memory gets cleaned up afterwards, its just during the test a lot of memory gets allocated

```c
#include <criterion/criterion.h>

Test(meow, static)
{
    for (int i = 0; i < (1 << 20); i++) {
        cr_assert(1 == 1);
        cr_assert(2 == 2);
        cr_assert(3 == 3);
    }
}
```

Thanks
-Jan

**Comment by Snaipe** [comment]
Does this happen with `v2.3.1` ? Memory explosion due to reported statistics on passed assertions should no longer be an issue since cr_assert now only reports when the assert fails.

**Comment by cybojanek** [comment]
Yes, sorry about that. Issue is *not* present under v2.3.1
