### ISSUE TITLE
`Could not spawn test instance: Protocol error` when executing test binary with `--debug=lldb` on Mac

### ISSUE THREAD

**Issue by kevincon** [Snaipe/Criterion#205]
First off, thanks so much for writing such a great unit testing framework. 😃 

I am trying to debug a Criterion test binary on my Mac (Sierra 10.12.4) by running it with the `--debug=lldb` argument. The test binary reports the following error:

```
criterion: Could not spawn test instance: Protocol error
[1]    54389 abort       --debug=lldb
```

I couldn't see that Xcode comes with `lldb-server`, so I installed `llvm` from Homebrew by first following this guide to prepare a codesigning certificate (https://llvm.org/svn/llvm-project/lldb/trunk/docs/code-signing.txt) and then running `brew install llvm --with-lldb --with-python`. Since Homebrew installs `llvm` as a keg, I also modified my PATH so that `lldb-server` would be visible to the test binary:

```
PATH=/usr/local/opt/llvm/bin:$PATH
```

`lldb-server` seems to be visible as I can run this command in the same shell that I'm trying to run the test binary from:

```
$ lldb-server version
lldb-360.99.0
```

Can you see what I'm doing wrong?

One more thing worth noting in case it makes a difference: I built the test binary (including Criterion and its dependencies) for `i386`. Here's a copy of my cmake toolchain file in case that's helpful:

```
if(APPLE)
    SET(CMAKE_SYSTEM_NAME "Darwin")
    SET(CMAKE_C_COMPILER "clang")
    SET(CMAKE_CXX_COMPILER "clang++")
else()
    SET(CMAKE_SYSTEM_NAME "Linux")
    SET(CMAKE_C_COMPILER "clang-3.8")
    SET(CMAKE_CXX_COMPILER "clang++-3.8")
endif()

set(CMAKE_SYSTEM_PROCESSOR "i386" CACHE STRING "" FORCE)

set(CMAKE_C_FLAGS "-std=gnu11 -m32" CACHE STRING "" FORCE)
set(CMAKE_ASM_FLAGS  "-m32" CACHE STRING "" FORCE)
```

Alternatively, what's the easiest way to debug Criterion test binaries on Mac? I would actually prefer using `gdb` over `lldb` if that's possible, but I tried installing `gdb` from homebrew and it didn't seem to include `gdbserver`. I think I could get `gdbserver` if I built `gdb` from source, but I'm hoping there might be a simpler way. 😄 

As a side note, I was able to build and debug my test binary from within an Ubuntu 14.04 Parallels VM on my Mac. It worked for both `--debug=lldb` (after `sudo apt-get install lldb-3.8` and symlinking `/usr/bin/lldb-server-3.8` to `/usr/bin/lldb-server`) and `--debug=gdb` (after `sudo apt-get install gdbserver`).

**Comment by Snaipe** [comment]
That's weird -- maybe the lldb server changed its CLI in-between versions? Does running `lldb-server gdbserver *:1234 /path/to/some/dummy/program` works for instance?

I don't think that the different architecture would be an issue, as I explicitely `execve` the lldb server. At least, I don't think it should. I'll investigate to see whether this is an issue under macOS. Does building a x86_64 criterion & test works otherwise with `--debug=lldb` ?

In any case, if the integration with a debugging server fails, you can always spawn your test with `./test --debug=idle`, remotely attach with gdb by PID (you'll probably have to run gdb as root though), and run in gdb `shell kill -CONT <pid>`, then `continue`. This is probably the best method to use by default on macOS as gdbserver/lldb-server doesn't ship.

**Comment by kevincon** [comment]
> Does running `lldb-server gdbserver *:1234 /path/to/some/dummy/program` works for instance?

Ah that seems to point to part of the issue. When I run that command on Mac for my test binary (after building the test binary on Mac) I get:
```
[1]    64507 segmentation fault  lldb-server gdbserver "*:1234"
```
but if I run it in my Ubuntu VM for my test binary (after building the test binary in the VM) I get the following (which looks correct):
```
using the default platform: host
Launched '</path/to/test_binary>' as process 28544...
```

I also get the segmentation fault on Mac for other programs (e.g. I tried `/usr/local/bin/python`), so maybe the issue is just that there's something wrong with the version of `lldb-server` I got from installing `llvm` via homebrew.

> In any case, if the integration with a debugging server fails, you can always spawn your test with ./test --debug=idle, remotely attach with gdb by PID (you'll probably have to run gdb as root though), and run in gdb shell kill -CONT <pid>, then continue. This is probably the best method to use by default on macOS as gdbserver/lldb-server doesn't ship.

I'm happy to report that this works (so I guess the different architecture isn't a factor), but since my test binary has a suite of multiple tests, each test is launched one at a time (not launching the next one until I have attached to the previous and run it to completion). So it seems that if I want to debug the last test case I would have to manually attach to each of the other test cases before I get to that one. Luckily you provide the `--filter` argument for test binaries so I'm able to use that to specify the name of the particular test case I want to run, so I think this workflow will work for me. :)

One more thing I noticed (and I'm happy to move this to a new issue if you think we should), but if I am debugging a test binary using `--debug=idle` and I send `CTRL+C` to the terminal where that's being run (which quits the test binary), if I run `ps ax | grep boxfort` I still see some processes running that have the PIDs of the test cases that I was debugging. But shouldn't those be killed wen I send `CTRL+C` to the test binary that started them?

**Comment by Snaipe** [comment]
> So it seems that if I want to debug the last test case I would have to manually attach to each of the other test cases before I get to that one. Luckily you provide the --filter argument for test binaries so I'm able to use that to specify the name of the particular test case I want to run, so I think this workflow will work for me. :)

Yes, this is the intended semantics for the usage of selective --debug -- glad to see that it's intuitive enough.

> One more thing I noticed (and I'm happy to move this to a new issue if you think we should), but if I am debugging a test binary using --debug=idle and I send CTRL+C to the terminal where that's being run (which quits the test binary), if I run ps ax | grep boxfort I still see some processes running that have the PIDs of the test cases that I was debugging. But shouldn't those be killed wen I send CTRL+C to the test binary that started them?

This is actually a [BoxFort issue](https://github.com/diacritic/BoxFort/issues/12) that exists on platforms without `prctl(PR_SET_PDEATHSIG)`, as linux/bsd use this syscall to automatically terminate children. However, no sensible fallback exists yet in BoxFort for platforms that doesn't have this (Windows, macOS), so children may be escaping on such situations.

**Comment by Snaipe** [comment]
Closing this as it is not a Criterion bug per-se, and the children-not-dying issue is already filed on the BoxFort issue tracker.
