### ISSUE TITLE
Fix the docs about providing your own main to include __dllexport on windows.

### ISSUE THREAD

**Issue by Snaipe** [Snaipe/Criterion#212]
[The example main on this page](http://criterion.readthedocs.io/en/latest/internal.html#example-main) doesn't work at all on windows (failing with `criterion: Could not spawn test instance: No child processes`). This is because the main function should be dllexported on this platform.

The documentation should be updated to reflect this.

**Comment by margaretdax** [comment]
@Snaipe I am getting this error on Windows but I'm not attempting to define my own internals afaik (I need Criterion for the project [c_koans](https://github.com/c-koans/c_koans))

Building Criterion from sources w/ CMake via CLion w/ the packaged mingw-64 toolchain (rather than MSVC)
