### ISSUE TITLE
Assert additional tests when .exit_code is specified?

### ISSUE THREAD

**Issue by ArchKudo** [Snaipe/Criterion#219]
If I have a `die` function which exits on failure and also prints an error message to stderr, is there a way to test both using a single test? Currently, it skips asserting the test present in the function and passes the test.
For eg. the following test passes even when the strings are unequal:

```
    Test(die, passing, .exit_code=EXIT_FAILURE) {  
        cr_assert_str_eq(charbuf, message); // Failing  
    }  
```
P.S: I'm sorry if this is something obvious, and/or isn't in accordance to the design of Criterion

**Comment by Snaipe** [comment]
Mmh, this seems like an oversight. What version are you using?

**Comment by ArchKudo** [comment]
Criterion 2.3.2
```
./test -v
Tests compiled with Criterion v2.3.2

```

**Comment by Snaipe** [comment]
I'm not sure how that would work. `die()` exits the program, so any statement below it won't be executed. If you need to make some assertions, you'll have to do them before the process exit.

**Comment by ArchKudo** [comment]
I am so sorry for troubling you, for something this stupid on my part, thanks for looking into it anyway, Sorry again😅😅

**Comment by Snaipe** [comment]
No worries, that's my responsibility with support :)

If you need help, I'd recommend dropping me an email or pinging me on Gitter/IRC. You'll usually get faster response time.
