### ISSUE TITLE
Binaries for latest release

### ISSUE THREAD

**Issue by offa** [Snaipe/Criterion#22]
Hello,

can you add binaries to the new release 1.2.1 (at least linux)? Without it's difficult to use within CI.

Thanks.

**Comment by Snaipe** [comment]
[Here you go](https://github.com/Snaipe/Criterion/releases/download/v1.2.1/criterion-1.2.1-linux-x86_64.tar.bz2) :)

**Comment by offa** [comment]
Wow that was fast! Thanks, now CI works with 1.2.1.
