### ISSUE TITLE
master docs are not up to date, 2.3.1 docs are missing

### ISSUE THREAD

**Issue by kubiajir** [Snaipe/Criterion#221]
Hi,
 I have finally compiled cloned Criterion however I had followed issues:

Extra work to compile Criterion:
 * Clone external repository to Criterion/dependencies/nanopb
 * Find and download debugbreak.h to Criterion/include/ and modify Criterion/src/core/abort.c
 * Find and download khash.h to Criterion/include/ and modify Criterion/src/core/runner.c and Criterion/src/io/output.c
 * Find and download kvec.h to Criterion/include/ and modify Criterion/src/io/output.c

I dont have these headers in my distribution as default.

**Comment by Snaipe** [comment]
You need to clone the submodules too. See [building from source](http://criterion.readthedocs.io/en/latest/setup.html#building-from-source) for instructions.

In your case, since you already cloned without --recursive, you can run `git submodule update --init --recursive` to get things to work.

**Comment by kubiajir** [comment]
Hi thanks for a quick answer, how ever you points me to a "latest" version of doc but when I open [Criterion web](http://criterion.readthedocs.io) page it point me to a "master" where is not the clone command in Prerequisites.

**Comment by Snaipe** [comment]
The old releases have a cmake module that should be auto-cloning these dependencies, however I'm assuming that you cloned the latest bleeding, so I can see where the confusion is coming from.

I'll fix the readme to include both the stable docs and the bleeding docs. Incidentally, it seems that the 2.3.1 docs are down, which should have updated master with it, so this is a bit weird. I'll look into that.

**Comment by kubiajir** [comment]
OK.

Just another question regarding to the compilation - have you ever tried to compile it on Raspberry pi? The boxfort fails on 
CMake Error at CMakeLists.txt:74 (message):
  Architecture 'armv7l' is not supported.

I need to run it on rpi as we are going to test API calls via buses (UART/SPI) of embedded device.

**Comment by Snaipe** [comment]
There is a [work in progress](https://github.com/diacritic/BoxFort/tree/arch/arm) for boxfort to support ARM, but I haven't tested it on real hardware so far. Can you try it out and let me know how it goes?

**Comment by kubiajir** [comment]
Well .... done. 
I had to wipe out Criterion/build/boxfort-build/tmp/boxfort-git* to stop cmake forcing the selected git commit for Boxfort. Then I had to update boxfort/CMakeLists.txt to accept RPI arch type
-set (ARM32 "^(arm|ARM|A)(32)?$")
+set (ARM32 "^(arm|ARM|A|armv7l)(32)?$")

With this settings it seems to be working - Criterion compiled and simple example is working. 

One note, on my distro (Calculate linux - based on Gentoo,  and Raspbian) I had to move installed libraries from /usr/local/lib to /usr/lib .

**Comment by Snaipe** [comment]
That's great! I'll merge the ARM code in soon then.

I would recommend you use `cmake -DCMAKE_INSTALL_PREFIX=/usr` to have CMake install the files under /usr rather than /usr/local, but libcriterion shouldn't care about its install path (some libs do, due to rpath shenanigans, but this is not the case here)

**Comment by stef** [comment]
OP writes that he was able to find `kvec.h` and put it in an include directory. i've been looking and found like 4 different projects with `kvec.h`s, can you say where you found this header? my system also lacks this.

**Comment by MrAnno** [comment]
Closing due to being outdated. (Also "fixed" by #407)
