### ISSUE TITLE
Can't execute my a.out

### ISSUE THREAD

**Issue by Swegrid** [Snaipe/Criterion#223]
Hello,

I'm on ManjaroLinux Deepin v17.0.5, i installed the library by following all the instructions, but i can't execute my a.out.
I have the "./a.out: error while loading shared libraries: libcriterion.so.3: cannot open shared object file: No such file or directory" error

I tried to reinstall the library but it still doesn't work, any idea ?
If you need any more informations, i'll give it to you

Thanks

**Comment by Snaipe** [comment]
This can happen if libcriterion.so can't be found in the system path (usually /usr/lib). I would suggest installing the library under /usr (`cmake -DCMAKE_INSTALL_PREFIX=/usr ..; make; sudo make install`), or define LD_LIBRARY_PATH to the path containing libcriterion, or adding it to your program's rpath (`-Wl,-rpath,/path/to/lib/dir`).

**Comment by Swegrid** [comment]
Thanks a lot, it works perfectly now ! :)

**Comment by karlvignon** [comment]
Thanks Snaipe !

**Comment by Snaipe** [comment]
FWIW, since I've been asked, ever since we've switched to meson, the new way to install under the right prefix is `meson build --prefix=/ && ninja -C build && sudo ninja -C build install`.

**Comment by HugoGDRM** [comment]
thanks a lot man good work !
