### ISSUE TITLE
ParameterizedTest - parallelization 

### ISSUE THREAD

**Issue by kubiajir** [Snaipe/Criterion#227]
Hi,
is ParameterizedTest running in parallel? Im creating test for API testing over serial/SPI line - for this Im using external program.  So in Criterion I have written some API wrapper over this program and I want to test the API by sending a tons of commands. How ever I have found out that I can create test with which looks like

Test(gpio, setOutput2) {
....
cr_assert_eq(gpio_cfg_output(GPIO_IDX_13, 0), M_OK);
cr_assert_eq(gpio_cfg_output(GPIO_IDX_14, 0), M_OK);
cr_assert_eq(gpio_cfg_output(GPIO_IDX_2, 0), M_OK); 
....
}

This test if fine, no problem. The I convert it to ParameterizedTest as i dont want write each line manually.  Then I have ParameterizedTestParameters with two diemnsional array with command argument and expected output  and this test 

ParameterizedTest(struct parameter_tuple *tup, gpio, setOutput) {
     cr_assert_eq(gpio_cfg_output(tup->gpio, 0), tup->o);
 }

And this test starts freaking out, by slightly investigation it seems that it is running the test in parallel  and this causes the serial line application to be running for multiple time simultaneously.  Also I have added some debug info i into the wrapper and it seems that it is running in different threads. Is there a way how to stop this feature?

Regards,
Jiri

**Comment by Snaipe** [comment]
You can disable parallel testing altogether by passing -j1 to the test
executable, or setting CRITERION_JOBS=1 in your environment before running
your tests.

If I had to test a few GPIO interactions in a sequence, I would probably
put the values I'm testing in an array and just call the function in a loop
until I don't have any values left to test.

Disabling parallelization for sub-tests could be something interesting to
consider for #204.

**Comment by kubiajir** [comment]
Hi thanks, 
Im testing multiply GPIOs and I can use all range and some of them must fails for setting and etc. 

Any way I have one more question, if I have done a test suites, is there a way how to call one test for a 1000x time?  So I want to create test which will cover all api calls and then I want to create test which will call each test for a 1000x times to test if not fail.

**Comment by Snaipe** [comment]
You can't repeat a test N times currently, but you could call the whole test suite from outside any number of times you want. I'm not sure this is something I would like to see in Criterion, but for the sake of completeness it could be interesting to consider that for #204.
