### ISSUE TITLE
criterion: Could not initialize test context: Invalid argument 

### ISSUE THREAD

**Issue by kubiajir** [Snaipe/Criterion#228]
Hi Im running Criterion on rpi and when I run the test for multiply time I receive  criterion: Could not initialize test context: Invalid argument error.  Any Idea what could be wrong?
```

pi@rpi3:~/crit $ ./criterion-sapi -j1
[====] Synthesis: Tested: 40 | Passing: 40 | Failing: 0 | Crashing: 0 
pi@rpi3:~/crit $ ./criterion-sapi -j1
criterion: Could not initialize test context: Invalid argument
Aborted
pi@rpi3:~/crit $ ./criterion-sapi -j1
[====] Synthesis: Tested: 40 | Passing: 40 | Failing: 0 | Crashing: 0 
```

I have also observed that each test is running in separate process ?  It is a good way how to speedup the test for simply tests. How ever for complex test it could be a problem if test ts dependent on previous test as it could use local variable. 

Actually what is the order of running test? For example I need to set GPIO to output (one test) before setting the GPIO output value ( second test). So I need to run tests in specified sequence.

**Comment by kubiajir** [comment]
The "criterion: Could not initialize test context: Invalid argument Aborted" is not happening in the same point of my program.  Some time it failures earlier/later/immediately. And it seems that is is related to program output, the app print out some errors or I use cr_log_error for debug output then it fails earlier.

**Comment by Snaipe** [comment]
The general stance that Criterion takes about tests is that tests should not rely on execution order. We might randomize the order of tests, or even prioritize them to run long-running tests in a separate core first while smaller tests are run in sequence. Point is, you shouldn't (in theory) make tests depend on each other.

This is somewhat necessary when talking to an external component, but the only possible solution here is to make your tests self-contained, as in: initialize everything needed up to the point where the test is runnable, and clean-up after itself. If doing so is critical, then you'd surely be interested in using test hooks for initializing and finalizing your component.

As for the abort(), I would guess that BoxFort has some issues with the 32-bit address space and setting up the inheritable heap. Could you send me a core dump? (make sure you include debug infos)
