### ISSUE TITLE
Function cr_assert_err_eq not documented properly.

### ISSUE THREAD

**Issue by MickaToast** [Snaipe/Criterion#229]
Hi,

I've notified that cr_assert_arr_eq is not documented properly, ie the third parameter of the function is said to be " * @param[in] FormatString (optional) printf-like format string" but in fact it need to be given and must represent the size of the array.

Thanks.

**Comment by MickaToast** [comment]
Seems that the issue was already reported 1 year ago #100

**Comment by Snaipe** [comment]
Good catch! it seems that we regressed when we switched to doxygen.

**Comment by utybo** [comment]
3 years later, this is still an issue fyi :D

Anything we could do to help?

**Comment by talentless-script-kiddie** [comment]
still an issue as of september 2021 :(  I thought the array macros were broken and I was using `cr_assert_eq(memcmp())` instead ...

**Comment by Snaipe** [comment]
This will be fixed by the new 2.4.0 release. Sorry for the massive delay.
