### ISSUE TITLE
Help building on an arm platform

### ISSUE THREAD

**Issue by chuckfossen** [Snaipe/Criterion#233]
I would like to build criterion on an aarch64 platform.
I'm new to cmake and git submodules...
I'm trying to figure out how to build using the arch/arm branch of boxfort.
Any hints on how to do this would be helpful.
Thanks

**Comment by Snaipe** [comment]
There were no trampolines in BoxFort for Arm64, so I just pushed one to arch/arm. I think it'll work, looking at how I implemented the Arm64 part of Mimick, but it'll probably need some more refinements & proper testing.

To get Criterion to work with that version of BoxFort, simply clone BoxFort and switch to the arch/arm branch, then compile & install it to /usr -- when you build Criterion, it should be able to detect the system installation of BoxFort and use it.

Let me know if you need more help/have other issues with it. I'll check if the Arm64 code works in qemu in the meantime.

**Comment by chuckfossen** [comment]
Thank you very much! I'll give it a try.

**Comment by chuckfossen** [comment]
Builds ok now. I can't test until I get another dependency for my application resolved on this platform.
