### ISSUE TITLE
Ubuntu 17.10 artful: repository missing build

### ISSUE THREAD

**Issue by brian-gavin** [Snaipe/Criterion#236]
Hi! Recently updated to Ubuntu 17.10 artful, wanted to install Criterion, and the repository doesn't have an artful release yet.

**Comment by Snaipe** [comment]
I'll trigger a build for newer versions of Ubuntu. I keep forgetting about doing that :)

**Comment by Snaipe** [comment]
Unfortunately, it looks like Artful has been obsoleted -- I can't push a build for it on launchpad. Sorry about that.

I've pushed builds for Xenial, Bionic and Cosmic, though.
