### ISSUE TITLE
criterion_log_noformat: use correct stream for line ending

### ISSUE THREAD

**Issue by stv0g** [Snaipe/Criterion#239]
https://github.com/Snaipe/Criterion/blob/514b4d820e2f8fb4daa2b95b69c981853656cb73/src/log/logging.c#L92

**Comment by Snaipe** [comment]
I'm not sure I'm getting this issue. Criterion logs messages to stderr to allow callers to manipulate the standard output of any test not redirecting it. Since logs are not meant to be consumed by programs, it's more appropriate to do so on stderr regardless of the logging level.

**Comment by stv0g** [comment]
Ah okay, now I get it :)

Sorry
