### ISSUE TITLE
Feature request: --exclude-pattern option. 

### ISSUE THREAD

**Issue by bturrubiates** [Snaipe/Criterion#24]
While using Criterion something that we find would be useful is the option for a negation pattern. The option to selectively run certain tests exists, but of course doesn't support full regular expression syntax. Rather than needing to specifically disable in the source it'd be cool if we could do the following: 

```
./test --exclude-pattern="suite_a/*"
```
To run all tests from suites other than the `suite_a` suite. 

To my knowledge this isn't possible with the current `--pattern` option, but I could be mistaken.

**Comment by Snaipe** [comment]
Rather than adding an option, I'm thinking of adapting the --pattern switch to accept extended globbing patterns. One could match all the tests but `foo/bar` with `--pattern="!(foo/bar)"`.

I also could add a --regexp that matches the tests against a regular expression, if `<regex.h>` is available.

**Comment by bturrubiates** [comment]
That sounds acceptable to me. @jswaro What do you think?

**Comment by jswaro** [comment]
I think both options sound fine.

**Comment by Snaipe** [comment]
This has been implemented. It currently transforms the pattern to a Perl regular expression, and will add libpcre as a dependency.

The feature will be available on the next minor release (1.3).
