### ISSUE TITLE
CMake: provide an IMPORTED target

### ISSUE THREAD

**Issue by ghost** [Snaipe/Criterion#244]
Feature request: generate and install a CMake package config file so that it's possible to consume this project in CMake-specific manner, i.e. via a target:
```cmake
find_package(Criterion REQUIRED CONFIG)
target_link_libraries(tgt PRIVATE Criterion::criterion) # for example
```

**Comment by Snaipe** [comment]
Does this have advantages over using `pkg_check_modules` and the pkg-config definitions? I'm curious, because I never really had to use cmake package config files, and it looks like the pkg-config stuff is somewhat more broadly available.

**Comment by light2yellow** [comment]
Technically, I don't think it has any, but it is an idiomatic CMake and allows easier and fancier consumption for downstream, and for downstream's downstream, and so on.

**Comment by Snaipe** [comment]
Thinking about this a bit more, it's true that pkg-config might not be present on the system (Windows), so it might make sense to provide a Config.cmake file.

**Comment by MrAnno** [comment]
Criterion has migrated to the Meson build system. Imported targets are no longer options this way, so I'm closing this issue.

One thing that can be improved further is the CMake "find module". We could use modern exported targets instead of old-style variables.
