### ISSUE TITLE
criterion-dev from ppa:snaipewastaken/ppa is outdated

### ISSUE THREAD

**Issue by timgabets** [Snaipe/Criterion#249]
Hi, 
first of all, thank you so much for the library - it's really cool! There is a problem - it seems that ppa:snaipewastaken/ppa contains the old version of the library - for example, there is no include/criterion/new/*.h headers. Could you please fix it?

Many thanks.

**Comment by Snaipe** [comment]
The new/ headers have not been part of a release just yet. I don't think Criterion in its current state is release-worthy, as there are some remaining issues with the sandboxing subsystem, but we're (slowly) getting there!

**Comment by Snaipe** [comment]
Criterion has now been packaged on Debian & derivatives
