### ISSUE TITLE
build failed at Makefile2:590

### ISSUE THREAD

**Issue by jundai20** [Snaipe/Criterion#253]
Build steps:
  mkdir build
  cd build/
  cmake ..
  cmake --build .

$ uname -srvmpio
Linux 4.13.0-41-generic #46~16.04.1-Ubuntu SMP Thu May 3 10:06:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

== Error log ==
[ 60%] Built target dyncall_s-dependency
[ 80%] Built target csptr-dependency
[100%] Built target boxfort-dependency
make[2]: *** No rule to make target 'CMakeFiles/criterion.dir/build'.  Stop.
CMakeFiles/Makefile2:590: recipe for target 'CMakeFiles/criterion.dir/all' failed

**Comment by Snaipe** [comment]
Could you attach the rest of the log, and the contents of CMakeFiles/CMakeError.log and CMakeFiles/CMakeOutput.log (both are in the build directory)?

**Comment by Snaipe** [comment]
Actually, what did `cmake ..` say? I'm getting a somewhat similar result when cloning the repository without `--recursive`, did you clone the submodules?

**Comment by jundai20** [comment]
Thanks for later response.  It is not reproduced. I've built on virtual box and old virtual box image lost, when I start a new clean box and install all required packages, the build passed.

**Comment by jundai20** [comment]
judai@judai-VirtualBox:~/opensource/shadow-plugin-extras/hello$ shadow example.xml 
** Starting Shadow v1.13.0-56-gb43caa2c 2019-07-24 (built 2019-08-08) with GLib v2.56.4 and IGraph v0.7.1
00:00:00.000194 [thread-0] n/a [message] [n/a] [shd-logger.c:296] [_logger_logStartupMessage] logging system started at 2019-08-09 13:17:15
00:00:00.000228 [thread-0] n/a [message] [n/a] [shd-main.c:352] [_main_helper] Starting Shadow v1.13.0-56-gb43caa2c 2019-07-24 (built 2019-08-08) with GLib v2.56.4 and IGraph v0.7.1
00:00:00.000331 [thread-0] n/a [message] [n/a] [shd-main.c:359] [_main_helper] For more information, visit https://shadow.github.io or https://github.com/shadow
00:00:00.000334 [thread-0] n/a [message] [n/a] [shd-main.c:360] [_main_helper] logging current startup arguments and environment
00:00:00.000347 [thread-0] n/a [message] [n/a] [shd-main.c:316] [_main_logEnvironment] arg: shadow
00:00:00.000349 [thread-0] n/a [message] [n/a] [shd-main.c:316] [_main_logEnvironment] arg: example.xml
00:00:00.000359 [thread-0] n/a [message] [n/a] [shd-main.c:370] [_main_helper] shadow will automatically adjust environment and relaunch
00:00:00.000361 [thread-0] n/a [message] [n/a] [shd-main.c:371] [_main_helper] loading shadow configuration file
00:00:00.000472 [thread-0] n/a [message] [n/a] [shd-main.c:394] [_main_helper] shadow configuration file loaded, parsed, and passed validation
00:00:00.000495 [thread-0] n/a [message] [n/a] [shd-main.c:406] [_main_helper] setting up LD_PRELOAD environment
00:00:00.000509 [thread-0] n/a [message] [n/a] [shd-main.c:594] [_main_helper] setting up LD_STATIC_TLS_EXTRA environment
00:00:00.000857 [thread-0] n/a [message] [n/a] [shd-main.c:151] [_main_computeLoadSize] we need 144 bytes of static TLS per load of namespace with library at path '/home/judai/.shadow/plugins/libshadow-plugin-hello.so'
00:00:00.003202 [thread-0] n/a [message] [n/a] [shd-main.c:151] [_main_computeLoadSize] we need 0 bytes of static TLS per load of namespace with library at path '/home/judai/.shadow/lib/libshadow-interpose.so'
00:00:00.003206 [thread-0] n/a [message] [n/a] [shd-main.c:303] [_main_getStaticTLSValue] finished checking TLS size required for 2 hosts; used dlmopen for 1 namespaces and cache for 1 namespaces
00:00:00.003213 [thread-0] n/a [message] [n/a] [shd-main.c:601] [_main_helper] we need 1024 total bytes of static TLS storage
00:00:00.003226 [thread-0] n/a [message] [n/a] [shd-main.c:642] [_main_helper] environment was updated; shadow is relaunching now with new environment
00:00:00.003265 [thread-0] n/a [message] [n/a] [shd-logger.c:310] [_logger_logShutdownMessage] logging system stopped at 2019-08-09 13:17:15, run time was 00:00:00

(shadow:10637): GLib-CRITICAL **: 13:17:16.020: g_hash_table_foreach: assertion 'hash_table != NULL' failed
00:00:00.000054 [thread-0] n/a [message] [n/a] [shd-logger.c:296] [_logger_logStartupMessage] logging system started at 2019-08-09 13:17:16
00:00:00.000077 [thread-0] n/a [message] [n/a] [shd-main.c:352] [_main_helper] Starting Shadow v1.13.0-56-gb43caa2c 2019-07-24 (built 2019-08-08) with GLib v2.56.4 and IGraph v0.7.1
00:00:00.000081 [thread-0] n/a [message] [n/a] [shd-main.c:359] [_main_helper] For more information, visit https://shadow.github.io or https://github.com/shadow
00:00:00.000083 [thread-0] n/a [message] [n/a] [shd-main.c:360] [_main_helper] logging current startup arguments and environment
00:00:00.000093 [thread-0] n/a [message] [n/a] [shd-main.c:316] [_main_logEnvironment] arg: shadow
00:00:00.000095 [thread-0] n/a [message] [n/a] [shd-main.c:316] [_main_logEnvironment] arg: example.xml
00:00:00.000097 [thread-0] n/a [message] [n/a] [shd-main.c:316] [_main_logEnvironment] arg: --preload=/home/judai/.shadow/lib/libshadow-interpose.so
00:00:00.000104 [thread-0] n/a [message] [n/a] [shd-main.c:328] [_main_logEnvironment] env: LD_STATIC_TLS_EXTRA=1024
00:00:00.000106 [thread-0] n/a [message] [n/a] [shd-main.c:328] [_main_logEnvironment] env: SHADOW_SPAWNED=TRUE
00:00:00.001183 [thread-0] n/a [message] [n/a] [shd-main.c:696] [_main_helper] startup checks passed, we are ready to start simulation
00:00:00.001188 [thread-0] n/a [message] [n/a] [shd-master.c:95] [master_new] simulation master created
00:00:00.001190 [thread-0] n/a [message] [n/a] [shd-master.c:391] [master_run] loading and initializing simulation data
00:00:00.001273 [thread-0] n/a [message] [n/a] [shd-master.c:171] [_master_loadConfiguration] successfully parsed Shadow XML input!
00:00:00.001453 [thread-0] n/a [message] [n/a] [shd-topology.c:370] [_topology_loadGraph] reading graphml topology graph at '/tmp/shadow-topology-U3385Z.graphml.xml'...
00:00:00.001684 [thread-0] n/a [message] [n/a] [shd-topology.c:381] [_topology_loadGraph] successfully read graphml topology graph at '/tmp/shadow-topology-U3385Z.graphml.xml'
00:00:00.001688 [thread-0] n/a [message] [n/a] [shd-topology.c:713] [_topology_checkGraphProperties] checking graph properties...
00:00:00.001690 [thread-0] n/a [message] [n/a] [shd-topology.c:555] [_topology_checkGraphAttributes] checking graph attributes...
00:00:00.001713 [thread-0] n/a [warning] [n/a] [shd-topology.c:628] [_topology_checkGraphAttributes] vertex attribute 'geocode' has been renamed to 'countrycode' and is considered deprecated; please use 'countrycode' and/or 'citycode' instead
00:00:00.001723 [thread-0] n/a [message] [n/a] [shd-topology.c:701] [_topology_checkGraphAttributes] successfully verified all graph, vertex, and edge attributes
00:00:00.001745 [thread-0] n/a [message] [n/a] [shd-topology.c:782] [_topology_checkGraphProperties] topology graph is complete, undirected, and strongly connected with 1 cluster. It does not prefer direct paths.
00:00:00.001749 [thread-0] n/a [message] [n/a] [shd-topology.c:1007] [_topology_checkGraphVertices] checking graph vertices...
00:00:00.001766 [thread-0] n/a [warning] [n/a] [shd-topology.c:935] [_topology_checkGraphVerticesHelperHook] optional attribute 'asn' on vertex 0 (id='poi-1') is non-positive
00:00:00.001771 [thread-0] n/a [warning] [n/a] [shd-topology.c:999] [_topology_iterateAllVertices] we had a problem validating vertex attributes
00:00:00.001773 [thread-0] n/a [warning] [n/a] [shd-topology.c:1012] [_topology_checkGraphVertices] unable to validate graph vertices
00:00:00.002829 [thread-0] n/a [message] [n/a] [shd-topology.c:1265] [_topology_clearCache] path cache cleared, spent 0.000000 seconds computing 0 shortest paths with dijkstra, and 0.000000 seconds computing 0 shortest self paths
00:00:00.002839 [thread-0] n/a [critical] [n/a] [shd-topology.c:2488] [topology_new] we failed to create the simulation topology because we were unable to validate the topology graphml file
00:00:00.005091 [thread-0] n/a [critical] [n/a] [shd-master.c:216] [_master_loadTopology] fatal error loading topology at path '/tmp/shadow-topology-U3385Z.graphml.xml', check your syntax and try again
00:00:00.005107 [thread-0] n/a [message] [n/a] [shd-master.c:118] [master_free] simulation master destroyed
00:00:00.005109 [thread-0] n/a [message] [n/a] [shd-main.c:720] [_main_helper] Shadow v1.13.0-56-gb43caa2c 2019-07-24 (built 2019-08-08) simulation was shut down cleanly, returning code 1
00:00:00.005157 [thread-0] n/a [message] [n/a] [shd-logger.c:310] [_logger_logShutdownMessage] logging system stopped at 2019-08-09 13:17:16, run time was 00:00:00
