### ISSUE TITLE
assert for not terminated string

### ISSUE THREAD

**Issue by Kokan** [Snaipe/Criterion#255]
Based on the documentation, there is no way to assert a string that is not terminated.
Something like this:
```c
char foo[3] = {'f', 'o', 'o'};

cr_assert_nstr_eq( foo, "foo", 3);
```

Of course this could be solved with more code, but I would prefer to have in the API directly.

**Comment by Snaipe** [comment]
This should actually be addressed with the (not-yet-released) [new assertion API](https://criterion.readthedocs.io/en/latest/assert.html#assertion-api), using either the `chr` tag, or the `mem` tag:

```c
char foo[3] = {'f', 'o', 'o'};

// using chr[3]
cr_assert(eq(chr[3], foo, "foo"));

// using mem
struct cr_mem m1 = { .data = foo, .size = 3 };
struct cr_mem m2 = { .data = "foo", .size = 3 };
cr_assert(eq(mem, m1, m2));
```

**Comment by Kokan** [comment]
Oh, I am going to check the new API. Do you plan to change the Theories also with the same logic ?

**Comment by Snaipe** [comment]
There is a long discussion [here](https://github.com/Snaipe/Criterion/issues/204) about how where the test API should go in the future; there were some ideas about reusing a similar tag system for type safety, but I'm still pieceing thing together in my head to be sure we get this right for 3.0.
