### ISSUE TITLE
Malloc fails inside tests

### ISSUE THREAD

**Issue by equals215** [Snaipe/Criterion#257]
I've written a simple function which checks if the malloc'd pointer isn't null : 

```
void *smalloc(size_t size)
{
	void *ptr = malloc(size);

	if (ptr == NULL) {
		perror("malloc");
		exit(84);
	}
	return (ptr);
}
```

I'm testing some functions using this smalloc and the tests compile but always print the perror message or if I get rid of the exit the tests segfaulting with core dump.
Did I made something wrong with the memory allocation inside criterion tests or it's just a criterion bug ?

**Comment by Snaipe** [comment]
Do you have a simple, reproducible, self-contained example that I can compile on my machine? Your smalloc looks correct, and I've used criterion to test simple memory allocators before, but did not have any issues in doing so.

**Comment by equals215** [comment]
I dont even know where the problem come from but I can give you an access to the repo where this problem occurs.

**Comment by Snaipe** [comment]
No need to give me access to anything; though having a small .c file that exposes the problem would help.

Could you give me more details on the environment you are having this issue from? (Version of Criterion used, OS and/or distro, compiler version, etc)

**Comment by equals215** [comment]
Using : 
- Criterion 2.3.2-1
- Linux anarchy 4.16.3-1-ARCH
- gcc 7.3.1+20180406-1

U'll find all the sources used in this zip file
[criterion_issue.zip](https://github.com/Snaipe/Criterion/files/2081390/criterion_issue.zip)

**Comment by Snaipe** [comment]
FWIW, the following example works:
```c
// lib.h
#pragma once

void *smalloc(size_t size);
void usesmalloc(void);
```
```c
// lib.c
// gcc -shared -fPIC -o libsmalloc.so ./lib.c
#include <stdio.h>
#include <stdlib.h>

void *smalloc(size_t size)
{
	void *ptr = malloc(size);

	if (ptr == NULL) {
		perror("malloc");
		exit(84);
	}
	return (ptr);
}

void usesmalloc(void)
{
	int *ptr = smalloc(4);
	*ptr = 4;
	free(ptr);
}
```
```c
// test.c
// gcc -I../include -o t ./test.c -L. -lcriterion -lsmalloc -Wl,-rpath,$(pwd)
#include <criterion/criterion.h>
#include <criterion/new/assert.h>

#include "lib.h"

Test(foo, bar) {
	usesmalloc();
}

Test(foo, baz) {
	void *ptr = smalloc(4096);
	cr_assert(not(zero(ptr)));
	free(ptr);
}
```

**Comment by Snaipe** [comment]
Ah, great! I'll have a look at the archive.

**Comment by equals215** [comment]
I don't think so, i'll try some things then i'll post here again

**Comment by equals215** [comment]
So I found out where it crashed, the smalloc make the tests crash when the function exit is in the function.

**Comment by Snaipe** [comment]
I'm not sure if it's even Criterion's fault at this point (not to mention that I haven't been able to reproduce it).

I'm closing this issue. We can still reopen it in the future if it happens again in a reproducible setup.
