### ISSUE TITLE
error C2001: newline in constant

### ISSUE THREAD

**Issue by hxl-dy** [Snaipe/Criterion#264]
Using cmake and vs 2015.
```
  D:\tmp\github\Criterion\src\entry\params.c(110): error C2001: newline in constant [D:\tmp\github\Criterion\build\criterion.vcxproj]
  D:\tmp\github\Criterion\src\entry\params.c(111): error C2001: newline in constant [D:\tmp\github\Criterion\build\criterion.vcxproj]
```

**Comment by am11** [comment]
According to Google, it seems like it has something to do with system locale.

Could you try applying https://github.com/am11/Criterion/commit/9e2eb9d7a0e2a5cf31bf8e7f40738f0cf5a9e473 to see if it fixes the problem in your system?

**Comment by hxl-dy** [comment]
Fixed by https://github.com/am11/Criterion/commit/9e2eb9d7a0e2a5cf31bf8e7f40738f0cf5a9e473
