### ISSUE TITLE
Cannot install in Ubuntu Bionic

### ISSUE THREAD

**Issue by cprieto** [Snaipe/Criterion#267]
Latest Ubuntu (Bionic whatever is named) refuse to install from ppa, can we have a build for 18.04?

**Comment by kYroL01** [comment]
Same issue for Debian 8 Jessie

**Comment by Snaipe** [comment]
Bionic, Xenial, and Cosmic have been built -- please let me know if it works for Debian Jessie, too :)

**Comment by kYroL01** [comment]
@Snaipe it continue to complains:

>  Error:2 http://ppa.launchpad.net/snaipewastaken/ppa/ubuntu cosmic InRelease
>  W: Errore GPG: http://ppa.launchpad.net/snaipewastaken/ppa/ubuntu cosmic InRelease: Le seguenti firme non sono state verificate perché la chiave pubblica non è disponibile: NO_PUBKEY CE6500E9003E6E24
> E: Il repository "http://ppa.launchpad.net/snaipewastaken/ppa/ubuntu cosmic InRelease" non è firmato

Sorry, my terminal is in italian, but I think u can understand the problem :) . It seems it continue to ignore the fact I'm with Debian Jessie and not with Ubuntu Cosmic.
Might I should try another branch ?

**Comment by Snaipe** [comment]
I think that my GPG key didn't get pulled when you added the repository. Try pulling it manually with `sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com CE6500E9003E6E24`, and try to install the package again.

**Comment by alifwahid** [comment]
This month's xenial update is causing problems for me. Looks like the criterion package has a new dependency on libgit2. I had no trouble before this month's update. Below is the error message. Note that I tried installing libgit2 but haven't found a ppa source yet.

$ sudo apt-get install criterion
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 criterion : Depends: libgit2 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by johanols** [comment]
Same issue on Linux Mint 19.

**Comment by Snaipe** [comment]
Oh, that's a mistake on my part -- I accidentally published `bleeding` instead of `v2.3.2`. I've triggered another round of builds, it should now be working as expected.

**Comment by alifwahid** [comment]
Thanks @Snaipe. Works fine now on my setup.

**Comment by kYroL01** [comment]
@Snaipe now i successfully installed also in Debian 8. Thanks :)

**Comment by Snaipe** [comment]
Great. I'll assume this is fixed then. Feel free to open another issue if things are still broken.
