### ISSUE TITLE
Very difficult to debug crashing tests on macOS.

### ISSUE THREAD

**Issue by alexis-layton** [Snaipe/Criterion#268]
When a test case crashes on macOS it is very difficult to debug. Even after installing gdb there is no gdbserver command. There is no lldb-server command. A better solution is needed.

**Comment by Snaipe** [comment]
Have you tried using --debug=idle and attaching gdb to the child process PID?

**Comment by alexis-layton** [comment]
That seems to work. It doesn't seem to be documented in the section on debugging however.
(Attaching using lldb however, I still have issues with gdb on macOS High Sierra. I thought 8.1.1 had fixed the issue, apparently 8.2 has but it's not in the brew recipe yet.)
