### ISSUE TITLE
cannot find pb_common.c

### ISSUE THREAD

**Issue by darkjambon** [Snaipe/Criterion#275]
I follow this tuto to install Criterion.
mkdir build
cd build
cmake ..
cmake --install .
and I have this
CMake Error at .cmake/Modules/PackageUtils.cmake:41 (add_library):
  Cannot find source file:

    dependencies/nanopb/pb_common.c
What I have to do ?

**Comment by MrAnno** [comment]
Just for the record:
nanopb is one of Criterion's dependencies, it has to be cloned as well:
```
git submodule update --init --recursive
```

or you can just clone the repository recursively:
```sh
# git clone --recursive https://github.com/Snaipe/Criterion
git clone --recurse-submodule https://github.com/Snaipe/Criterion
```
