### ISSUE TITLE
[SOLVED] Make malloc fail intentionnally for a specific test

### ISSUE THREAD

**Issue by fox-tek** [Snaipe/Criterion#277]
Hey, we've been discussing this issue with some fellow students recently.
In my dev school, doing unit tests is mandatory, and Criterion is the lib we use for C. Part of our grades depends on coverage.
Thing is, when we use malloc, we have to protect our function from its failure and here comes the issue : 
We never get 100% coverage when we test malloc failures, as we can't find a way to make it return NULL for one specific test. Sure we can check if the program ended well by defining `malloc(x)` to `NULL` manually, but in the end we have to take the `#define` off so the program runs normally.

Is there a way to make malloc fail on demand that is not just temporarily breaking the program ?

**Comment by Snaipe** [comment]
Have a look at [Mimick](https://github.com/diacritic/Mimick), there's a [sample](https://github.com/diacritic/Mimick/blob/master/sample/strdup/test.c#L31) that does just that. Note that you might have to disable the malloc mock before calling cr_assert.

**Comment by fox-tek** [comment]
Interesting, thanks. I'll come back if I encounter any issue. Also wow you're fast.

**Comment by Snaipe** [comment]
Alternatively, if you're using GCC/Clang, you can tell ld to wrap malloc with a custom function:

```c
static int override_malloc;

void *__real_malloc(size_t);
void *__wrap_malloc(size_t s) {
    if (override_malloc) {
        errno = ENOMEM;
        return NULL;
    }
    return __real_malloc(s);
}

Test(foo, bar) {
    override_malloc = 1;
    // do your function calls
    override_malloc = 0;

    cr_assert(...);
}
```

and compile with `-Wl,--wrap=malloc`. Of course, it doesn't have all of the scoping & validation features that Mimick has, but it's a good alternative if you don't want an additional dependency or an overkill solution.

**Comment by fox-tek** [comment]
This last one seems more adequate as we have restrictions on libs and functions we can use (we had to totally re-code printf for example, and we can use none but ours in most projects).

**Comment by kugel-** [comment]
FWIW, normally you can override library functions simply by implementing them in the main executable. The linker will not search library for undefined symbols if they already appear in main program. Linked libraries will also call this implementation (including the library which originally implements the function since the dispatch is via GOT with shared libraries, due to -fPIC).

`void *malloc(void) { return NULL; }`

If you must call into the real function additionally use @Snaipe method.

**Comment by kugel-** [comment]
The main executable being the unit test program here.

**Comment by fox-tek** [comment]
@kugel- The point here is to have a unit test file in which I first test a function's behaviour in the case malloc would fail and then testing the function with a working malloc. As I said in the original post, re-defining malloc is just a temporary thing that I'd have to do manually and then remove and this is not really helpful if I have to do this for, say, 10 functions, one after the other.
All I want is a pretty Criterion executable output showing 100% passed tests, malloc working and failing all together ; paired with a lovely 100% coverage when using gcovr. It's so satisfying. 🤤
