### ISSUE TITLE
RFE: Display test name on crash during startup or teardown routines

### ISSUE THREAD

**Issue by jswaro** [Snaipe/Criterion#28]
If possible, could Criterion print the name of the test on crash during start up or teardown. When debugging regressions, it can become painful to figure out which test actually crashed when it is a small subset of the tests that have regressed.

**Comment by Snaipe** [comment]
@jswaro After thinking about it, I might have got your issue wrong; Is adding the name of the test in the warning message occuring when it crashes during its setup or teardown what you had in mind ?

**Comment by jswaro** [comment]
Looking at the commit you referenced, that looks like exactly what I was asking for.

**Comment by Snaipe** [comment]
Very well then; closing this again.
