### ISSUE TITLE
"Assertion failed: string is empty" on non-empty string

### ISSUE THREAD

**Issue by JeanMarcZimmer** [Snaipe/Criterion#283]
I'm testing a C++ project. To test my string, I pay attention to add the `.c_str()` function.

I created a class that returns an std::string.
I'm trying to make sure it is not empty, and the `cr_assert_str_not_empty()` or `cr_expect_str_not_empty()` functions return an error, telling the string is empty.

I can even output the string using `printf()`.
Other methods, like using a temporary `std::string` or `cr_assert(str != "")` work as expected.

The string is created from a file in a class using `std::getline();`
it is returned as-is, not using reference or pointer.

Sorry, I can't bring much details, I'm a novice programmer.

**Comment by JeanMarcZimmer** [comment]
Why did I have to read the whole documentation 3 times to find that C++ isn't supported and leads to undefined behavior ???

**Comment by kugel-** [comment]
C++ is supported generally but I believe the cr_assert_str family expects C strings
