### ISSUE TITLE
Building without internet?

### ISSUE THREAD

**Issue by athei** [Snaipe/Criterion#284]
Is there a way to build Criterion without internet during build step?

The cloned version does download during build. 
The tarball version just fails:
```
CMake Deprecation Warning at CMakeLists.txt:15 (cmake_policy):
  The OLD behavior for policy CMP0054 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Updating submodules to their latest/fixed versions
-- (this can take a while, please be patient)
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- Could NOT find CSPTR (missing: CSPTR_LIBRARY CSPTR_INCLUDE_DIR) 
-- Could NOT find DYNCALL (missing: DYNCALL_LIBRARY DYNCALL_INCLUDE_DIR) 
-- Could NOT find NANOMSG (missing: NANOMSG_LIBRARY NANOMSG_INCLUDE_DIR) 
-- Could NOT find BOXFORT (missing: BOXFORT_LIBRARY BOXFORT_INCLUDE_DIR) 
-- Configuring done
CMake Error at .cmake/Modules/PackageUtils.cmake:41 (add_library):
  Cannot find source file:

    dependencies/nanopb/pb_common.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  CMakeLists.txt:127 (cr_add_library)


CMake Error at .cmake/Modules/PackageUtils.cmake:41 (add_library):
  No SOURCES given to target: criterion
Call Stack (most recent call first):
  CMakeLists.txt:127 (cr_add_library)
```

**Comment by kugel-** [comment]
Do you clone with --recursive-submodules?

**Comment by athei** [comment]
Yes. The problem are not the dependencies which are included as submodules. There are additional dependencies which are downloaded during the build which are not submodules.

**Comment by ginomcevoy** [comment]
Here is what I did, hopefully it will be useful to you.

1. Download the dependencies in a machine with internet, get the right commit (from CMakeLists.txt) and place them in the dependencies directory. For example for libcsptr:

```
git clone https://github.com/Snaipe/libcsptr
cd libcsptr
git checkout 0d52904
cd ..
mv libcsptr $CRITERION_HOME/dependencies
```

You can remove .git if you want. Do the same for all of these:

dependencies/libcsptr
"https://github.com/Snaipe/libcsptr#0d52904"

dependencies/dyncall
"https://github.com/Snaipe/dyncall#51e79a8"

dependencies/nanomsg
"https://github.com/nanomsg/nanomsg.git#7e12a20"

dependencies/boxfort
"https://github.com/diacritic/BoxFort.git#926bd4c

dependencies/git2
"https://github.com/libgit2/libgit2#v0.25.1"

dependencies/wingetopt
"https://github.com/alex85k/wingetopt.git#76a5d1a"

2. Move the code to the machine without internet.
3. Follow standard procedure:
```
cd $CRITERION_HOME
mkdir build && cd build
cmake ..
cmake --build .
```
4. git2 does not like to be in dependencies so the build will fail (I tried in the main directory, also did not work) Here is a workaround, needs to be executed after trying the build once:
```
cp -rf ../dependencies/git2 git2-build/src/git2
touch git2-build/src/git2-stamp/git2-gitclone-lastrun.txt
sed -i '1 i\return()' git2-build/tmp/git2-gitupdate.cmake
```
5. Now you should be able to build again:
```
cmake --build .
```

**Comment by Snaipe** [comment]
I think we need to mention in the docs to build and/or install all of the aforementioned dependencies to compile Criterion. The static build of these dependencies is pretty much a stopgap for when these deps are not available on the system, but the truth is that I have less and less interest in doing the download-if-not-found fallback logic here.

I'll see how this shapes up with meson. For now, all releases bundle a source tarball that can be used to build without the internet. In fact, it's a requirement for .deb builds on launchpad, so it has been incorporated for a while now.

**Comment by MrAnno** [comment]
I believe this has been fixed by the new Meson build. Internet is still required when building directly from the git repo, but using the source tarball that will be attached to the upcoming release should work without network access.

This can even be enforced with the "--wrap-mode=nodownload" option of Meson.

Please reopen if using the tarball is not suitable for you or if you experience any further issues with it.
