### ISSUE TITLE
Install criterion in gitlab ci

### ISSUE THREAD

**Issue by cedricfarinazzo** [Snaipe/Criterion#285]
Hey!

I would like to install criterion on gitlab ci.

First, I had some problems with your GPG key.
So I manually installed the GPG key as you said in this issue #267 

No problem to apt-get update.
But when I try to install criterion-dev as in the README.md file, I get this error
```
E: Unable to locate package criterion-dev
```
Can you help me solve this problem?

Thanks.

**Comment by Snaipe** [comment]
Sorry about the delay. Is the problem still relevant?

**Comment by cedricfarinazzo** [comment]
The problem is solved.
I finally decided to create and use a custom dockerfile image on which I installed criterion from the aur.
Thanks again for this awesome framework!
