### ISSUE TITLE
Linking does not work using CMake

### ISSUE THREAD

**Issue by matthaeusheer** [Snaipe/Criterion#290]
I encountered linking criterion when building using CMake. I can succesfully link criterion to my application when I compile using g++ -lcriterion (and so on...). However, when I use CMake I get the error ```fatal error: 'criterion/criterion.h' file not found```. This is the same for when I try to run the example on https://github.com/thombashi/CriterionSample.  
```
[ 10%] Building C object test_abnormal/CMakeFiles/test_abnormal.dir/test_exit.c.o
/Users/matthausheer/university/howtowritefastnumericalcode/CriterionSample/test_abnormal/test_exit.c:1:10: fatal error: 'criterion/criterion.h' file not
      found
#include <criterion/criterion.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [test_abnormal/CMakeFiles/test_abnormal.dir/test_exit.c.o] Error 1
make[1]: *** [test_abnormal/CMakeFiles/test_abnormal.dir/all] Error 2
```

I installed criterion using ```brew install snaipe/soft/criterion```.

The CMakeLists.txt in my own project looks kinda like this. Just to show that I tried to link criterion to my test target.
```
other CMake stuff...

add_executable(test
        (src/some_files.cpp ...)
        tests/test.cpp)

target_link_libraries(test
        criterion)
```

Any ideas? Help much appreciated.

**Comment by fox-tek** [comment]
Maybe try manually adding criterion's include directory to your CMakeLists' include_directories() ?

**Comment by am11** [comment]
Try locating where `criterion.h` is on the system:

```sh
find / -name criterion.h
# or
sudo find / -name criterion.h
```

suppose it was at `/home/me/my-includes/criterion/criterion.h`.

```sh
git clone https://github.com/thombashi/CriterionSample
cd CriterionSample

cmake .
make             # << here we get the error with squigglies
# ...
# #include <criterion/criterion.h>
#           ^~~~~~~~~~~~~~~~~~~~~~~
# ...

export CFLAGS=-isystem\ /home/me/my-includes           # << this fixes the issue

# retry
git clean -xdf
cmake .
make          # succeeds
```

**Comment by MrAnno** [comment]
If you don't want to do it manually, `snaipe/soft/criterion` installs a pkg-config file that can be used in CMake:

```CMake
find_package(PkgConfig REQUIRED)
pkg_check_modules(CRITERION REQUIRED criterion)
...
target_link_libraries(test PRIVATE ${CRITERION_LIBRARIES})
target_include_directories(test PRIVATE ${CRITERION_INCLUDE_DIRS})
```

**Comment by matthaeusheer** [comment]
@MrAnno That looks like a decent approach. However, following this, I get
```
[100%] Linking CXX executable test
ld: library not found for -lcriterion
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [test] Error 1
make[2]: *** [CMakeFiles/test.dir/all] Error 2
make[1]: *** [CMakeFiles/test.dir/rule] Error 2
make: *** [test] Error 2
```
The header file not found error seems to have disappeared though.
I have pkg-config installed.
```find / -name criterion.h``` gives me: /usr/local/Cellar/criterion/2.3.3/include/criterion/criterion.h

Appreciate the support!

**Comment by fox-tek** [comment]
Well now the problem surely comes from your link directories setup.

**Comment by MrAnno** [comment]
This should do the trick:
```diff
-target_link_libraries(test PRIVATE ${CRITERION_LIBRARIES})
+target_link_libraries(test PRIVATE ${CRITERION_LINK_LIBRARIES})
```

**Comment by matthaeusheer** [comment]
That did it indeed, thanks a lot!

**Comment by MrAnno** [comment]
Oh sorry, I haven't noticed that there is actually an official `FindCriterion` module here:
https://github.com/Snaipe/Criterion/blob/bleeding/dev/FindCriterion.cmake

You can create a folder named `cmake/Modules/` under your project root and put that file into the `Modules` directory.

```CMake
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${PROJECT_SOURCE_DIR}/cmake/Modules/")

find_package(Criterion REQUIRED)
target_link_libraries(test PRIVATE ${CRITERION_LIBRARIES})
target_include_directories(test PRIVATE ${CRITERION_INCLUDE_DIRS})
```

This is way better than using the "raw" `pkg_check_modules` command.

**Comment by Wes974** [comment]
Hi, I tried following both methods on my Mac too, but I can't seem to make it work, it still doesn't find criterion. I also installed criterion with `brew install snaipe/soft/criterion`. Does anyone have an idea ?

**Comment by MrAnno** [comment]
Looking at the above sample repository, it seems this issue has been resolved.

**Comment by Snaipe** [comment]
> Looking at the above sample repository, it seems this issue has been resolved.

Thanks for checking, closing this.
