### ISSUE TITLE
clang link time optimization removes test

### ISSUE THREAD

**Issue by athei** [Snaipe/Criterion#291]
When I build my project with clang and enable link time optimization all criterion test executeables are "empty":
`[====] Synthesis: Tested: 0 | Passing: 0 | Failing: 0 | Crashing: 0`

```
clang version 7.0.0-3 (tags/RELEASE_700/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
This does not happen when lto is disabled nor when I use lto with gcc. 

I guess the dead code elimination removes the test.

**Comment by Snaipe** [comment]
Right, that makes sense since the set of used functions is known at compile time for executables.

I think tagging __attribute__((used)) on test functions would fix the issue.

**Comment by Snaipe** [comment]
I'm not able (no longer able?) to reproduce this with the tip of bleeding. I'm assuming this is no longer an issue. Feel free to reopen or make a new one if this is still the case.
