### ISSUE TITLE
cr_assert_float_eq does not work with inf

### ISSUE THREAD

**Issue by zhihaoy** [Snaipe/Criterion#293]
Because `cr_assert_float_eq_op_` is implemented as
```
(Expected) - (Actual) <= (Epsilon) && (Actual) - (Expected) <= (Epsilon)
```
But then Expected = inf and Actual = inf, since inf - inf is UB (usually nan), this can never be true.  On the other hand, inf == inf and inf <= inf, so it looks like a bug unless intentional.

**Comment by Snaipe** [comment]
Right, this is an unfortunate side-effect of comparing with epsilons; you'd technically want to check `isinf(float)` if you want to be portable.

Maybe this needs to be mentioned in the documentation.
