### ISSUE TITLE
Assertions in documentation, but not defined

### ISSUE THREAD

**Issue by 4lph4-Ph4un** [Snaipe/Criterion#298]
Hi!

Tried to do some file assertions such as these: https://criterion.readthedocs.io/en/master/assert.html#file-assertions

Neither the assert or expect seems to be found when linked:

```
main.o : error LNK2019: unresolved external symbol cr_assert_file_contents_eq_str referenced in function testing_files_file_content_to_string_equality_impl
main.o : error LNK2019: unresolved external symbol cr_expect_file_contents_eq_str referenced in function testing_files_file_content_to_string_equality_impl
```

Other assertions seem to work fine.

**Comment by Snaipe** [comment]
Are you using `bleeding`? the bleeding branch is currently reimplementing its assertion API, so some things might be broken. I'd recommend using a stable release.

**Comment by 4lph4-Ph4un** [comment]
Ah! Blimey, that's it! I'll switch to stable :)
