### ISSUE TITLE
How do you install this on fedora?

### ISSUE THREAD

**Issue by GAO23** [Snaipe/Criterion#299]
How do you install this on fedora 30?

Why is apt the only package manager supported?

compiling this from source using cmake and make runs into dependency hell. 

I need this for my college computer science class and I have no desire whatsoever to switch to Ubuntu.

**Comment by Snaipe** [comment]
I think @samber prepackaged criterion for fedora here: https://github.com/samber/criterion-rpm-package -- maybe give it a try?

Other than that, if you'd like to see the library on fedora itself, please talk to distro maintainers to get this in; maintaining releases for each distribution is not something I can do with limited time these days. :)

**Comment by GAO23** [comment]
awesome. that will do.
