### ISSUE TITLE
gcc optimization level

### ISSUE THREAD

**Issue by ntuDerekWang** [Snaipe/Criterion#305]
Hello, 

I am wondering what gcc optimization for the library libcriterion.dll?
If I want to do gcc -O0 for libcriterion.dll, how can I do?
Thank you.

Best,
Derek

**Comment by Snaipe** [comment]
The simplest way is to pass `-DCMAKE_BUILD_TYPE=Debug` to cmake. If you don't want debug symbols with it I believe you can override `CMAKE_C_FLAGS_DEBUG` to only use -O0.

**Comment by ntuDerekWang** [comment]
Thank you :)
