### ISSUE TITLE
Test with read on stdin don't receive an EOF signal with CTLD-D in the terminal

### ISSUE THREAD

**Issue by P-NA-J** [Snaipe/Criterion#306]
Hello, 

just discovering the library, and I didn't find anything about it in the doc. I was trying a fonction that read on stdin and I tried to send an EOF signal with the command CTLD-D. When I tried on main, it's working perfetly but when I do the exact same thing in a Test, it write a '^D' and don't stop reading on stdin.

Should I use a special macro for it ? 

Thanks in advance

My code : 
```
Test(instruction_recovering, test1)
{
	char **array;
	int fd;

	fd = 0;
	array = instruction_recovering(fd);
/*	cr_expect_str_eq(array[0], "pa", RED "ERROR_FAILURE '+10'" DEFAULT);
	cr_expect_str_eq(array[1], "pb", RED "ERROR_FAILURE '+10'" DEFAULT);
	cr_expect_str_eq(array[2], "sa", RED "ERROR_FAILURE '+10'" DEFAULT);
	cr_expect_str_eq(array[3], "sb", RED "ERROR_FAILURE '+10'" DEFAULT);
	cr_expect_str_eq(array[4], "ss", RED "ERROR_FAILURE '+10'" DEFAULT);
	cr_expect_str_eq(array[5], "rr", RED "ERROR_FAILURE '+10'" DEFAULT);
	cr_expect_str_eq(array[6], "rra", RED "ERROR_FAILURE '+10'" DEFAULT);
	cr_expect_str_eq(array[7], "rrb", RED "ERROR_FAILURE '+10'" DEFAULT);
	cr_expect_str_eq(array[8], "rrr", RED "ERROR_FAILURE '+10'" DEFAULT);
*/}
```
```
char		**instruction_recovering(int fd)
{
	char	*tmp;
	char	**array;
	t_list	*list;

	tmp = NULL;
	list = NULL;
	array = NULL;
	while (get_next_line(fd, &tmp) > 0)
		ft_lst_push_back(&list, tmp, ft_strlen(tmp));
	ft_print_lst(list);
	return (array);
}

```
```
int main()
{
	char **array;
	int fd;

	fd = 0;
	array = instruction_recovering(fd);
	return (0);
}
```

**Comment by Snaipe** [comment]
Use `cr_get_redirected_stdin()`. Here's an [example](https://github.com/Snaipe/Criterion/blob/a64b8600a9236a4cc8204353b19ce233e294c29b/samples/redirect.c#L49).

Ctrl-D on your tty has the effect of closing stdin, no ^D is really passed to your program. `cr_get_redirected_stdin()` will give you a stream that you can write to, and anything written to it will become available for reading on fd 0.

**Comment by P-NA-J** [comment]
Thanks a lot !
