### ISSUE TITLE
Available to build Criterion lib as static library?

### ISSUE THREAD

**Issue by ntuDerekWang** [Snaipe/Criterion#307]
Hello,

I saw in CMakeList.txt the Criterion was built as shared library. Can I build it as static library? 
If i build it as static library, is there any possible issue?
BTW I use it in Mingw64 under Windows.
Thank you!

**Comment by Snaipe** [comment]
There's nothing really preventing you from trying a static build, but do mind that only the shared lib build are supported/tested/reliable. It's probably working fine, but I'm not 100% sure that something won't go wrong with either BoxFort or some of the low-level stuff we have to deal with to sandbox tests.

**Comment by ntuDerekWang** [comment]
Got you! Thanks for your prompt reply!
