### ISSUE TITLE
Issue building Criterion on FreeBSD

### ISSUE THREAD

**Issue by rmzelnick** [Snaipe/Criterion#309]
I'm trying to build Criterion on FreeBSD, I have cloned the repository and followed the instructions from this page https://criterion.readthedocs.io/en/master/setup.html however whenever I try running `cmake --build .` I get the following error

```
rzelnick@localhost:~/Documents/Criterion/build % cmake --build .
[  2%] Built target boxfort-dependency
[  4%] Built target git2-dependency
[  4%] Built target dyncall_s-dependency
[  7%] Built target nanomsg-dependency
[  9%] Generating csptr-dep
[ 20%] Performing update step for 'csptr'
[ 40%] Performing configure step for 'csptr'
-- Checking for one of the modules 'check'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rzelnick/Documents/Criterion/build/csptr
[ 40%] Performing build step for 'csptr'
[ 50%] Building C object CMakeFiles/csptr.dir/src/mman.c.o
cc: error: -Wl,--exclude-libs=ALL: 'linker' input unused [-Werror,-Wunused-command-line-argument]
*** Error code 1

Stop.
make[9]: stopped in /usr/home/rzelnick/Documents/Criterion/build/csptr
*** Error code 1

Stop.
make[8]: stopped in /usr/home/rzelnick/Documents/Criterion/build/csptr
*** Error code 1

Stop.
make[7]: stopped in /usr/home/rzelnick/Documents/Criterion/build/csptr
*** Error code 1

Stop.
make[6]: stopped in /usr/home/rzelnick/Documents/Criterion/build
*** Error code 1

Stop.
make[5]: stopped in /usr/home/rzelnick/Documents/Criterion/build
*** Error code 1

Stop.
make[4]: stopped in /usr/home/rzelnick/Documents/Criterion/build
*** Error code 1

Stop.
make[3]: stopped in /usr/home/rzelnick/Documents/Criterion/build
*** Error code 1

Stop.
make[2]: stopped in /usr/home/rzelnick/Documents/Criterion/build
*** Error code 1

Stop.
make[1]: stopped in /usr/home/rzelnick/Documents/Criterion/build
*** Error code 1

Stop.
make: stopped in /usr/home/rzelnick/Documents/Criterion/build
```

**Comment by Snaipe** [comment]
I'm not sure I can really help here, because we lack a proper CI environment for testing on FreeBSD. It's [in the works though](https://github.com/Snaipe/Criterion/pull/287).

I think you can get some more information on which command is failing by running `make VERBOSE=1`. I'm assuming `cc` is `gcc`, what version is it?

**Comment by am11** [comment]
If you like to try out FreeBSD CI in your fork, you can fetch my branch and use [these steps](https://github.com/Snaipe/Criterion/pull/287#discussion_r255316878) to set up. We can also rev FreeBSD version to 12 in first line of YAML. cbsd is used for i386 leg (which probably make the yaml look bit loaded/noisy). To get the binaries out from build slave to your fork's github release, `git tag blah && git push --tags`.

**Comment by rmzelnick** [comment]
> I'm not sure I can really help here, because we lack a proper CI environment for testing on FreeBSD. It's [in the works though](https://github.com/Snaipe/Criterion/pull/287).
> 
> I think you can get some more information on which command is failing by running `make VERBOSE=1`. I'm assuming `cc` is `gcc`, what version is it?

I've just realized my `cc` is `clang`, so now I have run the following,

Please note that I'm using GCC v8.3.0 and they're specified in when calling `cmake` and `make`.

```
rzelnick@localhost:~/Documents/Criterion/build % cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CC_COMPILER=gcc ..
CMake Deprecation Warning at CMakeLists.txt:15 (cmake_policy):
  The OLD behavior for policy CMP0054 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Could NOT find CSPTR (missing: CSPTR_LIBRARY CSPTR_INCLUDE_DIR) 
-- Could NOT find DYNCALL (missing: DYNCALL_LIBRARY DYNCALL_INCLUDE_DIR) 
-- Could NOT find NANOMSG (missing: NANOMSG_LIBRARY NANOMSG_INCLUDE_DIR) 
-- Could NOT find BOXFORT (missing: BOXFORT_LIBRARY BOXFORT_INCLUDE_DIR) 
-- Could NOT find libgit2 (missing: LIBGIT2_LIBRARIES LIBGIT2_INCLUDE_DIR) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rzelnick/Documents/Criterion/build
```

And then for building with CMake,

```
rzelnick@localhost:~/Documents/Criterion/build % cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CC_COMPILER=gcc --build .
CMake Deprecation Warning at CMakeLists.txt:15 (cmake_policy):
  The OLD behavior for policy CMP0054 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Could NOT find CSPTR (missing: CSPTR_LIBRARY CSPTR_INCLUDE_DIR) 
-- Could NOT find DYNCALL (missing: DYNCALL_LIBRARY DYNCALL_INCLUDE_DIR) 
-- Could NOT find NANOMSG (missing: NANOMSG_LIBRARY NANOMSG_INCLUDE_DIR) 
-- Could NOT find BOXFORT (missing: BOXFORT_LIBRARY BOXFORT_INCLUDE_DIR) 
-- Could NOT find libgit2 (missing: LIBGIT2_LIBRARIES LIBGIT2_INCLUDE_DIR) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rzelnick/Documents/Criterion/build
```

Now when I try to run make,

```
rzelnick@localhost:~/Documents/Criterion/build % make CC=gcc CXX=g++ VERBOSE=1
/usr/local/bin/cmake -S/home/rzelnick/Documents/Criterion -B/home/rzelnick/Documents/Criterion/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/bin/cmake -E cmake_progress_start /home/rzelnick/Documents/Criterion/build/CMakeFiles /home/rzelnick/Documents/Criterion/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make -f CMakeFiles/boxfort-dependency.dir/build.make CMakeFiles/boxfort-dependency.dir/depend
cd /home/rzelnick/Documents/Criterion/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build/CMakeFiles/boxfort-dependency.dir/DependInfo.cmake --color=
make -f CMakeFiles/boxfort-dependency.dir/build.make CMakeFiles/boxfort-dependency.dir/build
[  2%] Built target boxfort-dependency
make -f CMakeFiles/git2-dependency.dir/build.make CMakeFiles/git2-dependency.dir/depend
cd /home/rzelnick/Documents/Criterion/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build/CMakeFiles/git2-dependency.dir/DependInfo.cmake --color=
make -f CMakeFiles/git2-dependency.dir/build.make CMakeFiles/git2-dependency.dir/build
[  4%] Built target git2-dependency
make -f CMakeFiles/dyncall_s-dependency.dir/build.make CMakeFiles/dyncall_s-dependency.dir/depend
cd /home/rzelnick/Documents/Criterion/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build/CMakeFiles/dyncall_s-dependency.dir/DependInfo.cmake --color=
make -f CMakeFiles/dyncall_s-dependency.dir/build.make CMakeFiles/dyncall_s-dependency.dir/build
[  4%] Built target dyncall_s-dependency
make -f CMakeFiles/nanomsg-dependency.dir/build.make CMakeFiles/nanomsg-dependency.dir/depend
cd /home/rzelnick/Documents/Criterion/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build/CMakeFiles/nanomsg-dependency.dir/DependInfo.cmake --color=
make -f CMakeFiles/nanomsg-dependency.dir/build.make CMakeFiles/nanomsg-dependency.dir/build
[  7%] Built target nanomsg-dependency
make -f CMakeFiles/csptr-dependency.dir/build.make CMakeFiles/csptr-dependency.dir/depend
cd /home/rzelnick/Documents/Criterion/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build/CMakeFiles/csptr-dependency.dir/DependInfo.cmake --color=
make -f CMakeFiles/csptr-dependency.dir/build.make CMakeFiles/csptr-dependency.dir/build
[  9%] Generating csptr-dep
/usr/local/bin/cmake --build /home/rzelnick/Documents/Criterion/build --target csptr-bootstrap
/usr/local/bin/cmake -S/home/rzelnick/Documents/Criterion -B/home/rzelnick/Documents/Criterion/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/make -f CMakeFiles/Makefile2 csptr-bootstrap
/usr/local/bin/cmake -S/home/rzelnick/Documents/Criterion -B/home/rzelnick/Documents/Criterion/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/bin/cmake -E cmake_progress_start /home/rzelnick/Documents/Criterion/build/CMakeFiles 5
/usr/bin/make -f CMakeFiles/Makefile2 CMakeFiles/csptr-bootstrap.dir/all
/usr/bin/make -f CMakeFiles/csptr-bootstrap.dir/build.make CMakeFiles/csptr-bootstrap.dir/depend
cd /home/rzelnick/Documents/Criterion/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build/CMakeFiles/csptr-bootstrap.dir/DependInfo.cmake --color=
/usr/bin/make -f CMakeFiles/csptr-bootstrap.dir/build.make CMakeFiles/csptr-bootstrap.dir/build
[ 20%] Performing update step for 'csptr'
cd /home/rzelnick/Documents/Criterion/build/csptr-build/src/csptr && /usr/local/bin/cmake -P /home/rzelnick/Documents/Criterion/build/csptr-build/tmp/csptr-gitupdate.cmake
[ 40%] Performing configure step for 'csptr'
cd /home/rzelnick/Documents/Criterion/build/csptr && /usr/local/bin/cmake /home/rzelnick/Documents/Criterion/build/csptr-build/src/csptr -DCMAKE_INSTALL_PREFIX=/home/rzelnick/Documents/Criterion/build/external -DCMAKE_BUILD_TYPE= -G "Unix Makefiles" -DLIBCSPTR_TESTS=OFF "-DCMAKE_C_FLAGS= -Wl,--exclude-libs=ALL -fPIC -fvisibility=hidden"
Re-run cmake no build system arguments
-- Checking for one of the modules 'check'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rzelnick/Documents/Criterion/build/csptr
cd /home/rzelnick/Documents/Criterion/build/csptr && /usr/local/bin/cmake -E touch /home/rzelnick/Documents/Criterion/build/csptr-build/src/csptr-stamp/csptr-configure
[ 40%] Performing build step for 'csptr'
cd /home/rzelnick/Documents/Criterion/build/csptr && /usr/local/bin/cmake --build /home/rzelnick/Documents/Criterion/build/csptr
/usr/local/bin/cmake -S/home/rzelnick/Documents/Criterion/build/csptr-build/src/csptr -B/home/rzelnick/Documents/Criterion/build/csptr --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/bin/cmake -E cmake_progress_start /home/rzelnick/Documents/Criterion/build/csptr/CMakeFiles /home/rzelnick/Documents/Criterion/build/csptr/CMakeFiles/progress.marks
/usr/bin/make -f CMakeFiles/Makefile2 all
/usr/bin/make -f CMakeFiles/csptr.dir/build.make CMakeFiles/csptr.dir/depend
cd /home/rzelnick/Documents/Criterion/build/csptr && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/rzelnick/Documents/Criterion/build/csptr-build/src/csptr /home/rzelnick/Documents/Criterion/build/csptr-build/src/csptr /home/rzelnick/Documents/Criterion/build/csptr /home/rzelnick/Documents/Criterion/build/csptr /home/rzelnick/Documents/Criterion/build/csptr/CMakeFiles/csptr.dir/DependInfo.cmake --color=
/usr/bin/make -f CMakeFiles/csptr.dir/build.make CMakeFiles/csptr.dir/build
[ 50%] Building C object CMakeFiles/csptr.dir/src/mman.c.o
/usr/bin/cc  -I/home/rzelnick/Documents/Criterion/build/csptr-build/src/csptr/include/csptr -I/home/rzelnick/Documents/Criterion/build/csptr-build/src/csptr/src -Wl,--exclude-libs=ALL -fPIC -fvisibility=hidden -Wall -Wextra -Werror -g -std=gnu99 -Wno-unused-result -Wno-missing-field-initializers   -fPIC -o CMakeFiles/csptr.dir/src/mman.c.o   -c /home/rzelnick/Documents/Criterion/build/csptr-build/src/csptr/src/mman.c
cc: error: -Wl,--exclude-libs=ALL: 'linker' input unused [-Werror,-Wunused-command-line-argument]
*** Error code 1

Stop.
make[9]: stopped in /usr/home/rzelnick/Documents/Criterion/build/csptr
*** Error code 1

Stop.
make[8]: stopped in /usr/home/rzelnick/Documents/Criterion/build/csptr
*** Error code 1

Stop.
make[7]: stopped in /usr/home/rzelnick/Documents/Criterion/build/csptr
*** Error code 1

Stop.
make[6]: stopped in /usr/home/rzelnick/Documents/Criterion/build
*** Error code 1

Stop.
make[5]: stopped in /usr/home/rzelnick/Documents/Criterion/build
*** Error code 1

Stop.
make[4]: stopped in /usr/home/rzelnick/Documents/Criterion/build
*** Error code 1

Stop.
make[3]: stopped in /usr/home/rzelnick/Documents/Criterion/build
*** Error code 1

Stop.
make[2]: stopped in /usr/home/rzelnick/Documents/Criterion/build
*** Error code 1

Stop.
make[1]: stopped in /usr/home/rzelnick/Documents/Criterion/build
*** Error code 1

Stop.
make: stopped in /usr/home/rzelnick/Documents/Criterion/build
```

**Comment by rmzelnick** [comment]
@am11

> If you like to try out FreeBSD CI in your fork, you can fetch my branch and use [these steps](https://github.com/Snaipe/Criterion/pull/287#discussion_r255316878) to set up. We can also rev FreeBSD version to 12 in first line of YAML. cbsd is used for i386 leg (which probably make the yaml look bit loaded/noisy). To get the binaries out from build slave to your fork's github release, `git tag blah && git push --tags`.

**Comment by rmzelnick** [comment]
I was able to fix it by re-cloning with

`$ git --recurse-submodules https://github.com/Snaipe/Criterion.git`

Instead of,

`$ git --recursive https://github.com/Snaipe/Criterion.git`

As suggested by this page https://criterion.readthedocs.io/en/master/setup.html

**Comment by rmzelnick** [comment]
> If you like to try out FreeBSD CI in your fork, you can fetch my branch and use [these steps](https://github.com/Snaipe/Criterion/pull/287#discussion_r255316878) to set up. We can also rev FreeBSD version to 12 in first line of YAML. cbsd is used for i386 leg (which probably make the yaml look bit loaded/noisy). To get the binaries out from build slave to your fork's github release, `git tag blah && git push --tags`.

It won't be necessary since I've managed to install Criterion, however it would be interesting to see a port in the future!

**Comment by rmzelnick** [comment]
> @Snaipe
> 
> > I'm not sure I can really help here, because we lack a proper CI environment for testing on FreeBSD. It's [in the works though](https://github.com/Snaipe/Criterion/pull/287).
> > I think you can get some more information on which command is failing by running `make VERBOSE=1`. I'm assuming `cc` is `gcc`, what version is it?
> 
> I've just realized my `cc` is `clang`, so now I have run the following,
> 
> Please note that I'm using GCC v8.3.0 and they're specified in when calling `cmake` and `make`.
> 
> ```
> rzelnick@localhost:~/Documents/Criterion/build % cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CC_COMPILER=gcc ..
> CMake Deprecation Warning at CMakeLists.txt:15 (cmake_policy):
>   The OLD behavior for policy CMP0054 will be removed from a future version
>   of CMake.
> 
>   The cmake-policies(7) manual explains that the OLD behaviors of all
>   policies are deprecated and that a policy should be set to OLD only under
>   specific short-term circumstances.  Projects should be ported to the NEW
>   behavior and not rely on setting a policy to OLD.
> 
> 
> -- Could NOT find CSPTR (missing: CSPTR_LIBRARY CSPTR_INCLUDE_DIR) 
> -- Could NOT find DYNCALL (missing: DYNCALL_LIBRARY DYNCALL_INCLUDE_DIR) 
> -- Could NOT find NANOMSG (missing: NANOMSG_LIBRARY NANOMSG_INCLUDE_DIR) 
> -- Could NOT find BOXFORT (missing: BOXFORT_LIBRARY BOXFORT_INCLUDE_DIR) 
> -- Could NOT find libgit2 (missing: LIBGIT2_LIBRARIES LIBGIT2_INCLUDE_DIR) 
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/rzelnick/Documents/Criterion/build
> ```
> 
> And then for building with CMake,
> 
> ```
> rzelnick@localhost:~/Documents/Criterion/build % cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CC_COMPILER=gcc --build .
> CMake Deprecation Warning at CMakeLists.txt:15 (cmake_policy):
>   The OLD behavior for policy CMP0054 will be removed from a future version
>   of CMake.
> 
>   The cmake-policies(7) manual explains that the OLD behaviors of all
>   policies are deprecated and that a policy should be set to OLD only under
>   specific short-term circumstances.  Projects should be ported to the NEW
>   behavior and not rely on setting a policy to OLD.
> 
> 
> -- Could NOT find CSPTR (missing: CSPTR_LIBRARY CSPTR_INCLUDE_DIR) 
> -- Could NOT find DYNCALL (missing: DYNCALL_LIBRARY DYNCALL_INCLUDE_DIR) 
> -- Could NOT find NANOMSG (missing: NANOMSG_LIBRARY NANOMSG_INCLUDE_DIR) 
> -- Could NOT find BOXFORT (missing: BOXFORT_LIBRARY BOXFORT_INCLUDE_DIR) 
> -- Could NOT find libgit2 (missing: LIBGIT2_LIBRARIES LIBGIT2_INCLUDE_DIR) 
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/rzelnick/Documents/Criterion/build
> ```
> 
> Now when I try to run make,
> 
> ```
> rzelnick@localhost:~/Documents/Criterion/build % make CC=gcc CXX=g++ VERBOSE=1
> /usr/local/bin/cmake -S/home/rzelnick/Documents/Criterion -B/home/rzelnick/Documents/Criterion/build --check-build-system CMakeFiles/Makefile.cmake 0
> /usr/local/bin/cmake -E cmake_progress_start /home/rzelnick/Documents/Criterion/build/CMakeFiles /home/rzelnick/Documents/Criterion/build/CMakeFiles/progress.marks
> make -f CMakeFiles/Makefile2 all
> make -f CMakeFiles/boxfort-dependency.dir/build.make CMakeFiles/boxfort-dependency.dir/depend
> cd /home/rzelnick/Documents/Criterion/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build/CMakeFiles/boxfort-dependency.dir/DependInfo.cmake --color=
> make -f CMakeFiles/boxfort-dependency.dir/build.make CMakeFiles/boxfort-dependency.dir/build
> [  2%] Built target boxfort-dependency
> make -f CMakeFiles/git2-dependency.dir/build.make CMakeFiles/git2-dependency.dir/depend
> cd /home/rzelnick/Documents/Criterion/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build/CMakeFiles/git2-dependency.dir/DependInfo.cmake --color=
> make -f CMakeFiles/git2-dependency.dir/build.make CMakeFiles/git2-dependency.dir/build
> [  4%] Built target git2-dependency
> make -f CMakeFiles/dyncall_s-dependency.dir/build.make CMakeFiles/dyncall_s-dependency.dir/depend
> cd /home/rzelnick/Documents/Criterion/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build/CMakeFiles/dyncall_s-dependency.dir/DependInfo.cmake --color=
> make -f CMakeFiles/dyncall_s-dependency.dir/build.make CMakeFiles/dyncall_s-dependency.dir/build
> [  4%] Built target dyncall_s-dependency
> make -f CMakeFiles/nanomsg-dependency.dir/build.make CMakeFiles/nanomsg-dependency.dir/depend
> cd /home/rzelnick/Documents/Criterion/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build/CMakeFiles/nanomsg-dependency.dir/DependInfo.cmake --color=
> make -f CMakeFiles/nanomsg-dependency.dir/build.make CMakeFiles/nanomsg-dependency.dir/build
> [  7%] Built target nanomsg-dependency
> make -f CMakeFiles/csptr-dependency.dir/build.make CMakeFiles/csptr-dependency.dir/depend
> cd /home/rzelnick/Documents/Criterion/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build/CMakeFiles/csptr-dependency.dir/DependInfo.cmake --color=
> make -f CMakeFiles/csptr-dependency.dir/build.make CMakeFiles/csptr-dependency.dir/build
> [  9%] Generating csptr-dep
> /usr/local/bin/cmake --build /home/rzelnick/Documents/Criterion/build --target csptr-bootstrap
> /usr/local/bin/cmake -S/home/rzelnick/Documents/Criterion -B/home/rzelnick/Documents/Criterion/build --check-build-system CMakeFiles/Makefile.cmake 0
> /usr/bin/make -f CMakeFiles/Makefile2 csptr-bootstrap
> /usr/local/bin/cmake -S/home/rzelnick/Documents/Criterion -B/home/rzelnick/Documents/Criterion/build --check-build-system CMakeFiles/Makefile.cmake 0
> /usr/local/bin/cmake -E cmake_progress_start /home/rzelnick/Documents/Criterion/build/CMakeFiles 5
> /usr/bin/make -f CMakeFiles/Makefile2 CMakeFiles/csptr-bootstrap.dir/all
> /usr/bin/make -f CMakeFiles/csptr-bootstrap.dir/build.make CMakeFiles/csptr-bootstrap.dir/depend
> cd /home/rzelnick/Documents/Criterion/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build /home/rzelnick/Documents/Criterion/build/CMakeFiles/csptr-bootstrap.dir/DependInfo.cmake --color=
> /usr/bin/make -f CMakeFiles/csptr-bootstrap.dir/build.make CMakeFiles/csptr-bootstrap.dir/build
> [ 20%] Performing update step for 'csptr'
> cd /home/rzelnick/Documents/Criterion/build/csptr-build/src/csptr && /usr/local/bin/cmake -P /home/rzelnick/Documents/Criterion/build/csptr-build/tmp/csptr-gitupdate.cmake
> [ 40%] Performing configure step for 'csptr'
> cd /home/rzelnick/Documents/Criterion/build/csptr && /usr/local/bin/cmake /home/rzelnick/Documents/Criterion/build/csptr-build/src/csptr -DCMAKE_INSTALL_PREFIX=/home/rzelnick/Documents/Criterion/build/external -DCMAKE_BUILD_TYPE= -G "Unix Makefiles" -DLIBCSPTR_TESTS=OFF "-DCMAKE_C_FLAGS= -Wl,--exclude-libs=ALL -fPIC -fvisibility=hidden"
> Re-run cmake no build system arguments
> -- Checking for one of the modules 'check'
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/rzelnick/Documents/Criterion/build/csptr
> cd /home/rzelnick/Documents/Criterion/build/csptr && /usr/local/bin/cmake -E touch /home/rzelnick/Documents/Criterion/build/csptr-build/src/csptr-stamp/csptr-configure
> [ 40%] Performing build step for 'csptr'
> cd /home/rzelnick/Documents/Criterion/build/csptr && /usr/local/bin/cmake --build /home/rzelnick/Documents/Criterion/build/csptr
> /usr/local/bin/cmake -S/home/rzelnick/Documents/Criterion/build/csptr-build/src/csptr -B/home/rzelnick/Documents/Criterion/build/csptr --check-build-system CMakeFiles/Makefile.cmake 0
> /usr/local/bin/cmake -E cmake_progress_start /home/rzelnick/Documents/Criterion/build/csptr/CMakeFiles /home/rzelnick/Documents/Criterion/build/csptr/CMakeFiles/progress.marks
> /usr/bin/make -f CMakeFiles/Makefile2 all
> /usr/bin/make -f CMakeFiles/csptr.dir/build.make CMakeFiles/csptr.dir/depend
> cd /home/rzelnick/Documents/Criterion/build/csptr && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/rzelnick/Documents/Criterion/build/csptr-build/src/csptr /home/rzelnick/Documents/Criterion/build/csptr-build/src/csptr /home/rzelnick/Documents/Criterion/build/csptr /home/rzelnick/Documents/Criterion/build/csptr /home/rzelnick/Documents/Criterion/build/csptr/CMakeFiles/csptr.dir/DependInfo.cmake --color=
> /usr/bin/make -f CMakeFiles/csptr.dir/build.make CMakeFiles/csptr.dir/build
> [ 50%] Building C object CMakeFiles/csptr.dir/src/mman.c.o
> /usr/bin/cc  -I/home/rzelnick/Documents/Criterion/build/csptr-build/src/csptr/include/csptr -I/home/rzelnick/Documents/Criterion/build/csptr-build/src/csptr/src -Wl,--exclude-libs=ALL -fPIC -fvisibility=hidden -Wall -Wextra -Werror -g -std=gnu99 -Wno-unused-result -Wno-missing-field-initializers   -fPIC -o CMakeFiles/csptr.dir/src/mman.c.o   -c /home/rzelnick/Documents/Criterion/build/csptr-build/src/csptr/src/mman.c
> cc: error: -Wl,--exclude-libs=ALL: 'linker' input unused [-Werror,-Wunused-command-line-argument]
> *** Error code 1
> 
> Stop.
> make[9]: stopped in /usr/home/rzelnick/Documents/Criterion/build/csptr
> *** Error code 1
> 
> Stop.
> make[8]: stopped in /usr/home/rzelnick/Documents/Criterion/build/csptr
> *** Error code 1
> 
> Stop.
> make[7]: stopped in /usr/home/rzelnick/Documents/Criterion/build/csptr
> *** Error code 1
> 
> Stop.
> make[6]: stopped in /usr/home/rzelnick/Documents/Criterion/build
> *** Error code 1
> 
> Stop.
> make[5]: stopped in /usr/home/rzelnick/Documents/Criterion/build
> *** Error code 1
> 
> Stop.
> make[4]: stopped in /usr/home/rzelnick/Documents/Criterion/build
> *** Error code 1
> 
> Stop.
> make[3]: stopped in /usr/home/rzelnick/Documents/Criterion/build
> *** Error code 1
> 
> Stop.
> make[2]: stopped in /usr/home/rzelnick/Documents/Criterion/build
> *** Error code 1
> 
> Stop.
> make[1]: stopped in /usr/home/rzelnick/Documents/Criterion/build
> *** Error code 1
> 
> Stop.
> make: stopped in /usr/home/rzelnick/Documents/Criterion/build
> ```

OK so after cleaning my build directory and re-running the aforementioned commands I was able to build Criterion. I've also tried building with `clang` but there's a compilation error with csptr, specifically with the use of the flag -Wno-unused-command-line-argument (included in @am11 's pull request on his freebsd-ci branch)

**Comment by Snaipe** [comment]
So I'm thinking it's a clang problem -- what version is it? My guess is that the linker that clang uses does not understand --exclude-libs=ALL, and therefore clang decides to warn about it. libcsptr using -Werror doesn't help.

Fortunately, I think this can be mitigated in two ways:
1. remove -Werror from libcsptr. This is always a bad idea to have as default, I'm not sure what I was thinking there.
2. check that --exclude-libs=ALL is a valid flag. meson (#273) will take care of that.

**Comment by rmzelnick** [comment]
> 
> 
> So I'm thinking it's a clang problem -- what version is it? My guess is that the linker that clang uses does not understand --exclude-libs=ALL, and therefore clang decides to warn about it. libcsptr using -Werror doesn't help.
> 
> Fortunately, I think this can be mitigated in two ways:
> 
>     1. remove -Werror from libcsptr. This is always a bad idea to have as default, I'm not sure what I was thinking there.
> 
>     2. check that --exclude-libs=ALL is a valid flag. meson (#273) will take care of that.

Sorry if I was not clear, I meant to say that Criterion won't compile unless the flag -Wno-unused-command-line is present in `clang`, this is already added in @am11 's freebsd-ci branch, please look at this pull request https://github.com/Snaipe/Criterion/pull/287/files/33bba491dfacb074f55eadaad891631c6d9dccea in CMakeLists.txt:58

**Comment by Snaipe** [comment]
Having to disable a warning is very much so a bug in the build system. The only reason this is happening is because CMake is passing a linker flag to the compiler that its not able to understand.

Adding `-Wno-unused-command-line` is, in contrast, *not* the right fix. It's just a stopgap for a broken build system, which I would rather fix.

Switching to meson will avoid the problem entirely by checking that the linker flag is understood by the compiler before trying to use it, which is what CMake ought to have been doing from the beginning.

**Comment by rmzelnick** [comment]
> 
> 
> Having to disable a warning is very much so a bug in the build system. The only reason this is happening is because CMake is passing a linker flag to the compiler that its not able to understand.
> 
> Adding `-Wno-unused-command-line` is, in contrast, _not_ the right fix. It's just a stopgap for a broken build system, which I would rather fix.
> 
> Switching to meson will avoid the problem entirely by checking that the linker flag is understood by the compiler before trying to use it, which is what CMake ought to have been doing from the beginning.

I've Google searched the meaning of `-Wno-unused-command-line` and found out that `-Werror` converts unused arguments warnings into errors, hence the use of `-Wno-unused-command-line` in order to suppress these errors. I may be wrong but it seems that the error isn't related to a linker flag but rather it is related to the fact that you're using `-Werror`

I found this interesting article that addresses why you shouldn't use `-Werror` and it specifically says,

> -Werror lays the groundwork for maintenance headaches. When a new compiler version is released, new warnings are added or other risk areas are discovered. These new warnings will now cause your previously working build to fail, often for no good reason.

Please read the full article here https://embeddedartistry.com/blog/2017/5/3/-werror-is-not-your-friend

I'll try to build Criterion with `-Werror` in my FreeBSD installation later when I get home from work.

**Comment by Snaipe** [comment]
I believe this is fixed since we've switched to meson, and it checks compatible flags.
