### ISSUE TITLE
stuck at the beginning

### ISSUE THREAD

**Issue by billcxx** [Snaipe/Criterion#315]
Hi,
I'm trying to do what the gif in the README.md is doing https://github.com/Snaipe/Criterion/blob/bleeding/doc/screencast.gif

And the program stuck without any printout.

I'm using the wsl-ubuntu on Windows 10, and I installed criterion using apt-get
$ sudo add-apt-repository ppa:snaipewastaken/ppa
$ sudo apt-get update
$ sudo apt-get install criterion-dev

I have tried ./test -l , and it seems to have the correct output.
simple: 1 test
└── test

When I try ./test --verbose , the program only print out the version number and nothing more
[----] Criterion v2.3.2

I have wait for several minutes and have to kill it with ctrl+c

I have also tried on macosx, it works fine. So I guess this is related to the wsl-ubuntu on Windows 10. Any suggestions on how to debug in this case?

**Comment by Snaipe** [comment]
Could you try building 2.3.3 from source? That does sound similar to the problem that release aimed to fix.

**Comment by Snaipe** [comment]
This also makes me realize that the ppa is one patch version behind. I'll try uploading the new build.

**Comment by billcxx** [comment]
Thanks for your prompt reply!

As you have suggested, I compile v2.3.3 from source on wsl-ubuntu, and now it works as expected.

I'll close this issue. Thanks
