### ISSUE TITLE
Update Documentation to reflect new build from source process

### ISSUE THREAD

**Issue by abkarcher** [Snaipe/Criterion#326]
Hello,

The setup.rst file still reflects the process for using cmake to build from source, which no longer works as all cmake files were removed a few days ago. Should this be updated? Thanks!

**Comment by Snaipe** [comment]
They should, and I thought [they were](https://github.com/Snaipe/Criterion/commit/9a677276dac530da4bd1b4340cfd50c6aa3b1eaa). It looks like the read the docs build failed. I'll have a look at it.

**Comment by Snaipe** [comment]
Turns out I missed the memo from read the docs telling me to upgrade their app integration. I've manually re-triggered a build for bleeding and fixed the webhook.

**Comment by abkarcher** [comment]
Awesome, thanks! (and thanks in general for Criterion!)
