### ISSUE TITLE
Issues with Criterion installation 

### ISSUE THREAD

**Issue by Bensuperpc** [Snaipe/Criterion#335]
I would like update my Criterion installation, i follow this page : https://criterion.readthedocs.io/en/latest/setup.html#installation

When i want to build my project, i have this issues : 
`./unit_tests: error while loading shared libraries: libcriterion.so.3: cannot open shared object file: No such file or directory`

With previous installer (CMake ?) I do this command `https://github.com/Snaipe/Criterion/issues/223` to solve the issue, but now, i don't how to fix it :/ 

I fix it with this command : `sudo cp ~/Criterion/build/src/libcriterion.so.3.1.0 /usr/lib/libcriterion.so.3`
I don't know better way to fix this issue.

My config : 
- Ubuntu 19.10
- GCC 9.2.1
- Clang 9
- I use separate home partition

**Comment by Snaipe** [comment]
Now, with meson, the new way to specify the right prefix is `meson --prefix=/usr build`, assuming your build directory is named `build`.

**Comment by Bensuperpc** [comment]
It's working Thank you ! :)
For future users : 
`git clone --recursive https://github.com/Snaipe/Criterion`
`cd Criterion`
`meson --prefix=/usr build`
`sudo ninja -C build install`
