### ISSUE TITLE
New tag/release

### ISSUE THREAD

**Issue by hydrapolic** [Snaipe/Criterion#336]
Would you mind creating a new tag so we can create a new Gentoo Linux package for it? The current one seems 100 commits behind.

Thanks

**Comment by Snaipe** [comment]
Thanks for looking at this. The next scheduled release is 2.4.0, and I'm not 100% happy with the stability of the new assertion API right now. The good news is that I'm actively working to get a first release candidate out since the Debian folks are also interested in packaging Criterion.

**Comment by hydrapolic** [comment]
Cool, thanks.

**Comment by kugel-** [comment]
Is there some sort of compatibility or will upgrading suddenly break all our 1000s of tests?

**Comment by hydrapolic** [comment]
I've tried building the latest snapshot and all tests for syslog-ng passed fine.

**Comment by Snaipe** [comment]
There's no reason why everything would break, but the problem is that I haven't validated that all of the "legacy" assertions are still all working. I want to add back in a test for all of these first and get a passing build.

**Comment by madebr** [comment]
The last criterion release (2.3.3) is still using cmake.
I would like to create a recipe for [conan-center-index](https://conan.io/center/).
I'll wait with this until a release with meson support is done to avoid doing throw-away work.

**Comment by hydrapolic** [comment]
Ping :)

**Comment by Snaipe** [comment]
We're working on getting v2.4.0 out; ironing out the last few issues with some outstanding help :)

Closing this in favor of #401.
