### ISSUE TITLE
Conditional samples/tests

### ISSUE THREAD

**Issue by hydrapolic** [Snaipe/Criterion#337]
On Gentoo Linux we don't always run the tests (usually when stabilizing packages), only when one desires, but it seems like currently the samples/tests are always built. So it means we build all the targets but don't actually run the tests which is a waste of building time.

Can we maybe put some conditional around these in meson.build?
````
...
subdir('samples')
subdir('test')
````

The tests messon options seems to have no effect on this.

**Comment by Snaipe** [comment]
#334 seems to address that, let me merge it.

**Comment by hydrapolic** [comment]
Yeah, that's it, thanks.
