### ISSUE TITLE
Overriding close for a test

### ISSUE THREAD

**Issue by BSFishy** [Snaipe/Criterion#339]
Right now, I am working on making tests for my project, and for one in specific, I need to override the default functionality of the `close` function. From my testing, I've noticed that it is called a lot by Criterion, so I was wondering if this is supported, or what I should do instead.

Here is a basic example of what it looks like:
```c
#include <stdio.h>
#include <criterion/criterion.h>

int close(int fd) {
    fprintf(stderr, "%d\n", fd);
    return 0;
}

Test(suite, test) {
    cr_assert_eq(close(-1), 0);
}
```

And this is an example output for that code:
```text
3
4
5
7
8
...
107
[----] Criterion v2.3.3
112
[====] Running 1 test from suite:
3
...
109
[RUN ] suite::test
-1
[PASS] suite::test: (0.00s)
116
...
121
[====] Synthesis: Tested: 1 | Passing: 1 | Failing: 0 | Crashing: 0 
118
...
108
```

Would it be possible to override that function, or is it required by Criterion? And if so, would there be any possible way for me to write a test that changes the functionality of `close` depending on if a test is running, without changing my source code?

PS: I noticed #277, and I tried the wrap solution, but it doesn't seem to be getting called by my library. Not sure if that's applicable to this.

**Comment by Snaipe** [comment]
I'm not sure why the wrapping wouldn't work, but here's an alternative:

```c
static int override_close;

int close(int fd) {
    static int (*real_close)(int);
    if (!real_close) {
        real_close = dlsym(RTLD_NEXT, "close");
    }
    if (!override_close) {
        return real_close(fd);
    }

    fprintf(stderr, "%d\n", fd);
    return 0;
}

Test(foo, bar) {
    override_close = 1;
    // do your function calls
    override_close = 0;

    cr_assert(...);
}
```

**Comment by Snaipe** [comment]
Closing this; it's not a Criterion issue per-se, and care should be taken anyway when replacing vital functions like close().
