### ISSUE TITLE
criterion: Could not initialize inheritable arena: Not enough space

### ISSUE THREAD

**Issue by DreamCAtEarth** [Snaipe/Criterion#350]
Hello,

I tested Criterion 2.3.3 (both with build from the sources and pre-built releases from the repos) on Windows 7 64 bits, both with MinGW 6.0 and MSVC 2019 and I have the same issue before every test could start :

criterion: Could not initialize inheritable arena: Not enough space

Any clue ?

The error comes from the cri_alloc_init but I wasn't able to search further as bxf_arena_init is not defined in the project. Maybe dependencies with boxfort weren't really well done I suppose ?

Thanks for your help !

**Comment by Snaipe** [comment]
Is your dev environment also 64-bit (as-in, was criterion compiled as a 64-bit or 32-bit library)? I'm really not sure how it's possible that BoxFort was not able to find a suitable space for allocation in a 2^48 byte memory space.
