### ISSUE TITLE
Clarification on the .init hook for test suite

### ISSUE THREAD

**Issue by arv-sajeev** [Snaipe/Criterion#355]
the .init hook seems to run for each test case in a test suite, is there a way to make it only run once for each test suite. Am I doing something wrong??

**Comment by Snaipe** [comment]
Well, it depends what level of access you want your hook to have. Do you want it to change something in the test environment? the main issue is that each test runs in its own process, so a suite-wide init hook has to run once for each process. If you don't care about changing stuff (including variables), there's an old hook mechanism where you can define a [report hook](https://criterion.readthedocs.io/en/master/hooks.html) on PRE_SUITE. It's an awkward interface, and I plan to phase it out at some point, but for now you could try using it.

**Comment by arv-sajeev** [comment]
Thank you Snaipe,
I wanted to run a DPDK application so it has to setup an enviroment before the test runs , and I wanted it to persist throughout the suite. I couldn't figure out how to do this using report hook, it looks like hooks can only be used for printing and logging purposes.

But no worries I just have to init the environment for each test My tests work fine. 

Your tool is really easy to use and well documented, it's helped me setup tests without any hassle.
