### ISSUE TITLE
Porting Criterion

### ISSUE THREAD

**Issue by risaldar** [Snaipe/Criterion#356]
Although it is PC based, I needed to know if you have any guide on porting it to an embedded environment and executing under custom debuggers e.g. Lauterbach (https://www.lauterbach.com/frames.html?home.html). Also I couldn't find any information on generating mocks or stub (does any such thing come integrated with Criterion?)

**Comment by Snaipe** [comment]
There's no real guide for porting Criterion, although if your target platform is unix-like, there shouldn't be any issue in porting the whole thing, assuming your embedded environment has an MMU. The problematic piece might be porting BoxFort if you happen to target an unsupported architecture, but if you're game for writing a trampoline in your target arch assembly, that should be working OK.

Mock and stubs are out of scope for Criterion, the idea is that you'd use your favorite mocking framework.
