### ISSUE TITLE
building using msvc

### ISSUE THREAD

**Issue by daveabiy** [Snaipe/Criterion#357]
I cloned the git. 
msvc failed to build the library. 
error with the FindPackageHandleStandardArgs.cmake:164. 

if (${_NAME}_FIND_REQUIRED)
    message(FATAL_ERROR "${__msg}")
  else ()

How can i fix this?

additional info:
Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
[CMake]   Could NOT find Criterion (missing: CRITERION_LIBRARY CRITERION_INCLUDE_DIR)
[CMake] Call Stack (most recent call first):

**Comment by Snaipe** [comment]
Did you build & install criterion to somewhere MSVC knows about (maybe a system path)? I don't have enough details to really help here.

**Comment by Snaipe** [comment]
No update; closing.
