### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by paul000001** [Snaipe/Criterion#358]
I tried to build Criterion a couple times but I am getting the same results.

`[275/412] Compiling C object subprojects/libffi/src/libffi.so.7.1.0.p/x86_unix64.S.o
FAILED: subprojects/libffi/src/libffi.so.7.1.0.p/x86_unix64.S.o 
cc -Isubprojects/libffi/src/libffi.so.7.1.0.p -Isubprojects/libffi/src -I../subprojects/libffi/src -Isubprojects/libffi -I../subprojects/libffi -Isubprojects/libffi/include -I../subprojects/libffi/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -g -DFFI_BUILDING -fPIC -DTARGET=X86_64 -MD -MQ subprojects/libffi/src/libffi.so.7.1.0.p/x86_unix64.S.o -MF subprojects/libffi/src/libffi.so.7.1.0.p/x86_unix64.S.o.d -o subprojects/libffi/src/libffi.so.7.1.0.p/x86_unix64.S.o -c ../subprojects/libffi/src/x86/unix64.S
../subprojects/libffi/src/x86/unix64.S: Assembler messages:
../subprojects/libffi/src/x86/unix64.S:451: Error: junk at end of line, first unrecognized character is `@'
../subprojects/libffi/src/x86/unix64.S:470: Error: junk at end of line, first unrecognized character is `@'
../subprojects/libffi/src/x86/unix64.S:483: Error: junk at end of line, first unrecognized character is `@'
../subprojects/libffi/src/x86/unix64.S:497: Error: junk at end of line, first unrecognized character is `@'
../subprojects/libffi/src/x86/unix64.S:510: Error: junk at end of line, first unrecognized character is `@'
[276/412] Compiling C object subprojects/libffi/src/libffi.so.7.1.0.p/closures.c.o
../subprojects/libffi/src/closures.c: In function ‘allocate_space’:
../subprojects/libffi/src/closures.c:747:29: warning: comparison of integer expressions of different signedness: ‘off_t’ {aka ‘long int’} and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
  747 |       off_t to_write = (len < page_size) ? len : page_size;
      |                             ^
../subprojects/libffi/src/closures.c:747:44: warning: operand of ?: changes signedness from ‘off_t’ {aka ‘long int’} to ‘size_t’ {aka ‘long unsigned int’} due to unsignedness of other operand [-Wsign-compare]
  747 |       off_t to_write = (len < page_size) ? len : page_size;
      |                                            ^~~
../subprojects/libffi/src/closures.c:734:31: warning: unused parameter ‘offset’ [-Wunused-parameter]
  734 | allocate_space (int fd, off_t offset, off_t len)
      |                         ~~~~~~^~~~~~
ninja: build stopped: subcommand failed.`

**Comment by Snaipe** [comment]
Getting libffi to compile right on any given system can be fairly hard -- I've recommend installing the libffi-dev packages that are relevant to your distribution.

**Comment by paul000001** [comment]
I have already the later libffi-dev installed.

**Comment by Snaipe** [comment]
Can you send the output of `meson --reconfigure <your build dir>`? libffi should have been detected. Can you make sure that you have pkg-config installed?

**Comment by ayoubelmhamdi** [comment]
it's solved for me by installing  `libffi-dev ` in void-Linux named `libffi-devel` then `reconfiging`
```bash
$ xbps-install -Sy libffi-devel
$ meson --reconfigure 
```
