### ISSUE TITLE
No osx release artifacts for v2.3.3

### ISSUE THREAD

**Issue by jackcmay** [Snaipe/Criterion#367]
Is v2.3.3 not compatible with osx?

**Comment by igorkotkovets** [comment]
There is an issue on macOS Big Sur 

`$ make tests

/Applications/Xcode.app/Contents/Developer/usr/bin/make clean
rm -f main.o app who_likes_it.o units.o tests
CC -o test tests.c -lcriterion
tests.c:1:10: fatal error: 'criterion/criterion.h' file not found
#include <criterion/criterion.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [tests] Error 1
`

I installed Criterion using `brew install snaipe/soft/criterion`

Do you have any ideas? 
Thanks in advance

**Comment by minbaby** [comment]
```bash
#####################
# cmake include dir
#####################
export C_INCLUDE_PATH=/usr/local/include
export CPLUS_INCLUDE_PATH=/usr/local/include

#####################
# cmake libs
#####################
export LIBRARY_PATH=/usr/local/lib
```

add to .bashrc or .zshrc, then reload shell

**Comment by igorkotkovets** [comment]
To build tests I made `Makefile` with additional compilation flags

```bash
...
tests: tests.c who_likes_it.c
        $(MAKE) clean
        CC -I /Users/igork/.brew/opt/criterion/include -L/Users/igork/.brew/opt/criterion/lib -o tests tests.c -lcriterion
...
```
where `-I /Users/igork/.brew/opt/criterion/include` - path to headers
`-L/Users/igork/.brew/opt/criterion/lib` - path to library binary

**Comment by Snaipe** [comment]
This looks more generally like an environment misconfiguration. If criterion is not installed in the system paths, I would expect the user environment to define the relevant [environment variables](https://gcc.gnu.org/onlinedocs/gcc/Environment-Variables.html) -- namely, C_INCLUDE_PATH, CPLUS_INCLUDE_PATH, and LIBRARY_PATH) to make this work. I'm also surprised that brew isn't taking care of that though.

**Comment by Snaipe** [comment]
I assume this is fixed by MrAnno's tap: `brew install mranno/tap/criterion`. Feel free to reopen or make a new issue if criterion still can't build on macOS.

**Comment by MyPublicGitHubAcct** [comment]
Hello,

I ran into this problem today (first time trying Criterion) - 

Installed with brew install criterion
Mac (M1 chip) running Sonoma 14.3.1
Project is very simple - main.cc, sig.cc, sig_test.cc + Makefile, with all the things you would expect.

I can add the environment variables, but before I do...should we be using this repo or Mranno's?
