### ISSUE TITLE
Ninja Build Failed.

### ISSUE THREAD

**Issue by aolia-0303** [Snaipe/Criterion#372]
I was following the steps here(https://criterion.readthedocs.io/en/latest/setup.html#installation) in order to build Criterion:

The following command failed
```
ninja -C build
```

The error log is:
```
../subprojects/libffi/src/x86/unix64.S:451: Error: junk at end of line, first unrecognized character is `@'
../subprojects/libffi/src/x86/unix64.S:470: Error: junk at end of line, first unrecognized character is `@'
../subprojects/libffi/src/x86/unix64.S:483: Error: junk at end of line, first unrecognized character is `@'
../subprojects/libffi/src/x86/unix64.S:497: Error: junk at end of line, first unrecognized character is `@'
../subprojects/libffi/src/x86/unix64.S:510: Error: junk at end of line, first unrecognized character is `@'
```

**Comment by uniquepointer** [comment]
Did you ever fix this issue? I am running into same error.

**Comment by Snaipe** [comment]
Compiling libffi when it's missing on your system is kind of a last-resort-hope-you-know-what-you're-doing approach. Please install libffi-dev (or whatever the name is for your distro's libffi package).

Perhaps the docs should be updated to indicate this, or at least not attempt to compile libffi by default.

**Comment by uniquepointer** [comment]
gotcha, thank you

**Comment by MrAnno** [comment]
See also:
https://gitlab.freedesktop.org/gstreamer/meson-ports/libffi/-/issues/9

Workaround: `meson setup -Dc_std=gnu11 ...`

**Comment by MartinBourbier** [comment]
I just encountered the same issue and I have libffi-dev installed on my machine.
I also tried the workaround of @MrAnno, but it did not work.

Does anybody have a clue as to why this is happenning?

**Comment by MrAnno** [comment]
It's happening due to a non-C-standard libffi check. More info can be found in the issue of my previous comment.

Using gnu extensions `c_std=gnu11` should fix it.

**Comment by MartinBourbier** [comment]
I tried again and it worked this time.
Thanks!
