### ISSUE TITLE
Running tests creates dozens of sandbox-gmon.<0-9999> files, test cases "crashing" on teardown in valgrind

### ISSUE THREAD

**Issue by abkarcher** [Snaipe/Criterion#373]
Hello,

We recently made some minor changes to our library's build system and have begun running into some strange issues with Criterion. The tests all run fine, however there are two issues I have not been able to isolate:

1.) After the test cases are run, there are usually anywhere from a few dozen to ~300 sandbox-gmon files created in the test directory that must be removed manually.

2.) When running valgrind on tests, we get these pop ups with most tests - (the teardown errors do not occur when running the tests regularly)
(Command: `valgrind --leak-check=full --track-origins=yes --show-leak-kinds-all --trace-children=yes .libs/runtest`)

```
==12357== Process terminating with default action of signal 27 (SIGPROF)
==12357==    at 0x4F5465A: __open_nocancel (open64_nocancel.c:45)
==12357==    by 0x4F62874: write_gmon (gmon.c:365)
==12357==    by 0x4F62BCE: _mcleanup (gmon.c:444)
==12357==    by 0x4E8815D: __cxa_finalize (cxa_finalize.c:83)
==12357==    by 0x146126: ??? (in /home/andrew/Desktop/publicAcvp/test/.libs/runtest)
==12357==    by 0x4011F5A: _dl_fini (dl-fini.c:138)
==12357==    by 0x4E87A26: __run_exit_handlers (exit.c:108)
==12357==    by 0x4E87BDF: exit (exit.c:139)
==12357==    by 0x4E650B9: (below main) (libc-start.c:342)
==12357== 
==12357== HEAP SUMMARY:
==12357==     in use at exit: 3,337,738 bytes in 1 blocks
==12357==   total heap usage: 61,331 allocs, 61,330 frees, 5,600,659 bytes allocated
==12357== 
==12357== 3,337,738 bytes in 1 blocks are still reachable in loss record 1 of 1
==12357==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==12357==    by 0x4F62A01: monstartup (gmon.c:153)
==12357==    by 0x146060: __gmon_start__ (in /home/andrew/Desktop/publicAcvp/test/.libs/runtest)
==12357==    by 0x50E0015: ??? (in /usr/lib/x86_64-linux-gnu/libdl-2.31.so)
==12357== 
==12357== LEAK SUMMARY:
==12357==    definitely lost: 0 bytes in 0 blocks
==12357==    indirectly lost: 0 bytes in 0 blocks
==12357==      possibly lost: 0 bytes in 0 blocks
==12357==    still reachable: 3,337,738 bytes in 1 blocks
==12357==         suppressed: 0 bytes in 0 blocks
==12357== 
==12357== For lists of detected and suppressed errors, rerun with: -s
==12357== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
[----] Warning! The test `AES_API::empty_ctx` crashed during its setup or teardown.

```

The link to our test directory is here: https://github.com/cisco/libacvp/tree/libacvp_1_2_0-throttle/test
The aforementioned changes to the build system can be found in Makefile.am.

Any help or feedback would be appreciated.

Thanks,
Andrew

**Comment by Snaipe** [comment]
You're compiling your tests with -pg, so it's expected that you're getting gprof files when running them. Gprof-compiled programs cannot run with valgrind due to the SIGPROF issues -- if you must use valgrind, use callgrind for profiling, or compile with and without profiling.

**Comment by abkarcher** [comment]
Hi,

The -p was what I was missing, didn't realize thats what the sandbox-gmon files were. Thanks a ton for the help!

Andrew
