### ISSUE TITLE
criterion: ftbfs with GCC-11

### ISSUE THREAD

**Issue by mochrul** [Snaipe/Criterion#377]
The criterion Debian package received a bug (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=984025) that the criterion cannot be compiled with the newest gcc version (GCC-11).

The compilation log is here: https://people.debian.org/~doko/logs/20210228/filtered/gcc11/criterion_2.3.3git1-1_unstable_gcc11.log

**Comment by MrAnno** [comment]
Hi @mochrul,

This will be fixed in #395.

https://github.com/Snaipe/Criterion/pull/395/commits/31e2acf989935ffad7044b149062bad4935d5c80
