### ISSUE TITLE
Make and CMake errors - Installing Criterion on BigSur11.2.3

### ISSUE THREAD

**Issue by jolan-brizard** [Snaipe/Criterion#378]
Hey guys, i encoutered a make and cmake error when trying to do 'brew install snaipe/soft/criterion' command.
I searched on the 'Issues' GitHub pages but could not find someting that was helping me (I'm a first year IT student that might explain why though). Here's the screenshot : 
<img width="1052" alt="Capture d’écran 2021-03-15 à 10 21 15" src="https://user-images.githubusercontent.com/71981971/111131527-9fe3ac80-8578-11eb-92bd-b74dcbd1dd91.png">

I tried to do it manually by cloning the repository / mkdir build / cd build / cmake .. but encountered another cmake error 'Cannot load cache'.

Thanks for helping if you do and have a nice day wherever you are :)

**Comment by Snaipe** [comment]
I believe this is fixed by MrAnno's tap: `brew install mranno/tap/criterion`
