### ISSUE TITLE
Is v2.3.3 the lastest stable release?

### ISSUE THREAD

**Issue by RaniAgus** [Snaipe/Criterion#380]
I couldn't install Criterion in Linux Mint 20.1 using `apt-get`:
``` bash
$ sudo add-apt-repository ppa:snaipewastaken/ppa
Cannot add PPA: ''This PPA does not support focal''.
```
So I tried installing the compiled binary archives manually, and it worked:
```
$ wget -qO- https://github.com/Snaipe/Criterion/releases/download/v2.3.3/criterion-v2.3.3-linux-x86_64.tar.bz2 | tar -xjvf -
$ sudo cp -a criterion-v2.3.3/lib/. /usr/lib
$ sudo cp -a criterion-v2.3.3/include/. /usr/include
```

But I'm wondering if v2.3.3 is the lastest stable release available, because it has been released on Nov 4, 2018 and I see that there are 122 commits bleeding since then.

Thanks for providing this cool framework :)

**Comment by MrAnno** [comment]
v2 also has some bugs that have been fixed but they're unreleased  (such as #301 - Sep 2019), and now they affect all the latest Linux distros.

@Snaipe are you looking for maintainers?
I'm not fully familiar with your v3 plans, future directions, etc., but I'd be glad to help with maintenance releases, or with the v3 transition.

**Comment by Snaipe** [comment]
To update this; yes, v2.3.3 is the last stable release; I don't have that much time to work on Criterion these days, and an issue in my notification settings caused me to not get recent updates on the bug tracker.

That being said, MrAnno has stepped up as maintainer; he'll be making pull requests to try to get a new release out, and will eventually take over maintenance.

Other than that, please note that this project is still very much driven by pull requests; if you have an issue with the library, we welcome patches.

**Comment by Snaipe** [comment]
We're working on getting v2.4.0 out; closing this in favor of #401
