### ISSUE TITLE
Support for clang compiler in Cirrus CI

### ISSUE THREAD

**Issue by kare** [Snaipe/Criterion#393]
Is it possible to support clang compiler?

**Comment by Snaipe** [comment]
It should be working with clang. What kind of issue are you seeing?

**Comment by kare** [comment]
@Snaipe I'm new to the project and thought that it's not supported since it's not listed in Cirrus CI.

**Comment by kasperk81** [comment]
macOS covers clang in CI.

**Comment by MrAnno** [comment]
Compiling with clang is supported, it is indirectly tested in CI with a certain type of clang compiler as part of the macOS job. 

Feel free to reopen this issue, if you have further questions/issues with clang compilation.
