### ISSUE TITLE
Criterion v2.4.0 release

### ISSUE THREAD

**Issue by Snaipe** [Snaipe/Criterion#401]
I think the recent fixes addressed most of the showstopping issues for v2.4.0; @MrAnno how do you feel about the current state of bleeding for a new release?

Concurrently, I'll go through every open issue to see whether this will be fixed by the release, and if not whether this is a showstopper for the new version.

Prerequisites:

* [x] Check that the readthedocs build+publish still works, maybe use a test tag

Release checklist:

* [x] Update the ChangeLog
* [x] Merge bleeding into master (with a merge commit)
* [x] Make an annotated tag (with the changelog as message)
* [x] Tag BoxFort v0.1.2 at the commit that the Criterion release uses (currently 46cfaebead74bd1d2898afb66a06ec6badce4326)
* [x] Send a new version notification to the mailing list
* [x] Party! :tada:

**Comment by Snaipe** [comment]
Something I haven't checked in a while is whether the readthedocs generator still works; we'll probably need to make a test tag and test it out first, because re-publishing docs for a tag was pretty much impossible last time I checked.

**Comment by MrAnno** [comment]
Sounds good to me :)

I'm not sure about backward compatibility with v2.3.3, I'll do some tests on the current release candidate (syslog-ng has 182 exotic Criterion tests, I am going to give it a go.).

**Comment by MrAnno** [comment]
In the meantime:

![image](https://user-images.githubusercontent.com/3130044/147750734-a4b743c3-1164-478e-8aa0-b9508f8e1ed4.png)


![image](https://user-images.githubusercontent.com/3130044/147750811-0b0b5c97-e49a-4bca-abe7-a8d0560bb4ce.png)

**Comment by Snaipe** [comment]
These removed symbols should never have been exposed to begin with; looks like I'll have to audit symbol visibility on the new version

**Comment by MrAnno** [comment]
Can I help with collecting entries for the changelog?

**Comment by Snaipe** [comment]
Sure; I usually go through the git log of everything that happened between the release candidate and the last release, then categorize & format them accordingly.

**Comment by MrAnno** [comment]
Thank you, I'll do the same.

I've tested the release candidate with the mentioned syslog-ng tests. Most of them work properly with the below warnings, which is absolutely fine:
```
boxfort-worker: Symbol `criterion_options' has different size in shared object, consider re-linking
```

I have 2 crashes, which I'm currently investigating. Hopefully they are unrelated to Criterion.

**Comment by kugel-** [comment]
Thanks for working on 2.4.0. If time permits (and I don't forget) I'll check our inhouse tests work fine with the new release.

**Comment by MrAnno** [comment]
Everything seems to be fine from my side. A ton of warnings have appeared originated from 2 potential issues:

```
In file included from /.../Criterion/install/include/criterion/internal/assert.h:44,
                 from /.../Criterion/install/include/criterion/assert.h:1681,
                 from /.../Criterion/install/include/criterion/criterion.h:32,
                 from ../modules/csvparser/tests/test_csvparser_from_config.c:26:
/.../Criterion/install/include/criterion/internal/../hooks.h:50:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
   50 | typedef void (*f_report_hook)();
      | ^~~~~~~
```

```
In file included from ../lib/logproto/tests/test_findeom.c:25:
/.../Criterion/install/include/criterion/criterion.h:45: warning: "Test" redefined
   45 | #define Test(Suite, Name, ...)    internal
      |
In file included from /.../Criterion/install/include/criterion/internal/parameterized.h:27,
                 from /.../Criterion/install/include/criterion/parameterized.h:101,
                 from ../lib/logproto/tests/test_findeom.c:24:
/.../Criterion/install/include/criterion/internal/test.h:197: note: this is the location of the previous definition
  197 | #define Test(...)         CR_EXPAND(CR_TEST_BASE(__VA_ARGS__, .sentinel_ = 0))
      |
```

#403 fixes them.

**Comment by Snaipe** [comment]
@kugel- I usually go through a round of release candidates first, so we'll have plenty of time to let users check their tests against the new release once we start the release process.

**Comment by Snaipe** [comment]
I think I'm happy with the current tip. Once #411 merges, I'll create the release candidate tag `v2.4.0-rc`.

After that tag, and until `v2.4.0` gets tagged, all commits on master will be their own release candidate even without an explicit tag. To distinguish between them, `git describe` is authoritative on the release candidate version.

For instance, if a new commit `deadbeef` is made on top of v2.4.0-rc, git describe will produce a version like `v2.4.0-rc-1-deadbeef`, which will be latest release candidate version.

Once master sits two full weeks without any new commits on top of it, I'll tag v2.4.0.

**Comment by Snaipe** [comment]
v2.4.0-rc has been tagged! I'll repeat what I already sent to the mailing list here:

---

Criterion v2.4.0-rc-0-gbc3b265, the first release candidate for 2.4.0,
has been released. The full changelog is included below. Please verify
that your tests still work with this new version. As usual, the
release candidate will wait for two weeks after the last commit before
turning into an actual release.

One of the very exciting additions to this release is the new
experimental assertion API. This API brings rich value printing and
diffing on assertion error, and is more pleasant to use overall. Give
it a try!

I'd like to thank everyone involved in this release. In particular,
huge thanks to László Várady for helping me push this over the finish
line. It has been three years since the last release of Criterion, and
I've had less and less time and interest in the project due to me not
mainly working with C.

Alongside that release, I'd like to announce that László will help
with maintenance of the project going forward. László is currently
involved with syslog-ng[1] and has contributed outstanding fixes to
Criterion's sandboxing code, ARM support, as well as various fixes in
the CI pipeline, build system, tests, and documentation.

Happy New Year!

[1]: https://github.com/syslog-ng/syslog-ng

**Comment by MrAnno** [comment]
Yay! Thank you for the kind words.

**Comment by MrAnno** [comment]
The latest commit on master is now 2 weeks old.

There is ongoing work about release automation (#414), which is currently in the testing phase, and we have a debugging issue on macOS (Apple silicon) in which the `--debug` flag seems not to be working, but using the manual `--debug=idle` method works fine as a workaround.

**Comment by Snaipe** [comment]
It seems fairly bad to not work by default when passing in --debug, at least it seems like a pretty big gotcha to ship like this and tell macOS users that --debug must be used with `idle`. I wonder if we should add a fallback to BoxFort such that if the preferred debugger does not exist, it defaults to idle. Thoughts?

**Comment by MrAnno** [comment]
I like the idea, will do. :)

**Comment by Snaipe** [comment]
With #421 merged and the new release candidate ([v2.4.0-rc-18-g1cc3911](https://github.com/Snaipe/Criterion/releases/tag/v2.4.0-rc-18-g1cc3911)) out, let's make it marinate until the end of the upcoming week before releasing 2.4.0. So far it seems there hasn't been any newly discovered issues so I think we don't have to wait two extra weeks to tag the release.

**Comment by MrAnno** [comment]
Sounds great.
I'll recheck my existing Criterion tests with the latest release candidate until the end of next week.

**Comment by Snaipe** [comment]
And with that, [v2.4.0](https://github.com/Snaipe/Criterion/releases/tag/v2.4.0) has been released! :tada: Thanks for the awesome work @MrAnno, and for helping push this over the finish line!
