### ISSUE TITLE
Cannot add PPA: ''This PPA does not support focal''.

### ISSUE THREAD

**Issue by cassepipe** [Snaipe/Criterion#428]
I have tried using the PPA but apparently focal fossa is not supported. Is this on purpose or an error ?

Congrats (and thanks) for  the release !

**Comment by Snaipe** [comment]
The PPA is unsupported now that Debian 11 and Ubuntu 21.04 officially package Criterion -- no new version will be published or backported. You'll have better chances at building from source yourself.

**Comment by cassepipe** [comment]
Thanks for the info. 

Successful build on Linux Mint 20.3.
