### ISSUE TITLE
cri_diff_init leaks memory

### ISSUE THREAD

**Issue by g1g4b0t** [Snaipe/Criterion#429]
According to [Valgrind](https://valgrind.org/), [`cri_diff_init`](https://github.com/Snaipe/Criterion/blob/4cf886a2d96ada425e8c88d3c4d935e510c7c712/src/string/diff.c#L38) leaks memory, e.g.:

```
==123456== 96 bytes in 1 blocks are still reachable in loss record 18 of 18
==123456== at 0x4837B65: calloc (vg_replace_malloc.c:752)
==123456== at 0x48DC368: git__calloc (util.h:169)
...
==123456== at 0x486CB3B: git_libgit2_init (global.c:278)
==123456== at 0x486405F: cri_diff_init (in libcriterion.so.3)
```

`cri_diff_init` calls `git_libgit2_init`, which should be accompanied by a call to [`git_libgit2_shutdown`](https://libgit2.org/libgit2/#HEAD/group/libgit2/git_libgit2_shutdown) when finished with the `libgit2` context. I could not find any calls to `git_libgit2_shutdown` in the code, so that would explain the leaks.

#### Appendix

Test program `test_foo.c`:
```c
#include <criterion/criterion.h>

Test(foo, bar) {
    cr_assert(0);
}
```

Compiled with `gcc (Debian 8.3.0-6) 8.3.0)` and linked against [Criterion 2.4.0](https://github.com/Snaipe/Criterion/releases/tag/v2.4.0) on `Debian 4.19.194-3 (2021-07-18) x86_64`:
```
gcc -g -O0 test_foo.c -o test_foo -lcriterion
```

Ran test program `test_foo` under Valgrind:
```
valgrind -v --track-origins=yes --leak-check=full --show-leak-kinds=all ./test_foo
```

**Comment by Snaipe** [comment]
Yeah, git_libgit2_init had to be added because some change in libgit2 cause the diff functions to depend on some global state. It's rather annoying and I wished we didn't need it.

I'll see if I can add a call to git_libgit2_shutdown somewhere. Unfortunately, even if we fix libgit2 to not have to depend on that global state, distros shipping with these broken versions will still require that init/shutdown call pair.

**Comment by Snaipe** [comment]
#430 fixes this. Child processes were also impacted since they had an independent call to `cri_diff_init`, though the valgrind call above didn't catch that since it was missing `--trace-children=yes`. I've fixed the leak in both places.
