### ISSUE TITLE
[M1 Mac] Compile error implicit declaration 'BXF_DBG_ENABLE_FALLBACK'"

### ISSUE THREAD

**Issue by Techcable** [Snaipe/Criterion#433]
On my M1 Mac Monterey 12.2.1, I get the follinwg error on commit 5b0a4b52dbc26860601c1269da4bbe7154f6c866 and everything after it:

```
[1/45] Compiling C object src/libcriterion.3.dylib.p/core_runner_coroutine.c.o
FAILED: src/libcriterion.3.dylib.p/core_runner_coroutine.c.o 
ccache cc -Isrc/libcriterion.3.dylib.p -Isrc -I../src -I../dependencies/debugbreak -I../dependencies/klib -I../dependencies/valgrind/include -Iinclude -I../include -I../subprojects/boxfort/include -Isubprojects/boxfort/src -I../subprojects/boxfort/src -Isubprojects/nanomsg/__CMake_build -I../subprojects/nanomsg/__CMake_build -Isubprojects/nanomsg -I../subprojects/nanomsg -Isubprojects/nanopb/__CMake_build -I../subprojects/nanopb/__CMake_build -Isubprojects/nanopb -I../subprojects/nanopb -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/ffi -I/opt/homebrew/Cellar/libgit2/1.3.0/include -fcolor-diagnostics -Wall -Winvalid-pch -Wextra -std=c11 -O0 -g -Wno-unused-parameter -Wno-unused-value -fvisibility=hidden -fexceptions -DCRITERION_BUILDING_DLL=1 -DPB_ENABLE_MALLOC=1 -DPB_NO_PACKED_STRUCTS=1 -D_GNU_SOURCE '-DGETTEXT_PACKAGE="criterion"' -DNN_STATIC_LIB -DBXF_STATIC_LIB=1 -D__USE_MINGW_ANSI_STDIO -MD -MQ src/libcriterion.3.dylib.p/core_runner_coroutine.c.o -MF src/libcriterion.3.dylib.p/core_runner_coroutine.c.o.d -o src/libcriterion.3.dylib.p/core_runner_coroutine.c.o -c ../src/core/runner_coroutine.c
../src/core/runner_coroutine.c:330:13: error: implicit declaration of function 'BXF_DBG_ENABLE_FALLBACK' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            BXF_DBG_ENABLE_FALLBACK(debugger);
            ^
../src/core/runner_coroutine.c:354:21: error: implicit declaration of function 'BXF_DBG_GET_DEBUGGER' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            switch (BXF_DBG_GET_DEBUGGER(sp.debug.debugger)) {
                    ^
2 errors generated.
ninja: build stopped: subcommand failed.
```

Here is a link to the complete log: https://gist.github.com/Techcable/580b96c345885870393518d8a621f730

I have bisected the problem. It begins at commit 5b0a4b52dbc26860601c1269da4bbe7154f6c866 (and everything after it).

It is *NOT* present on fd9be359b0947f55e40188f1de9400380a3abcab

**Comment by MrAnno** [comment]
Hi,

Thanks for opening this issue.

The basic idea here is that commit 5b0a4b52dbc26860601c1269da4bbe7154f6c866 depends on a new BoxFort feature, so it has to be updated, which is done in fd9be359b0947f55e40188f1de9400380a3abcab (if one uses the subproject just like you do).

Something is obviously wrong, because the mentioned subproject bump precedes 5b0a4b52dbc26860601c1269da4bbe7154f6c866.

I'll look into it soon.

**Comment by Snaipe** [comment]
I hit that in my local workspace before -- turns out that when you bump a version in the wrap, Meson won't redownload the subproject across reconfigurations.

@Techcable can you try running `meson subprojects update --reset`? Another possibility is to manually rm-rf subprojects/boxfort, but I'd like to confirm what the canonical way to fix this is.

**Comment by Techcable** [comment]
> I hit that in my local workspace before -- turns out that when you bump a version in the wrap, Meson won't redownload the subproject across reconfigurations.
> 
> @Techcable can you try running `meson subprojects update --reset`? Another possibility is to manually rm-rf subprojects/boxfort, but I'd like to confirm what the canonical way to fix this is.

This command fixes this. Also a clean checkout compiles correctly as well.

I ran
```bash
meson subprojects update --reset
meson --reconfigure build
meson compile -C build > log.txt 2>&1
```

Now everything works correctly 😄 

Appears that this is an issue of meson cache invalidation on my end. 😄 

Here are the more detailed outputs of each command: https://gist.github.com/Techcable/d6ecb3fdc0e0db1fb88ed63f5a767546
