### ISSUE TITLE
Still reachable blocks from libgit2 and libcrypto calls

### ISSUE THREAD

**Issue by thomasfsteeples** [Snaipe/Criterion#442]
Have been using Criterion in a new project, and am enjoying it thus far. However, when I run my project through valgrind, the use of Criterion gives me a large number of "still reachable" blocks from calls to libgit2 and libcrypto. This behaviour can be observed with Criterion own unit tests executable, with a command like the following: 
```
valgrind --tool=memcheck --leak-check=full --trace-children=yes --show-leak-kinds=all -- ./build/test/unit/unit_tests
...
==27970== LEAK SUMMARY:
==27970==    definitely lost: 0 bytes in 0 blocks
==27970==    indirectly lost: 0 bytes in 0 blocks
==27970==      possibly lost: 0 bytes in 0 blocks
==27970==    still reachable: 629,551 bytes in 10,481 blocks
==27970==         suppressed: 0 bytes in 0 blocks
```
Whilst "still reachable" leaks are perceived by some to be ok (see [this](https://stackoverflow.com/a/3857638) stackoverflow answer), it does clutter my valgrind output, and makes it more difficult to eliminate "still reachable" blocks from my own programs.

The three main culprits seem to be `PEM_X509_INFO_read_bio` and `X509_load_cert_crl_file` from libcrypto, and `git_libgit2_init` from libgit2. I'm not au fait with the OpenSSL library, but I believe the still reachable leak from libgit2 can be fixed by a corresponding call to `git_libgit2_shutdown` at the appropriate moment.

Would you be willing to consider introducing the appropriate cleanup code to Criterion? Thank you for your time.

**Comment by Snaipe** [comment]
This should already be fixed on bleeding (see #430) -- it will be included in the next release, v2.4.1. Not sure when the release will happen quite yet, but we can probably start the release process once #440 gets merged.

**Comment by thomasfsteeples** [comment]
Oh excellent, well done. Happy for you to close the issue when you deem it appropriate.

**Comment by Snaipe** [comment]
I've started the release train for v2.4.1, and [`v2.4.1-rc-0-g3543417`](https://github.com/Snaipe/Criterion/releases/tag/v2.4.1-rc) is the current release candidate, feel free to try it out!
