### ISSUE TITLE
PPA for installation on Ubuntu < 21.4 does not work

### ISSUE THREAD

**Issue by senarclens** [Snaipe/Criterion#444]
```
sudo add-apt-repository ppa:snaipewastaken/ppa
```

leads to

```
E: The repository 'http://ppa.launchpad.net/snaipewastaken/ppa/ubuntu focal Release' does not have a Release file.
```
on *buntu 20.04, so criterion can only be installed from source atm on all Ubuntu versions <21.4.

**Comment by Snaipe** [comment]
We should probably remove the instructions to install from ppa -- we're no longer going to maintain it going forward so it'll be stuck at version 2.3.3 for the foreseeable future. Building from source is going to be the best answer here if the distro doesn't have Criterion packaged.

**Comment by senarclens** [comment]
Closed by removing outdated documentation (https://github.com/Snaipe/Criterion/commit/93667ee539099f6317629734c1c079a6730b5620).
