### ISSUE TITLE
g_worker_pipe memory leak

### ISSUE THREAD

**Issue by cybojanek** [Snaipe/Criterion#45]
Valgrind reports g_worker_pipe memory leak never being freed. Should it be freed in cleanup?

https://github.com/Snaipe/Criterion/blob/bleeding/src/core/runner.c#L412

**Comment by Snaipe** [comment]
Indeed it should. Thank you!

**Comment by cybojanek** [comment]
Wow - that was quick! Cheers! Thanks for the awesome library!
