### ISSUE TITLE
Binary release for OSX

### ISSUE THREAD

**Issue by saladuit** [Snaipe/Criterion#450]
I'm organizing a small hackathon on my campus and I'm wondering whether it is possible to make a portable folder that students can use. I'm part of the 42 network and for some reason they chose to work with MAC OS and to make it incredibly difficult to install certain things. I'm trying to create a boiler plate project that makes it easy to use criterion out of the box. Any other suggestions would also be very much appreciated!

**Comment by Snaipe** [comment]
Thanks to @MrAnno's efforts, Criterion is packaged and readily available on macOS via `brew` -- you should be able to tell your students to just `brew install criterion`. If you have issues in using the package, let us know.

There are a couple of community-maintained project skeletons under [`./dev`](https://github.com/Snaipe/Criterion/tree/bleeding/dev) though I haven't recently tested them. Feel free to hack on top of that and/or contribute new templates.

**Comment by saladuit** [comment]
So after many tries the way to solve our issue was to install brew into a folder like this: /sgoinfr.
And then install criterion over there via `brew install criterion`.  This made it possible for many users to acces it via the following commands:
```
export LIBRARY_PATH=/sgoinfre/criterion_test/.brew/lib:${LIBRARY_PATH}
export C_INCLUDE_PATH=/sgoinfre/criterion_test/.brew/include:${C_INCLUDE_PATH}
```
One more question: while preparing the presentation on how to use criteiron more or less, I'd found out that the old syntax was removed form the documentation. E.g. `cr_assert_str_eq()`
The new API is however recommended. Will the old one get deprecated?

**Comment by Snaipe** [comment]
The old one is indeed deprecated in favor of the new one -- that being said, the old API is not going anywhere for a while, and it is still documented over at https://criterion.readthedocs.io/en/master/assert_old.html. If it gets removed, it'll be for a major version bump like v3.0.0.

**Comment by MrAnno** [comment]
I believe this has been addressed by the Homebrew package.
Please reopen this issue if you have further related questions/issues.
