### ISSUE TITLE
segfault on assert fail with -O1

### ISSUE THREAD

**Issue by cybojanek** [Snaipe/Criterion#46]
When compiling test cases with anything other than -O0, a failed assert causes a program crash, instead of just a failure. Simple example:

```c
#include <criterion/criterion.h>

Test(cat, meow)
{
    cr_assert_eq(strlen("meow"), 5);
}
```

```bash
gcc -O0 test.c -o test -lcriterion
# OK
./test
gcc -O1 test.c -o test -lcriterion
# Segfault
./test
```

**Comment by Snaipe** [comment]
What operating system are you compiling the tests on ?
Also, is this happening with the stable release (a0af6a0af129fab0ab1fe63f54e5262bb6868304), or the current bleeding branch ?

**Comment by cybojanek** [comment]
98366789f6e5bf985f5d24e277c4d3fdb2226173
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

**Comment by Snaipe** [comment]
Does the commit f8e2054805dbf834a6c65debfe72c7496924e5bc happen to fix this ?

**Comment by cybojanek** [comment]
I did a git checkout to that commit and it works (I wasn't able to cherry pick f8e2054 onto 9836678 because it depends on a bunch of other stuff).

**Comment by Snaipe** [comment]
Ok, leaving this open for the moment as a reminder; it should be fixed when I merge the parameterized tests into bleeding.

**Comment by Snaipe** [comment]
The bug seems to have been there for a long time -- this is why I'm merging the fix now on both master and bleeding. v2.0.1 is now the recommended stable version.
