### ISSUE TITLE
v2.4.2 preparation

### ISSUE THREAD

**Issue by MrAnno** [Snaipe/Criterion#484]
I think #474 , #483, #473, and #465 are important enough to prepare a new bugfix release.

### Preparing release candidate

* [x] Make sure `bleeding` builds on all platforms and all tests pass (Apple silicon main() patching - known issue)
* [x] `git checkout master`
* [x] `git merge bleeding --no-commit --no-ff`
* [x] Bump project version (`meson.build`)
* [x] Bump ABI version when needed (`meson.build`)
* [x] Update ChangeLog
* [x] `git commit -m "release: v2.4.2"`
* [x] `git tag -s v2.4.2-rc`
* [x] `git push origin v2.4.2-rc master`

After publishing the RC tag, each new push on master will produce a new release candidate.
The `bleeding` branch is fast-forwarded automatically during the RC period.

### Finalizing release

After a 1-2 week RC period, the final version can be released:

* [x] `git checkout master`
* [x] `git tag -s v2.4.2`
* [x] `git push origin v2.4.2`

**Comment by Snaipe** [comment]
Looking over the PRs, #462 seems straightforward enough for inclusion too.

**Comment by MrAnno** [comment]
macOS is broken again :(
https://github.com/Snaipe/Criterion/runs/12611859561

I'll take a look at it.

**Comment by MrAnno** [comment]
I'm afraid we can no longer patch the main function on Apple silicon when the user provides their own main() function, or when linking statically.

My previous `VM_PROT_COPY` trick was probably a kernel bug, which has been patched.

I think I'm moving forward with the v2.4.2 release with this known issue.
