### ISSUE TITLE
Include debugbreak and klib in source zip file

### ISSUE THREAD

**Issue by cprieto** [Snaipe/Criterion#488]
Hi!

I had been working in a recipe to include this amazing library in the Conan Index so it can be used with Conan (https://conan.io/), so far it is a work in progress... But I had been facing some problems regarding including the submodule dependencies (debugbreak and klib), mostly because the policies and checks in the public repository for recipes.

I know this could be a too much to ask thing, but could we include the source for those given revisions of those submodules in the zip source file provided with each release? at least for future versions?

Keep the great work!

**Comment by MrAnno** [comment]
I'll take a look at this. I think we should just convert those 2 submodules to Meson subprojects.

Thanks for working on the Conan recipe.

**Comment by cprieto** [comment]
Oh thanks @MrAnno I thought about doing exactly the same with a patch for the main `meson.build` file and include wraps around it. I had not finished my patch yet but if so, I will submit the PR soon, would that be ok for you?

Would this be ready for the upcoming 2.4.2?

**Comment by cprieto** [comment]
PR submitted, only a problem with the required version for Meson in some build servers (Meson needs to be at least 0.55, we can include that restriction in the `project` definition). Besides that, it works without the need of submodules. :smile:
