### ISSUE TITLE
libgit2 has been updated to version 1.7.0

### ISSUE THREAD

**Issue by LeChatP** [Snaipe/Criterion#509]
Hello, I have recently noticed that Libgit2 has been updated to version 1.7.0, and unfortunately, the compiler has not declared Criterion as compatible. I was wondering if you have any information on whether Criterion will be compatible or not. Or should we stick to the previous version? Please note that I am using ArchLinux. Thank you!

**Comment by pauljoohyunkim** [comment]
Meanwhile, I guess, to use criterion on Arch, downgrade libgit2 either by locating version 1.6 tar.zst of libgit2 or downloading version 1.6 from [libgit2 archive](https://archive.archlinux.org/packages/l/libgit2/), then issuing
`sudo pacman -U [libgit2 version 1.6 tar zst file]`

You can always update it back to the newest version by full system update.

**Comment by pauljoohyunkim** [comment]
I was facing the same issue.

A similar issue was mentioned in an older comment in [criterion](https://aur.archlinux.org/packages/criterion) AUR page.

Full recompilation seems to have fixed the issue for me.

**Comment by MrAnno** [comment]
Please reopen the issue if recompiling the Criterion AUR package doesn't solve your issue.

You just have to recompile Criterion when one of its updated dependencies has an ABI change. For example:
```
paru -S --rebuild criterion
```
