### ISSUE TITLE
Redirected stdin C++ stream behaves weirdly with string literals on windows

### ISSUE THREAD

**Issue by Snaipe** [Snaipe/Criterion#51]
To reproduce:

```c++
Test(sample, simple) {
    auto& f_cin = criterion::get_redirected_cin();
    f_cin << "Foo";
}
```

This snippet will *not* feed the `"Foo"` string to `f_cin`, but its pointer.
This is horribly counter intuitive and violates the principle of least surprise.

A simple workaround to this would be to simply replace `"Foo"` by `std::string("Foo")`.

AFAIK, the issue only concerns Windows.

**Comment by am11** [comment]
@Snaipe, can you please make a more [self-contained example](http://sscce.org/) (with main instantiating a `&ofstream` and then expected/actual output)? I will pass it along to some concerned folks. :)

**Comment by Snaipe** [comment]
@am11 I managed to come up with a self-contained [example](https://gist.github.com/Snaipe/cc51a98fbc1ffb7af358) after a bit of tweaking around.

The issue arises only when:
1) the stream class is inherited.
2) the variable is typed as a reference of the inherited type (using a reference to `std::fstream`, for instance, works).

It seems to be a problem with the overload resolution picking up `operator<<` for `const void *` before the one for `const char *`.

GCC & Clang seem to both handle the resolution gracefuly.

**Comment by am11** [comment]
@Snaipe, thanks! On compiling with g++ 4.9, I am getting:

```sh
sh-4.3$ g++ --std=c++0x -o main *.cpp                                                                                                                                              

main.cpp: In instantiation of 'my_basic_fstream<CharT>::my_basic_fstream(FILE*) [with CharT = char; FILE = _IO_FILE]':                                                             

main.cpp:21:13:   required from 'static my_basic_fstream<CharT>& get_file_stream_<CharT>::call(FILE*) [with CharT = char; FILE = _IO_FILE]'                                        

main.cpp:28:36:   required from here                                                                                                                                               

main.cpp:11:64: error: no matching function for call to 'std::basic_fstream<char>::basic_fstream(FILE*&)'                                                                          

     my_basic_fstream(std::FILE *f) : std::basic_fstream<char>(f) {}                                                                                                               

                                                                ^                                                                                                                  

main.cpp:11:64: note: candidates are:                                                                                                                                              

In file included from main.cpp:3:0:                                                                                                                                                

/usr/include/c++/4.9.2/fstream:834:7: note: std::basic_fstream<_CharT, _Traits>::basic_fstream(const string&, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_tra

its<char>; std::string = std::basic_string<char>; std::ios_base::openmode = std::_Ios_Openmode]                                                                                    

       basic_fstream(const std::string& __s,                                                                                                                                       

       ^                                                                                                                                                                           

/usr/include/c++/4.9.2/fstream:834:7: note:   no known conversion for argument 1 from 'FILE* {aka _IO_FILE*}' to 'const string& {aka const std::basic_string<char>&}'              

/usr/include/c++/4.9.2/fstream:819:7: note: std::basic_fstream<_CharT, _Traits>::basic_fstream(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_trait

s<char>; std::ios_base::openmode = std::_Ios_Openmode]                                                                                                                             

       basic_fstream(const char* __s,                                                                                                                                              

       ^                                                                                                                                                                           

/usr/include/c++/4.9.2/fstream:819:7: note:   no known conversion for argument 1 from 'FILE* {aka _IO_FILE*}' to 'const char*'                                                     

/usr/include/c++/4.9.2/fstream:806:7: note: std::basic_fstream<_CharT, _Traits>::basic_fstream() [with _CharT = char; _Traits = std::char_traits<char>]                            

       basic_fstream()                                                                                                                                                             

       ^                                                                                                                                                                           

/usr/include/c++/4.9.2/fstream:806:7: note:   candidate expects 0 arguments, 1 provided                                                                                            
```

**Comment by am11** [comment]
I have further simplified the example with https://gist.github.com/am11/5341b87ce9eb6bdf2d15 with comments. Removing one (apparently) unrelated and unused line makes it compile with VCR. But Clang and GCC failed due to same issue: missing function signatures in std..

**Comment by Snaipe** [comment]
@am11 the sample is using a MSVC-specific constructor (the one taking a FILE*), I did not make the GCC/Clang specific version because it did not happen on both of them.

I added a [version](https://gist.github.com/Snaipe/cc51a98fbc1ffb7af358#file-poc_stream_weirdness_g-_compat-cc) which is GCC/Clang compatible, but it's not that interesting to be honest.

**Comment by am11** [comment]
@Snaipe, I agree its looks like spaghetti now. :stuck_out_tongue_winking_eye: 
Nonetheless, I will proceed with reporting to VC team and cross reference. FWIW, we reported some bugs after VS2015 RTM (released 29.07.2015) and they have fixed for VS2015 Update 1 (currently unreleased). For some reason their webcompiler site is down: http://webcompiler.cloudapp.net/, otherwise we could verify this one right away. 
Thank you for this effort! :+1:

**Comment by am11** [comment]
x-ref: https://connect.microsoft.com/VisualStudio/feedback/details/1816111.

**Comment by Snaipe** [comment]
@am11 I just reread the snippet you linked, but I think that the solution you provide to make it pass is a bit unfortunate: *unused_stream actively invokes undefined behaviour (you dereference a null smart pointer), and, well, the apparent "good" behaviour could be the result of an optimisation based on the fact that *unused_stream is invalid.

**Comment by am11** [comment]
@Snaipe, I have received an reply (via email) from VC team member:.

>
I've reduced this and I believe it is a compiler bug.  Here's a library-free repro:
>
>
C:\Temp>type meow.cpp
>```c++
namespace Std {
>
    template <class Elem> struct CharTraits { };
>
    template <class Elem, class Traits = CharTraits<Elem>> struct BasicOstream {
        void operator<<(const void *) = delete;
    };
>
    template <class Traits> void operator<<(BasicOstream<char, Traits>&, const char *) = delete;
}
>
template <typename CharT> struct MyOstream : Std::BasicOstream<char> { };
>
MyOstream<char> * stream;
>
#ifdef AVOID_TEMPLATE
    MyOstream<char>& call() {
#else
    template <typename RandomT = double> MyOstream<char>& call() {
#endif
    stream = new MyOstream<char>();
    return *stream;
}
>
int main() {
    MyOstream<char>& f = call();
    f << "Foo";
}
>```
>
C:\Temp>cl /EHsc /nologo /W4 meow.cpp
>
meow.cpp
>
meow.cpp(26): error C2280: 'void Std::BasicOstream<char,Std::CharTraits<Elem>>::operator <<(const void *)': attempting t
>
o reference a deleted function
>
        with
>
        [
>
            Elem=char
>
        ]
>
meow.cpp(5): note: see declaration of 'Std::BasicOstream<char,Std::CharTraits<Elem>>::operator <<'
>
        with
>
        [
>
            Elem=char
>
        ]
>
>
>
C:\Temp>cl /EHsc /nologo /W4 /DAVOID_TEMPLATE meow.cpp
>
meow.cpp
>
meow.cpp(26): error C2280: 'void Std::operator <<<Std::CharTraits<Elem>>(Std::BasicOstream<Elem,Std::CharTraits<Elem>> &
>
,const char *)': attempting to reference a deleted function
>
        with
>
        [
>
            Elem=char
>
meow.cpp(8): note: see declaration of 'Std::operator <<'
>
AVOID_TEMPLATE shouldn't affect the result of overload resolution, but it does.  I'll pass this along to the compiler team.

**Comment by Snaipe** [comment]
Awesome.

In the meantime, I guess I can remove the template on `call` (we use CharT = char anyways) since it's affecting resolution.
