### ISSUE TITLE
Unable to compile criterion on ArchLinux

### ISSUE THREAD

**Issue by virgilga** [Snaipe/Criterion#520]
I can't install Criterion via the AUR package repositories.
Test suite 48 / 48 fails:
![Screenshot_20240219_172126](https://github.com/Snaipe/Criterion/assets/105997554/d46c93a4-1d94-4706-a400-1aa364726f01)
Here is the log file:
[testlog.txt](https://github.com/Snaipe/Criterion/files/14334753/testlog.txt)

**Comment by MrAnno** [comment]
Thanks for opening this issue.

```diff
-  [====] Synthesis: Tested: 11 | Passing: 0 | Failing: 11 | Crashing: 0 
+  [====] Synthesis: Tested: 0 | Passing: 0 | Failing: 0 | Crashing: 0 
```

Looks similar to #436. I will check it.

**Comment by Orkie** [comment]
I also encountered this today while trying to build criterion from AUR. It definitely seems to be related to lto - it would appear makepkg is forcing `-flto=auto` into the CFLAGS env var, ignoring the PKGBUILD telling meson not to use lto.

I managed to work around this by taking a copy of /etc/makepkg.conf, and replacing `lto` with `!lto` in the `OPTIONS` line.

You can then download the PKGCONFIG and run `makepkg -si --config path/to/modified/makepkg.conf`. No ideal, but got me over the immediate issue.

This was on a machine which was freshly installed two days ago - one of my other machines which had Arch installed 3 years ago does not appear to have anything to do with lto in /etc/makepkg.conf and hence didn't have a problem installing criterion.

**Comment by Orkie** [comment]
Just noticed you can set options in PKGBUILD for a single package too- adding the following line fixes the problem without messing around with makepkg.conf:
```options=(!lto)```

**Comment by MrAnno** [comment]
@Orkie Thank you for the investigation, the AUR package `2.4.2-2` disables lto.
