### ISSUE TITLE
TAP output is broken with multiple jobs

### ISSUE THREAD

**Issue by Snaipe** [Snaipe/Criterion#65]
This happens because events (and hence logging) are no longer ordered when dealing with multiple jobs.
Since synchronizing is impossible without de-parallelizing everything, the best bet would be to print all the data during the POST_ALL stage.

**Comment by porglezomp** [comment]
I can't easily install a 4.9+ GCC on the machines I'm working with, how long do you think it'll be until there's a release with this fix in it?

**Comment by Snaipe** [comment]
@porglezomp I don't really know why this fix relates to you needing GCC 4.9+ -- truth to be told, this issue fixes a bug that was introduced on bleeding after the latest release.

IIRC, you should be able to compile the library with GCC 4.6 and later, but only if you disable the C++ bridge. You can do so by passing `-DLANG_CXX=OFF` to cmake.

Otherwise, the ETA for the next release should be in a matter of days. I don't want to rush it before I'm sure it's stable enough.

**Comment by porglezomp** [comment]
Oh, I assumed that the TAP bug was present in the previous release, I'm having trouble with the messages showing up as various Unicode garbage. If that wasn't in the previous release I may have a bug to report...

**Comment by Snaipe** [comment]
@porglezomp It's possible that your shell does not support ANSI coloring and/or unicode. What are you using?
In the meantime, you can completely disable these by passing `--ascii` to the test executable or define `CRITERION_USE_ASCII=1` in your environment variables. Does this help?

**Comment by porglezomp** [comment]
I'm using the Chrome OS shell, running Ubuntu in a chroot. I get colors perfectly fine if I run the test on its own, but if I enable TAP it turns crazy. Here's the output of a tiny sample test with a few different flags:

Does this look similar to the previous incarnation of this bug, or is this something new?
```
tests $ ./test_test.out   
[----] test_test.c:4: Assertion failed: Hello, World!
[FAIL] simple::test: (0.00s)
[====] Synthesis: Tested: 2 | Passing: 1 | Failing: 1 | Crashing: 0 
```
```
tests $ ./test_test.out --tap
TAP version 13
1..2
# Criterion v2.1.0

# Running 2 tests from simple
ok - simple::second_test  (0.00s)
not ok - simple::test  (0.00s)
?orld!_test.c:4: Assertion failed: �:\��/
```
Running the `--tap` invocation multiple times causes the last line to print as all of the following, and more:
```
>y��?orld!t.c:4: Assertion failed: 
  test_test.c:4: Assertion failed: �y�*Gc?orld!
?orld!_test.c:4: Assertion failed: 6(�k�_
  test_test.c:4: Assertion failed: ~�E&s;??orld!
  test_test.c:4: Assertion failed: |�)���?orld!
  test_test.c:4: Assertion failed: `�
  test_test.c:4: Assertion failed: 뒅pK2"?orld!
```

**Comment by Snaipe** [comment]
This seems to indeed be a bug. Could you open a new issue and include a self-contained test case along with the logs above and the commit hash that you are currently building against?

**Comment by porglezomp** [comment]
Opened #78, note that I'm working off the latest release version since I can't get the repository to compile on my system.
