### ISSUE TITLE
Modify `assert.h` to support clang

### ISSUE THREAD

**Issue by ckaran** [Snaipe/Criterion#74]
Clang supports `__typeof__` (see http://clang.llvm.org/docs/UsersManual.html#differences-between-various-standard-modes).  This means that `assert.h` can be modified to support clang in addition to gcc.  http://stackoverflow.com/questions/2658461/what-predefined-macro-can-i-use-to-detect-clang describes how to determine if clang is in use.  The macros you want to investigate are probably the following:
```
__clang__
__clang_major__
__clang_minor__
__clang_patchlevel__
__clang_version__
```

**Comment by Snaipe** [comment]
Doesn't it work already with clang? clang does define `__GNUC__` along with `__clang__` iirc.

**Comment by ckaran** [comment]
You're right, it does.  I was just hoping for something more explicit, so that when I grep through sources I have a better idea of what is supported by what.

**Comment by Snaipe** [comment]
Fair enough.
