### ISSUE TITLE
Add an interactive debugging mode

### ISSUE THREAD

**Issue by ckaran** [Snaipe/Criterion#85]
@Snaipe You started talking about adding an interactive mode to Criterion; that sounded sufficiently different from #82 that I decided to make this issue to track it separately.  If you don't think that's a good idea, then please close this issue.

**Comment by ckaran** [comment]
If you're going to make an interactive mode, I'd like to suggest combining this with any work using [nanomsg](http://nanomsg.org/index.html) or any of the other [similar options](http://queues.io/), and then to go ahead and define a full protocol for communications between the parent and children using something like [MsgPack](http://msgpack.org/index.html) as the serialization library.  This would make it possible to turn the children into servers in a client/server architecture, and have any language that is able to work with [nanomsg](http://nanomsg.org/index.html) and [MsgPack](http://msgpack.org/index.html) act as clients.  There a number of advantages to this, including:

- The children/servers can be run on dedicated test hardware while clients/parents can be run on completely separate hardware.  This way if you're doing something that may crash the server, you'll still get logs of what is going on up to when the crash occurred (modulo some lost data due to nanomsg's buffering).

- We can use scripting languages to drive the children and intelligently probe the results.  As an example, I use [Hypothesis](http://hypothesis.readthedocs.org/en/master/) to do what is essentially fuzz testing of my python code.  Using [Cython](http://cython.org/), I've been able to test my C code by making them python extension modules, and then letting [Hypothesis](http://hypothesis.readthedocs.org/en/master/) work its magic.

- By defining a communications protocol, you can separate out the shell/GUI from the tests.  That should keep Criterion a little cleaner (do you *really* want to write an interactive shell for a unit testing framework?)

**Comment by Snaipe** [comment]
This seems fair and would be the general direction to take to allow feature requests like #69 to be implemented.

There are clear issues on the current I/O system that were inherited from a time where it did not really matter, and cleanly rewriting this logic should keep things decoupled between the CLI front end, the server backend, and the test workers.

**Comment by am11** [comment]
[Protobuf](https://github.com/google/protobuf) or [Bond](https://github.com/microsoft/bond) can also be tested for ultra-fast [de]serialization.

**Comment by Snaipe** [comment]
The protocol shouldn't be complicated enough to require something like protobuf -- it would be like swatting a fly with a rocket launcher: highly effective but a tad overkill.

**Comment by ckaran** [comment]
You might also want to think of a JSON-based encoder; it's not as fast or compact, but when you're trying to debug why your messages aren't working right, the fact that its all text will be helpful (e.g., dump the output from the line to a file and just look at it).

**Comment by am11** [comment]
+1 for always having a version number in configuration/manifest files

Agree that Protobuf and Bond are heavy dependencies.

Aside (I have no intention to hijack this thread, just bouncing ideas):
I have recently started experimenting with JSON web token: http://jwt.io/. It tackles many similar (secure) communication scenarios using standardized approach. C implementation is also available: [libjwt](https://launchpad.net/~ben-collins/+archive/ubuntu/libjwt). Probably not highly imperative in this case either but if the intended architecture is implemented with some familiar technology, that will be an advantage over a brand new / custom-build approach. :)

Secondly if there be a need for debug 'mappings', again a know Base64-VLQ [source-map](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit?pli=1#!) may be a good choice (it is mostly used for source-to-source mapping by modern browsers and editors' previews in trans-compilation scenarios, but the technology itself is not limited to the said use-case). @mgreter has implemented it in C++ for libsass: https://github.com/mgreter/sourcemap.cpp (along with the [online inspector](http://libsass.ocbnet.ch/srcmap/index.html)). I once converted Mozilla's source-map JS [implementation](https://github.com/mozilla/source-map) to [C#](https://github.com/madskristensen/WebEssentials2013/blob/3d55a47/EditorExtensions/Shared/Helpers/Base64VLQ.cs).
.

**Comment by Snaipe** [comment]
Further discussions on the protocol and I/O rewrite will be done on #89.

**Comment by Snaipe** [comment]
This has been implemented on b6fb500 with a `--debug` flag that starts the tests with a debugging server waiting for incoming connections.

This renders obsolete the non-official `--single` mode flag.

An example on how to use this new flag is as follow:

```
$ ./test --debug
Process /home/snaipe/workspace/c/criterion/build/test created; pid = 16224
Listening on port 1234
```

```
$ gdb -q ./test
Reading symbols from ./test...done.
(gdb) target remote localhost:1234
  Remote debugging using localhost:1234
  Reading /lib64/ld-linux-x86-64.so.2 from remote target...
  Reading /lib64/ld-linux-x86-64.so.2 from remote target...
  Reading symbols from target:/lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
  0x00007ffff7dd9d90 in _start () from target:/lib64/ld-linux-x86-64.so.2
(gdb)
```

Simple as it goes.

The TCP port of the debugging server may also be changed with the `--debug_port` flag.

**Comment by ckaran** [comment]
Which branch is this fix on?  I've just recloned criterion, checked out each branch, and poked through everything I can in git, and I can't find the commit, nor do my built tests offer the `--debug` flag for me to use.

**Comment by Snaipe** [comment]
> Which branch is this fix on? I've just recloned criterion, checked out
each branch, and poked through everything I can in git, and I can't find
the commit, nor do my built tests offer the --debug flag for me to use.
>

This is live on `features/boxfort-sanboxing`. Note however that due to a
bug on the posix code, you'll have to `pkill -STOP gdbserver` (or
lldb-server) when you hit a SIGSTOP in the test.

Also, the branch is still unstable overall, I wouldn't recommend using it
until it gets merged back to bleeding.

**Comment by ckaran** [comment]
I saw that this is now in bleeding; do we still need to `pkill -STOP` the server, or does Criterion handle that at this point?

**Comment by Snaipe** [comment]
@ckaran everything now works out of the box without any extra steps.

Bleeding is mostly stable at this point and I will make a release candidate once #149 and #150 are fixed, so feel free to test the branch out if you're not using windows at the moment! In particular, `--debug` needs some feedback as there might be some gotchas we need to document between platforms.

**Comment by ckaran** [comment]
@Snaipe Sounds good!  I'm not using Windows, but I am using older versions of OS X and Ubuntu, so I may turn up some unexpected bugs that way...

**Comment by Snaipe** [comment]
Note that OS X doesn't ship with a gdbserver or lldb-server by default, so you'll have to install one of those (gdbserver if using gcc, lldb-server if using clang) if you want to use the `--debug` flag by default.
