### ISSUE TITLE
Make Criterion play nice with dmalloc

### ISSUE THREAD

**Issue by ckaran** [Snaipe/Criterion#87]
I've been using [Dmalloc](http://dmalloc.com/) to debug my memory problems.  It works well, but it fails miserably with Criterion, and I suspect that its because of the smart pointer support you've developed (dmalloc tries to replace calls to `malloc()`, etc., with macroized versions).  Do you know if it will be possible to make them play nice with each other?

Below is sample output of what I get with my code:

```
debug-malloc library: dumping program, fatal error
   Error: cannot locate pointer in heap (err 22)
debug-malloc library: dumping program, fatal error
   Error: cannot locate pointer in heap (err 22)
debug-malloc library: dumping program, fatal error
   Error: cannot locate pointer in heap (err 22)
debug-malloc library: dumping program, fatal error
   Error: cannot locate pointer in heap (err 22)
[----] test/test_ARL_pq_element.c:71: Unexpected signal caught below this line!
[FAIL] ARL_pq_element::_APQ_LEAST_VALID_ELEMENT_ID: CRASH!
[----] test/test_ARL_pq_element.c:96: Unexpected signal caught below this line!
[FAIL] ARL_pq_element::_APQ_new_element: CRASH!
[----] test/test_ARL_pq_element.c:60: Unexpected signal caught below this line!
[FAIL] ARL_pq_element::_APQ_INVALID_ELEMENT_ID: CRASH!
[----] test/test_ARL_pq_element.c:82: Unexpected signal caught below this line!
[FAIL] ARL_pq_element::_APQ_new_element_pool: CRASH!
[====] Synthesis: Tested: 4 | Passing: 0 | Failing: 4 | Crashing: 4 
```

**Comment by Snaipe** [comment]
This is weird, dmalloc should only be relevant to the memory you allocate inside the tests, right?
Any allocation happening outside the boundaries of dmalloc shouldn't interfere with it, and I'm not using smart pointers (or for that matter, any allocation) in the forked child.

For reference, what steps are you using to reproduce the above result ? (w/ minimal source if possible).

**Comment by ckaran** [comment]
Below is minimal test program (saved as `main.c`):

```C
#include <stdlib.h>
#include <criterion/criterion.h>
#include "dmalloc.h"

Test(Test_criterion,
     testing_dmalloc_behavior,
     .description="This is exceedingly simple code to show what happens when Criterion runs into Dmalloc.")
{
    char* junk = (char*) malloc(25 * sizeof(char));
    free(junk);

    cr_assert(true, "This should Just Work (TM)");
}
```

I compiled it using the following:

```
clang -Wall -Wextra -pedantic -std=c11 -I/usr/local/include -L/usr/local/lib -lcriterion -I/opt/local/include -L/opt/local/lib -ldmalloc -o main main.c
```

I set `dmalloc` up using `dmalloc -i 1 -l dmalloc.log high`, which yielded the following when running the `dmalloc` command by itself:

```
Debug-Flags 0x4f4ed03 (83160323) (internal token: high)
Address      not-set
Interval     1
Lock-On      not-set
Logpath      'dmalloc.log'
Mem-Limit    not-set
Start        not-set

Debug Malloc Utility: http://dmalloc.com/
  For a list of the command-line options enter: dmalloc --usage
```

This lead to the following crash:

```
debug-malloc library: dumping program, fatal error
   Error: cannot locate pointer in heap (err 22)
[----] main.c:9: Unexpected signal caught below this line!
[FAIL] Test_criterion::testing_dmalloc_behavior: CRASH!
[====] Synthesis: Tested: 1 | Passing: 0 | Failing: 1 | Crashing: 1 
```

As a note, to test this you'll not only need to compile and link against libdmalloc, you **must** set the dmalloc settings as I've shown above.  If you run the `dmalloc` utility and get the following:

```
Debug-Flags  not-set
Address      not-set
Interval     not-set
Lock-On      not-set
Logpath      not-set
Mem-Limit    not-set
Start        not-set

Debug Malloc Utility: http://dmalloc.com/
  For a list of the command-line options enter: dmalloc --usage
```

then you won't get any crashes.

**Comment by Snaipe** [comment]
I didn't have the issue you mention, however I had to use the threaded version of dmalloc by linking against `libdmallocth.a`, otherwise the program would complain that dmalloc had gone recursive.

Shell session:
```bash
$ clang -Wall -Wextra -pedantic -std=c11 -I/usr/local/include -L/usr/local/lib -lcriterion -I/opt/local/include -L/opt/local/lib -ldmallocth -o main main.c
$ eval $(dmalloc -i 1 -l dmalloc.log high)
$ ./main
[====] Synthesis: Tested: 1 | Passing: 1 | Failing: 0 | Crashing: 0
```

**Comment by ckaran** [comment]
How did you set up dmalloc on your machine?  It requires ```function dmalloc { eval `command dmalloc -b $*`; }``` be in your `.bash_profile` or `.bash_rc`.  

Also, when you execute `eval $(dmalloc -i 1 -l dmalloc.log high)`, what does the `dmalloc` command return?  On my machine, this is what I see:

```
$ dmalloc
Debug-Flags  not-set
Address      not-set
Interval     not-set
Lock-On      not-set
Logpath      not-set
Mem-Limit    not-set
Start        not-set

Debug Malloc Utility: http://dmalloc.com/
  For a list of the command-line options enter: dmalloc --usage
$ eval $(dmalloc -i 1 -l dmalloc.log high)
$ dmalloc
Debug-Flags  not-set
Address      not-set
Interval     not-set
Lock-On      not-set
Logpath      not-set
Mem-Limit    not-set
Start        not-set

Debug Malloc Utility: http://dmalloc.com/
  For a list of the command-line options enter: dmalloc --usage
$ dmalloc -i 1 -l dmalloc.log high
$ dmalloc
Debug-Flags 0x4f4ed03 (83160323) (internal token: high)
Address      not-set
Interval     1
Lock-On      not-set
Logpath      'dmalloc.log'
Mem-Limit    not-set
Start        not-set

Debug Malloc Utility: http://dmalloc.com/
  For a list of the command-line options enter: dmalloc --usage
```

As a result, when I run the commands you've got, I don't have any crashes, but if I do the following:

```
$ clang -Wall -Wextra -pedantic -std=c11 -I/usr/local/include -L/usr/local/lib -lcriterion -I/opt/local/include -L/opt/local/lib -ldmallocth -o main main.c
$ dmalloc -i 1 -l dmalloc.log high
$ ./main 
debug-malloc library: dumping program, fatal error
   Error: cannot locate pointer in heap (err 22)
[----] main.c:9: Unexpected signal caught below this line!
[FAIL] Test_criterion::testing_dmalloc_behavior: CRASH!
[====] Synthesis: Tested: 1 | Passing: 0 | Failing: 1 | Crashing: 1 
```

it crashes.

**Comment by Snaipe** [comment]
Here's what happens on my end:

```bash
$ dmalloc -b -i 1 -l dmalloc.log high
DMALLOC_OPTIONS=debug=0x4f4ed03,inter=1,log=dmalloc.log
export DMALLOC_OPTIONS
```

dmalloc outputs the definition of DMALLOC_OPTIONS, and I pass it to eval.

At first, dmalloc wasn't configured as a shell function, but it didn't change anything after defining it.

The full dmalloc log is generated, so it is running on my end.

I'm using dmalloc 5.5.2, I went to [the download page](http://dmalloc.com/releases/) and built it myself. Maybe this is something that happens on older versions of dmalloc?

**Comment by ckaran** [comment]
Weird... I have the same version of dmalloc installed.  I'm running on an OS X machine though... maybe something there?  What machine are you running on?

**Comment by Snaipe** [comment]
Ah, yes, I'm running it on linux. I'm going to try and fire it on my OS X VM.

**Comment by ckaran** [comment]
OK, I'm running OS X 10.9.5.  `uname -a` returns `13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64`

**Comment by Snaipe** [comment]
I can reproduce this on my OS X image. Why this is happening is beyond my understanding for the moment, but at least I know where to investigate.

In the meantime, I've heard that the support for valgrind on OS X is much better those days, so you might want to try it out.

On my OS X image:

```
$ valgrind ./main -q
==6450== Memcheck, a memory error detector
==6450== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==6450== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==6450== Command: ./main -q
==6450== 
==6451== 
==6451== HEAP SUMMARY:
==6451==     in use at exit: 35,321 bytes in 412 blocks
==6451==   total heap usage: 519 allocs, 107 frees, 42,798 bytes allocated
==6451== 
==6451== LEAK SUMMARY:
==6451==    definitely lost: 231 bytes in 1 blocks
==6451==    indirectly lost: 0 bytes in 0 blocks
==6451==      possibly lost: 0 bytes in 0 blocks
==6451==    still reachable: 0 bytes in 0 blocks
==6451==         suppressed: 35,090 bytes in 411 blocks
==6451== Rerun with --leak-check=full to see details of leaked memory
==6451== 
==6451== For counts of detected and suppressed errors, rerun with: -v
==6451== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
--6450:0:schedule VG_(sema_down): read returned -4
==6450== 
==6450== HEAP SUMMARY:
==6450==     in use at exit: 34,225 bytes in 410 blocks
==6450==   total heap usage: 522 allocs, 112 frees, 42,183 bytes allocated
==6450== 
==6450== LEAK SUMMARY:
==6450==    definitely lost: 231 bytes in 1 blocks
==6450==    indirectly lost: 0 bytes in 0 blocks
==6450==      possibly lost: 0 bytes in 0 blocks
==6450==    still reachable: 0 bytes in 0 blocks
==6450==         suppressed: 33,994 bytes in 409 blocks
==6450== Rerun with --leak-check=full to see details of leaked memory
==6450== 
==6450== For counts of detected and suppressed errors, rerun with: -v
==6450== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

Interestingly, valgrind is missing a suppression for allocated memory in the `currentlocale` function, which shows here as the 231 leaked bytes, but it can be ignored.

**Comment by ckaran** [comment]
I agree that valgrind is more powerful, but the false positive rate is quite high for my code because of all the third party libraries I link against (they commonly don't bother freeing memory at library shutdown).  I need to spend some time learning valgrind; if it has a way of ignoring certain chunks of code, then I can filter out the false positives.  As it stands though, even with scripts helping cull some of the junk, I'm getting several hundred false positives that I need to wade through :(.  Dmalloc doesn't have that problem; it only checks the code that its linked into.  

I can find a workaround though; at this point, I have two sets of test code, one that uses Criterion, and one that doesn't.  Not the ideal case, but doable.

**Comment by ckaran** [comment]
Cool, thank you!
