### ISSUE TITLE
Tests are not automatically registered in the deb distribution

### ISSUE THREAD

**Issue by Snaipe** [Snaipe/Criterion#91]
This seems to only be happening on .deb package builds.

To reproduce:

```bash
$ sudo add-apt-repository ppa:snaipewastaken/ppa
$ sudo apt-get update && sudo apt-get install libcriterion-dev
$ gcc -x c -o test - -lcriterion <<EOF
#include <criterion/criterion.h>
Test(sample, simple) { cr_assert_fail("It works"); }
EOF
$ ./test
[====] Synthesis: Tested: 0 | Passing: 0 | Failing: 0 | Crashing: 0
```

I suspect that the launchpad build system strips criterion or changes its symbols before packaging the deb.

Maybe we can't rely that much on the `__{start,stop}_<section>` linker variables to iterate through the tests, but instead we should retrieve them with dlsym.

Another possible fix could be to tell the build system to not strip the binary.

**Comment by am11** [comment]
Found [this answer](http://askubuntu.com/a/176431/77893) by @RAOF. I guess the last paragraph is most relevant. :)

**Comment by Snaipe** [comment]
Stripping debug symbols shouldn't be the issue -- after all, travis builds without `-g` work out of the box.

After thinking about it a bit much, I don't think that launchpad strips non-debug symbols either, as this would break all the executables using dlopen/dlsym.

Reading the [launchpad build log](https://launchpadlibrarian.net/229122530/buildlog_ubuntu-xenial-i386.criterion_2.2.0-2-ubuntu1%7Exenial1_BUILDING.txt.gz) indicates that there might be a command in the post processing that probably raises the resolution priority of the section linker variables inside `libcriterion.so`. In this case, using `dlsym` to retrieve these section symbols might be the best route.

**Comment by am11** [comment]
Regarding:

> dpkg-gensymbols: warning: new libraries appeared in the symbols file

There is documented way of avoiding this warning: https://www.debian.org/doc/manuals/maint-guide/advanced.en.html#librarysymbols.

**Comment by jblazquez** [comment]
I'm seeing this issue when using the `gold` linker instead of plain `ld`. It looks like the contents of the special `__start`/`__stop` sections aren't making their way to the executable.

**Comment by Snaipe** [comment]
Interesting. I will rewrite that part of the code to not use __start/__stop_cr_test.

**Comment by lbudai** [comment]
@jblazquez: could you try to set the `-no-as-needed` option to your linker?

**Comment by jblazquez** [comment]
@lbudai That didn't work:

```
$ gcc -fuse-ld=gold -Wl,-no-as-needed -o test test.o -lcriterion && ./test
[====] Synthesis: Tested: 0 | Passing: 0 | Failing: 0 | Crashing: 0 
$ nm test | grep tst
$ 
```

**Comment by Snaipe** [comment]
I can also confirm this on my end (with `-Wl,-no-as-needed` and `-Wl,--no-as-needed` since both were mentioned). I think that using self-introspection of the elf file to get section limits rather that using `__start_cr_test` might fix both issues.
